### ISSUE TITLE
JSON Schema definitions

### ISSUE THREAD

**Issue by sarneeh** [fastify/fastify#1058]
#### What are you trying to achieve or the steps to reproduce?

I'd like to use JSON Schema `definitions` for my fastify endpoints validation and serialization. After reading the [docs](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md) I'm not sure if fastify supports completely the JSON Schema format or not. The docs recommend it, but it doesn't work as I'd expect it.

I'd like to do something like this:

```js
const definitions = {
  user: {
    type: 'object',
    properties: {
      email: { type: 'string' }
    },
    required: ['email']
  }
};

const userEndpoint = {
  definitions,
  body: { $ref: '#/definitions/user' },
  response: {
    '2xx': { $ref: '#/definitions/user' }
  }
};
```

#### What was the result you received?

An error - `can't resolve reference #/definitions/user from id #`.

#### What did you expect?

I expect it to work 😄 

#### Context

* *node version*: 9.11.2
* *fastify version*: 1.8.0
* *os*: Mac

**Comment by delvedor** [comment]
Hi! Thank you for checking out Fastify!
For the incoming request validation, we do support full JSON schema specification thanks to [ajv](https://github.com/epoberezkin/ajv), while for the `response` part we do not, since we are using the JSON schema to improve the performances of the serialization (see [fast-json-stringify](https://github.com/fastify/fast-json-stringify)).

Because of this, the JSON schema `$ref` is not well supported, but we do provide a method to achieve this, [shared schemas](https://www.fastify.io/docs/latest/Validation-and-Serialization/#adding-a-shared-schema).

```js
fastify.addSchema({
  $id: 'greetings',
  type: 'object',
  properties: {
    hello: { type: 'string' }
  }
})

fastify.route({
  method: 'POST',
  url: '/',
  schema: {
    body: 'greetings#'
  },
  handler: () => {}
})
```

**Comment by sarneeh** [comment]
@delvedor Hmm... It's a pity that this API is not encapsulated. I love the `fastify` plugin system and this would be cool if this would be encapsulated also. Although it's not something critical to have 😄 I'll check out the API, thanks for the fast reply! 😄

**Comment by delvedor** [comment]
Before talking about the PR, do we want to support encapsulated schemas?

**Comment by delvedor** [comment]
https://github.com/fastify/fastify/issues/1351
