### ISSUE TITLE
Hook exceptions crash Fastify

### ISSUE THREAD

**Issue by cemremengu** [fastify/fastify#1129]
Not sure if this is a desired behavior (user should handle exceptions instead) but having something like 

```js
fastify.addHook('preHandler', (request, reply, next) => {
  throw new Error('test')
})


fastify.addHook('onResponse', (req, res, next) => {
  throw new Error('test')
})
```

on any hook will crash Fastify. Should it just handle the exceptions and return `500` (or at least log them and not crash) ? I think this can be patched via something like below but maybe there is a better solution

```js
function hookIterator(fn, reply, next) {
  if (reply.res.finished === true) return undefined

  try {
    return fn(reply.request, reply, next)
  } catch (err) {
    reply.sent = false
    reply._isError = true
    reply.send(err)
  }
}
```

```js
function onResponseIterator(fn, res, next) {
  try {
    return fn(res, next)
  } catch (err) {
    res.log.error({
      res,
      err
    }, 'request errored')
  }
}
```

**Comment by jsumners** [comment]
Same discussion as #850

**Comment by mcollina** [comment]
Would you like to add this section to the docs? A set of fresh eyes might help.

**Comment by cemremengu** [comment]
Sure, definitely. I will gather the comments from the previous issue as well.

**Comment by goliatone** [comment]
@mcollina I understand the reasoning for not handling errors is partially due to performance and because, well, it is hard. I find this take valuable during production but makes the development process very unfriendly. 
One of the things I really enjoyed about Sails was how friendly their errors are- they catch errors and provide suggestions/fixes for the most common ones. 

Is there a way to override this behavior during development and provide a better developer experience? What would be the best way to approach this?

**Comment by mcollina** [comment]
Development and production environments should be as close as possible. Such a huge difference will likely cause many production issues.

The best approach is to let the process crash on error, but use nodemon or similar in development to automatically restart the process
