### ISSUE TITLE
When will `preValidation hook` be released?

### ISSUE THREAD

**Issue by thomasyuan** [fastify/fastify#1256]
Just trying to create a test for my REST API today, and found that the schema validation gets executed before authentication which is exactly the #1105. 
I'm so happy that #1153 fixed this issue and get merged on Oct 1. But then I realized that it's not included in 1.13.0. 

Quick question, when will we release the next version or this feature?

**Comment by thomasyuan** [comment]
Or, just curious, should I use 'onRequest' for now? I believe it's not a perfect solution otherwise we won't create #1153.  What's the problem if I use 'onRequest' ?

**Comment by delvedor** [comment]
Fastify v2 has just been published, and the `preValidation` hook with it :)

**Comment by thomasyuan** [comment]
Cool!

**Comment by ahimanta** [comment]
regards

First of all, tell to you  that I am following your project, waiting for the promises of it to be fulfilled, so I encourage and good luck.

I take this comment to give my opinion: on the page and documentation appears that "fastify" has the option of preValidation but the code does not, be careful with these things since from what I have seen only you answer the questions that they are doing to the project, so giving a good impression is extremely important.

Another important point would be to present simple examples of to use different components of the ecosystem. it took me almost a week to undertand that how fastify work, that is too much especially because fastify seems simple to implement

**Comment by Eomm** [comment]
Hi @ahimanta ,
any feedback is always appreciated!
Let me understand better your point in order to improve our docs ✌

`preValidation` hook is documented [here](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#route-level-hooks) and [here](https://github.com/fastify/fastify/blob/master/docs) and you can find a deeper detail of "how fastify works".
Could you kindly tell us what document was not clear?
Maybe is better open a specific issue like "clarify document xxx" also

Anyway, when you have trouble writing some code you can open an issue in https://github.com/fastify/help . This repo is created to help the Fastify community 🎉
