### ISSUE TITLE
the default handler for 404 did not catch this

### ISSUE THREAD

**Issue by sebdeckers** [fastify/fastify#1374]
## 🐛 Bug Report

I have a server that is exposed to quote a bit of bot traffic, scanning for some known vulnerabilities in common web apps. Just saw this message from Fastify requesting me to report the error. HTH.

```
{"level":30,"time":1546828192808,"msg":"incoming request","pid":68741,"hostname":"iMac.local","reqId":804,"req":{"method":"GET","url":"http://5.188.210.50/echo.php","remotePort":19067},"v":1}
{"level":40,"time":1546828192809,"msg":"the default handler for 404 did not catch this, this is likely a fastify bug, please report it","pid":68741,"hostname":"iMac.local","reqId":804,"v":1}
{"level":40,"time":1546828192809,"msg":"└── / (ACL|BIND|CHECKOUT|CONNECT|COPY|DELETE|GET|HEAD|LINK|LOCK|M-SEARCH|MERGE|MKACTIVITY|MKCALENDAR|MKCOL|MOVE|NOTIFY|OPTIONS|PATCH|POST|PROPFIND|PROPPATCH|PURGE|PUT|REBIND|REPORT|SEARCH|SOURCE|SUBSCRIBE|TRACE|UNBIND|UNLINK|UNLOCK|UNSUBSCRIBE)\n    └── * (ACL|BIND|CHECKOUT|CONNECT|COPY|DELETE|GET|HEAD|LINK|LOCK|M-SEARCH|MERGE|MKACTIVITY|MKCALENDAR|MKCOL|MOVE|NOTIFY|OPTIONS|PATCH|POST|PROPFIND|PROPPATCH|PURGE|PUT|REBIND|REPORT|SEARCH|SOURCE|SUBSCRIBE|TRACE|UNBIND|UNLINK|UNLOCK|UNSUBSCRIBE)\n","pid":68741,"hostname":"iMac.local","reqId":804,"v":1}
```

## To Reproduce

This was not intentionally produced so I sadly have no reproduce steps.

## Expected behavior

Error message implies that the default 404 handler should deal with it.

## Your Environment

- *node version*: v11.6.0
- *fastify version*: 2.0.0-rc.2
- *os*: Mac
- *any other relevant information* This server listens on both HTTP and HTTPS. It's not clear from the log but most likely this was received on the HTTP port which gets most of the bot spam.

**Comment by mcollina** [comment]
I've debugged this a bit. It happens when somebody is sending a malformed HTTP/1.1 request.

```
GET http://5.188.210.50/echo.php HTTP/1.1

```

Can you confirm `5.188.210.50` is the IP address your server is hosted on?

Normally it should be something like:

``` 
GET /docs/index.html HTTP/1.1

```

find-my-way assumes that all URLs starts with `/`.

---

In https://tools.ietf.org/html/rfc2616#section-5.1.2:

> To allow for transition to absoluteURIs in all requests in future
   versions of HTTP, all HTTP/1.1 servers MUST accept the absoluteURI
   form in requests, even though HTTP/1.1 clients will only generate
   them in requests to proxies.

That `GET http://5.188.210.50/echo.php HTTP/1.1` is actually valid syntax, so we should theoretically support it. I'd also argue that this is Node.js responsibility see https://nodejs.org/api/http.html#http_message_url.

I think the best approach in this case is to check in https://github.com/fastify/fastify/blob/master/fastify.js#L844 if the URL does not start with a `/` and return a proper error that explain what the client is doing wrong.

Also.. can you check if express does actually handle this case?

**Comment by sebdeckers** [comment]
So I don't know if this is intended behaviour but Express does in fact route to handlers of `/echo.php` when using an absolute URL in the request. And the `request.url` property contains the entire string.

```js
const express = require('express')
const app = express()
app.use((request, response, next) => {
  console.log(request.url)
  next()
})
app.get('/echo.php', (request, response, next) => {
  console.log('GOT IT')
  next()
})
app.listen(8080)
```

```
$ telnet localhost 8080
GET /echo.php HTTP/1.1
[...]
$ telnet localhost 8080
GET http://5.188.210.50/echo.php HTTP/1.1
[...]
```

Node shows:

```
/echo.php
GOT IT
http://5.188.210.50/echo.php
GOT IT
```

**Comment by delvedor** [comment]
We'll fix this in [`find-my-way`](https://github.com/delvedor/find-my-way) :)

**Comment by amer8** [comment]
Same Fastify warning when the path contains a `%`.

**Comment by delvedor** [comment]
We have just released a new version of our router, can you update your dependencies and try again? Thanks!
