### ISSUE TITLE
Dynamic schema for route 

### ISSUE THREAD

**Issue by kromol** [fastify/fastify#1376]
## 🚀 Feature Proposal

Ability to set schema for route dynamically ( for example in `preValidation`)

## Example

I see at least two use cases for this feature:

1. When one URL serves several versions of the resource (expected version passed in header) then it would be great to have ability to inject correct schema.
2. Sharing one schema for request and response with `readOnly` and `writeOnly` attributes. This approach requires schema preprocessing in order to create two schemas dynamically (since `Ajv` does not have any option to validate only read only or write only of attributes) - with `readOnly` (for response) and with `writeOnly` (for request) properties.

**Comment by delvedor** [comment]
I think this can be easily implemented in a plugin.
Do you want to try?

**Comment by kromol** [comment]
Yes, I'd like to give it a try. I will think what would be the best way to do it in `fastify` way and come with my suggestions soon so you can let me know if it's good direction.

**Comment by kromol** [comment]
I checked `fastify` source code and as far as I understand schemas for each route are processed when the application starts and then are internally cached. So it's still not clear how to inject it via plugin in runtime. It does not seem feasible with current setup...
But I could be wrong here. @delvedor can you advise please?

**Comment by Eomm** [comment]
Hi, @kromol , I worked these weeks on that piece of code.

Could you show me an example use case to understand better?
So I could try to help you with what I know 🙌

**Comment by kromol** [comment]
The use case is pretty simple - ability to choose (define) schema in the request lifecycle. Right now I can do it only for route and there is no way to access it for example in `preValidation` hook.

It can be very useful if one route serves different versions of the resource and you don't know in advance which version will be requested. For example like this:
```
application/vnd.my-resource+json;v=1
application/vnd.my-resource+json;v=2
application/vnd.my-resource+json;v=3
```

So I want to be able to select correct schema based on the `Accept` or `Content-Type` headers of the request.

**Comment by mcollina** [comment]
Fastify currently support API versioning via https://github.com/fastify/fastify/blob/master/docs/Routes.md#version.

It would be good to support multiple validations (and maybe serializers) per content type. Would you like to send a PR for that feature? It's a complex one, and I would like not to break compatibility with fastify-swagger. We should aim to retain performance/throughput as well.

**Comment by Eomm** [comment]
@kromol , except the writeOnly and readOnly cases, this example fit for yours needed?
Because it works with fastify v2.RC6

```js
const fastify = require('fastify')({ logger: true })

fastify.register(async function (instance, opts) {

  const singleHandler = async function (request) {
    console.log(request.body)
    return request.body
  }

  const schemaWithoutA = { type: 'object', properties: { this: { type: 'string' } }, required: ['this'] }
  instance.post('/', {
    version: '1.0.0',
    handler: singleHandler,
    schema: {
      body: schemaWithoutA,
      response: { '2xx': schemaWithoutA }
    }
  })

  const schemaWithA = { type: 'object', properties: { this: { type: 'string' }, a: { type: 'string' } }, required: ['a'] }
  instance.post('/', {
    version: '2.0.0',
    handler: singleHandler,
    schema: {
      body: schemaWithA,
      response: { '2xx': schemaWithA }
    }
  })
})

fastify.listen(3000)

// curl -X POST 'http://localhost:3000/' -H 'Content-Type: application/json' -H 'Accept-Version: 1.x' -d '{ "this": "is", "b": "json" }'
// curl -X POST 'http://localhost:3000/' -H 'Content-Type: application/json' -H 'Accept-Version: 2.x' -d '{ "this": "is", "a": "json", "b": "hello" }'
```

**Comment by kromol** [comment]
@Eomm unfortunately that's not what I'm looking for. Actually I want to avoid defining the same routes just to inject different schema. As a workaround I can use `beforeHandler, define some logic there and validate incoming request with `Ajv`, but I believe much better option would be to use the built-in functionality if it's possible.

@mcollina I would give it a try.

**Comment by Eomm** [comment]
Hi @kromol 
to be sure, the behaviour you are looking for is this:

![image](https://user-images.githubusercontent.com/11404065/53291481-4a32e080-37b4-11e9-85af-e7731b39f7cc.png)

right?

Because I was thinking that this could be automatized with a plugin that adds many routes for you.

Here you are a pseudo-code:

```js
function muldex (fastify, opts, next) {
  fastify.decorate('muldex', (url, opts, handler) => {
    opts.multiplex.forEach(item => {
      fastify.post(url, item.schema, item.version, handler)
    })
  })
  next()
}
```

This is the first draft, I should think better the method signature.

**Comment by Eomm** [comment]
I have thinked how we could apply a conditional validation. So I would like propose this API change,
maintaining the backword compatibility. This in order to be a semver-minor change.
The `schema.<fields>` will accept:

+ a JSON: all remain as is
+ an array of JSON

If it is an array of JSON, each element must be like this one:

```js
{
  jsonSchema: <put the usual JSON schema>,
  applyOn: function (req) { true || false }
}
```

When a request arrives the `applyOn` function is executed and, if it return `true` the validation
is applied agains the `jsonSchema` attached.

When there are multiple elements on the array, the validation applied is *the first one* that return
`true`. The array will be read in order.

If none function `applyOn` of the array return `true`, the validation is skipped.

This let you to do validation against headers or whatever the `res` object contains, or at least 
define the function parameter with only headers (`function (headers) { true || false }`)
I would let also the function sync.

What do you think @mcollina ?

Example:

```js
const schema = {
  body: [{
    jsonSchema: { <json schema for body 1> },
    applyOn: function (req) { true || false }
  }, {
    jsonSchema: { <json schema for body 2> },
    applyOn: function (req) { true || false }
  }],
  params: { <usual json schema> }
}

fastify.post('/the/url', { schema }, handler)
```

**Comment by mcollina** [comment]
I'm not super comfortable with that change, because that would break fastify-swagger and the `onRoute` hook.

**Comment by Eomm** [comment]
Good point, for sure I should check if swagger standard supports this kind of mechanism and update that plugin, but `onRoute` shouldn't be affected: this change impact that part of the code, but the API should remain the same (there shall be a change in the `Context` object in order to track the different compiled schemas).

Anyway I will try to think a better approach ✌

**Comment by Eomm** [comment]
**New proposal**:

We could incentivize the use of [`oneOf`](https://json-schema.org/understanding-json-schema/reference/combining.html#oneof) property.
In fact the feature request is: "I want that my request will be validated against one of these schemas based on <xyz> condition"

The integration with the codebase, instead, it could be done with a plugin `fastify-schema-constraint` like this:

```js
const pluginOpts = {
  body: { constraint: function (req) { return req.header.length > 0 ? "#schema1" : "#schema2" } },
  querystring: { constraint: function (req) { return req.header.length > 0 ? "#schema3" : "#schema4" } },
  params: { constraint: function (req) { return req.header.length > 0 ? "#schema5" : "#schema6" } },
  headers: { constraint: function (req) { return req.header.length > 0 ? "#schema7" : "#schema8" } }
}

fastify.register(require('fastify-schema-constraint`), pluginOpts)

fastify.post('/',
  {
    schema: {
      body: {
        "oneOf": [
          { $id: "#schema1", "type": "number", "multipleOf": 5 },
          { $id: "#schema2", "type": "number", "multipleOf": 3 }
        ]
      }
    }
  },
  handler)
```

The `fastify-schema-constraint` will be executed as `preHandler` hook and will check that the validated request is exactly the $id returned by the function.

+ if the function isn't set for almost a parameter: error on startup
+ if the function returns `null || undefined` at runtime, the validation will be skipped
+ if the function throws an exception or return something that is not a string, the response will be a 500
+ if the function return a string, it need to be the `$id` of one of the schemas in the `oneOf` array otherwise the response will be a 500
+ if the returned string doesn't match the validated object the response will be a 500
+ if the returned string match the validated object the handler will be executed

In this way we can remain in the standard boundaries and release this feature. The example schema doesn't break the the actual
version of `fastify-swagger` but it doesn't suggest any model.... **why?!?**

----

I go deeper in this analysis of swagger and I think that, in any case, the `fastify-swagger` plugin need to be updated.
The plugin support `swagger 2.0` but is an old specification [2014-09-08](https://swagger.io/specification/).
The `oneOf` JSON schema keyword has been added in [OPEN API v3](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/).
[Here](https://swagger.io/docs/specification/data-models/keywords/) are list all the keywords supported in OAS3 and some differences with JSON Schema (need to implement an adapter).
Dulcis in fundo: there is an open bug on the visual part of the `oneOf` https://github.com/swagger-api/swagger-ui/issues/3803 (but I hope they will fix it)
I will open an issue on our plugin for this update

**Comment by Eomm** [comment]
Released the plugin [fastify-schema-constraint](https://github.com/Eomm/fastify-schema-constraint#readme)

Note: it needs the last fastify versione ^2.2.0
