### ISSUE TITLE
meta/ci: integration of Azure permissions with Fastify org and teams

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#1483]
This is a meta issue to track how we can have better integration between Fastify and Azure. @martinwoodward has kindly offered his help, thanks!!

Currently, the account members and teams need to be added manually: there is no integration between Github and Azure. We would expect that every member of the org can add new projects in Azure, create and run builds.

It would be even more helpful that members of every team we have will have different access levels, for instance we have a `fastify` team (I know, we are good at naming things) that should be able to work with every repo, while other teams, such as `fast-son-stringify` or benchmarks should be able to work only with specific repositories.

**Comment by martinwoodward** [comment]
Thanks folks.  Which of the repos in the fastly org need a corresponding CI build (and who should be an admin for it?)

|  repo     |  Needs CI (X)  | Admin(s) |
| -------- | --------------- | --------- |
| fast-json-stringify |       |               |
| fastify | | |
| fastify-cli | | |
| graphics | | |
| middie | | |
| fastify-plugin | | |
| point-of-view | | |
| fastify-swagger | | |
| fastify-mongodb | | |
| fastify-redis | | |
| fastify-multipart | | |
| fastify-bearer-auth | | |
| fastify-bankai | | |
| fastify-nextjs | | |
| fastify-websocket | | |
| fastify-jwt | | |
| fastify-helmet | | |
| fastify-auth | | |
| fastify-leveldb | | |
| fastify-accepts | | |
| fastify-accepts-serializer | | |
| website | | |
| fastify-static | | |
| fastify-formbody | | |
| benchmarks | | |
| fastify-cookie | | |
| fastify-env | | |
| example | | |
| fastify-example-twitter | | |
| fastify-register-timeout | | |
| fastify-caching | | |
| light-my-request | | |
| fast-formdata-stringify | | |
| fastify-postgres | | |
| fastify-url-data | | |
| under-pressure | | |
| fastify-kafka | | |
| fastify-mysql | | |
| fastify-compress | | |
| any-schema-you-like | | |
| fastify-reply-from | | |
| fastify-http-proxy | | |
| fastify-citgm | | |
| fastify-zipkin | | |
| help | | |
| fastify-circuit-breaker | | |
| fastify-rate-limit | | |
| fastify-elasticsearch | | |
| fastify-autoload | | |
| fastify-routes-stats | | |
| fastify-sensible | | |
| fastify-basic-auth | | |
| docs-chinese | | |
| fastify-oauth2 | | |
| fastify-soap-client | | |
| fastify-cors | | |
| fastify-routes | | |
| fluent-schema | | |
| fastify-jitson | | |
| fastify-example-todo | | |
| env-schema | | |
| fastify-server-timeout | | |

**Comment by delvedor** [comment]
@martinwoodward currently we are testing [fastify](https://github.com/fastify/fastify), and I wanted to add [fast-json-stringify](https://github.com/fastify/fast-json-stringify) since we are still in the "trying phase" with Azure.

> (and who should be an admin for it).

What does it mean "be an admin"?

**Comment by mcollina** [comment]
We would like any member of the Github org to be able to set up CI, more or less how they can create git repos.

**Comment by martinwoodward** [comment]
Got it - so everyone here should have admin rights? https://github.com/orgs/fastify/people

**Comment by mcollina** [comment]
That's the idea. However, they should not be able to do billing-related things.

**Comment by martinwoodward** [comment]
Speaking with the team, the issues we're having here are because this account got created as backed by Azure Active Directory. I want to switch this to be backed by a Microsoft account (MSA) so that you'll have a better experience.  DM'd you @mcollina - can you create a Microsoft Account using the same email address that you have as your default for GitHub and then let me know what it is?  If you don't have a Microsoft Account yet you can create one from https://signup.live.com

**Comment by jsumners** [comment]
> If you don't have a Microsoft Account yet you can create one from https://signup.live.com

This is a barrier to entry I just don't want to deal with.

**Comment by martinwoodward** [comment]
> This is a barrier to entry I just don't want to deal with.

Understood - I'm working on that part also.

**Comment by martinwoodward** [comment]
Ok, moved the account out from a AAD backed account to one that is just backed by MSA's and owned by @mcollina using his gmail account.  I recommend that we keep all the build definitions for the Fastify org in the same project in Azure DevOps just to have less navigation etc. If we find that we want more fine-grained security control in the future we can move stuff out into seperate projects but doesn't sound like we want that.

Therefore all builds can be viewed (and administered) from this link:
https://dev.azure.com/fastify/fastify/_build 

At the moment @mcollina, @delvedor, @StarpTech and myself are able to create and edit build definitions from this button in the link above:

![image](https://user-images.githubusercontent.com/856858/53629690-1a496a00-3c06-11e9-8472-d69c7aaa1fe7.png)

I'll work on setting it up so that all authorised and authenticated members of the fastify team will be able to do this next.

**Comment by martinwoodward** [comment]
OK - have it set up so that anyone in the fastify team can create and edit builds in the fastify project.  Note that at the moment only @mcollina, @delvedor, @StarpTech and me can invite people into the fastify team by pressing the Invite button on https://dev.azure.com/fastify/fastify

![image](https://user-images.githubusercontent.com/856858/53631996-c0e43980-3c0b-11e9-8898-866bffd3aaad.png)

If you want me to make it so that anyone on the team can invite anyone just let me know.

**Comment by mcollina** [comment]
I should have invited all of @fastify/fastify. Can you please check if you can restart a build in https://dev.azure.com/fastify/fastify/_build?

**Comment by Ethan-Arrowood** [comment]
I can successfully restart a build 👍

**Comment by Eomm** [comment]
I can't restart a build

**Comment by mcollina** [comment]
> I can't restart a build

You are in now. You should try to log in using behemoth89@gmail.com.

**Comment by Eomm** [comment]
Confirmed ✌

**Comment by delvedor** [comment]
Closing as we'll move to GitHub Actions.
