### ISSUE TITLE
send multipart/form-data

### ISSUE THREAD

**Issue by borodadada** [fastify/fastify#1596]
Hello, how i can send file + json data, i need multipart/form-data? Now i use application/octet-stream, but its only file data.

**Comment by dalisoft** [comment]
Hello @borodadada!
I'm using [this plugin](https://github.com/fastify/fastify-multipart#usage) and works good.

**Comment by borodadada** [comment]
hmmm i try add in project
`
D:\js\mongodb\node_modules\fastify\lib\contentTypeParser.js:40
    throw new FST_ERR_CTP_ALREADY_PRESENT(contentType)
    ^
FastifyError [FST_ERR_CTP_ALREADY_PRESENT]: FST_ERR_CTP_ALREADY_PRESENT: Content type parser 'multipart' already present.
`

not work...

**Comment by borodadada** [comment]
Then i intall plug and use
`
const multipart = require('fastify-multipart')
fastify.register(multipart)
`
error
'
D:\js\mongodb\node_modules\fastify\lib\contentTypeParser.js:40
    throw new FST_ERR_CTP_ALREADY_PRESENT(contentType)
    ^
FastifyError [FST_ERR_CTP_ALREADY_PRESENT]: FST_ERR_CTP_ALREADY_PRESENT: Content type parser 'multipart' already present.
    at ContentTypeParser.add (D:\js\mongodb\node_modules\fastify\lib\contentTypeParser.js:40:11)
    at Object.addContentTypeParser (D:\js\mongodb\node_modules\fastify\lib\contentTypeParser.js:245:30)
'

i don't install restify-multipart, his added in default? 

add in project
`
                const mp = request.multipart(handler, done, options)
                mp.on('field', function (key, value) {
                    console.log('form-data', key, value)
                })

                function handler (field, file, filename, encoding, mimetype) {
                    pump(file, fs.createWriteStream('a-destination'))
                }
                function done (err) {
                    console.log('upload completed')
                    _reply.code(200).send()
                }
`

but how it work?
How add json object, file?

**Comment by Eomm** [comment]
Hi,
I think you are trying to use plugin `fastify-file-upload` and `fastify-multipart` in the same fastify instance. This is not possible since both the plugins add a content parser. (you can use both in different encapsulated context)

So, in your example, you should use only one of the two.

With `fastify-multipart` you can receive `multipart/form-data` so you will be able to receive:
+ input type file
+ other input types (text, email, password, textarea etc...)

So for sure, you can send a single POST with a file and a stringify JSON.

But it is not clear to me if you want to send a JSON file. In this case, you should receive in your server get the file content and then parse it to a JSON

@borodadada consider writing more precise questions in order to give you more precise help 😃

**Comment by borodadada** [comment]
fastify-file-upload - i use for receive file on server side from client side. On client i create multipart/form-data ( Axios ) ( file + other json data ), and all work good. 
Now i need send file from server side to client side. From client side i send download file command, on server side i need create reply file data + file info (json). Whats i need for this? 
Ohhh.....

**Comment by Eomm** [comment]
I think you can use `form-data` lib in your server, so you can pump your "server-form" to the `reply` object.

[Here](https://github.com/fastify/fastify-multipart/blob/master/test/multipart.test.js) you can find some example (from client-to-server) but it should work on both the ways.

For sure Axios should parse the multipart data: I don't know if it has this feature

**Comment by borodadada** [comment]
Eomm thanks, i wiil try

**Comment by Eomm** [comment]
Feel free to share if you succeed or reopen if you have any trouble 👍
