### ISSUE TITLE
Using schemas in route declarations mutates them

### ISSUE THREAD

**Issue by sarneeh** [fastify/fastify#1635]
## 🐛 Bug Report

Just like in the title - when you use a schema object, i.e:

`fastify.get('/', { schema: { body: someObj } }, () => {})` 

The `someObj` is not cloned and directly mutated (the `$id` property is being deleted).

## To Reproduce

```js
const assert = require("assert");
const fastify = require("fastify");
const server = fastify();

const schema = {
  $id: "schema",
  type: "object",
  properties: {
    hello: {
      type: "string"
    }
  }
};

server.get("/", { schema: { body: schema } }, () => {});

server.ready().then(() => {
  assert.ok(schema.$id);
});
```

## Expected behavior

I expect `fastify` to not mutate the data i put into it, especially when the subject are JSON schema definitions (as one would most probably like to reuse them as much as possible).

## Your Environment

- *node version*: 10
- *fastify version*: 2.3.0
- *os*: Linux

**Comment by sarneeh** [comment]
I wanted to resolve this issue by myself but unfortunately, I didn't manage to do this in the timebox I had. This issue is most probably related to the `validation.build` method which calls `resolveRefs` which in the end clears the `$id`'s. For someone who will take this, here's a failing test case for `validation.js`:

```js
test('build schema - schema objects are being cloned', t => {
  t.plan(1);
  const schema = {
    $id: 'schemaId',
    type: 'string'
  }
  const opts = {
    schema: {
      body: schema
    }
  };
  validation.build(
    opts,
    () => {
      t.ok(schema.$id)
      return () => {};
    },
    new Schemas()
  );
});
```

**Comment by Eomm** [comment]
Could you try to put a second `true` parameter here?

https://github.com/fastify/fastify/blob/ec4564abe3df40f4ff6dd27517a5eb721c3c2333/lib/validation.js#L29

```js
context.schema = schemas.resolveRefs(context.schema, true)
```

I'm not sure this will pass all the tests

**Comment by Eomm** [comment]
I'll write down a little analysis of the problem as a memo:
the fix for #1553 assumes that a JSON schema is added using `addSchema` that clone the schema parameter and don't remove the `$id` because someone else will think of it.

Then the user adds the routes and builds the validator function for that is stored in the context.

During this build phase the `resolveRef` function:
- execute the `replace-way` substitution of the `shared-schema`s
- removes all the `$id`s from the objects if they *don't* match this `/^#[A-Za-z]{1}[\w-:.]{0,}$/` pattern (that is the JSON schema standard pattern for the `$id`)

So, for your problem @sarneeh, I suggest changing the value of `$id = '#schema'` if it is possible for you.

Anyway, for sure this is a bug related to the `shared-schema`, but it is a bit tricky because there are cyclic objects and a clone is not a solution, I need more time to fix it in the best way.

**Comment by sarneeh** [comment]
@Eomm Thank you for this analysis!

I've tried the `#id` solution and it works! 

But I'm pretty confused about the standard for `$id` you're mentioning, because the only standard that I'm aware of is - quoting the [docs](https://json-schema.org/understanding-json-schema/structuring.html#id): `It is best practice that every top-level schema should set `$id` to an absolute URI, with a domain that you control`. I didn't hear about a `#id` standard for schema identifiers. Is it really a standard? If yes, then maybe we should improve the [fastify examples](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#adding-a-shared-schema) on `replace-way` schemas so nobody would run into this issue?

Anyways, thank you for taking the time to understand this problem and providing a solution :smiley:

**Comment by Eomm** [comment]
Here you are the sources:
- [$id standard](https://tools.ietf.org/html/draft-handrews-json-schema-01#section-8.2)
- [$id pattern](https://tools.ietf.org/html/draft-handrews-json-schema-01#section-8.2.3)

About the examples.. the possibilities are so many that I found really hard also build that set 😅
If you would like to add some info that would have been useful I appreciate it 👍

**Comment by delvedor** [comment]
Can we close this?

**Comment by sarneeh** [comment]
@delvedor Yes! Sorry, I forgot about this issue. Closed.
