### ISSUE TITLE
expose find-my-way interface 

### ISSUE THREAD

**Issue by sandro-pasquali** [fastify/fastify#1757]
## 🚀 Feature Proposal

Reflect the API of `find-my-way` on `fastify` api.

## Motivation

I'd like to dynamically disable routes (and re-enable them). So if I could get to this https://github.com/delvedor/find-my-way#offmethod-path somehow

## Example

fastify.off(`/route/`);

**Comment by allevo** [comment]
Do you mind to allow enable and disable route on the fly? If the server is already started?

**Comment by delvedor** [comment]
We don't expose the `.off` interface because Fastify "compiles" all your configuration into an internal fast data structure, and the only way to change it is by stopping and rebooting the server again.

What you can do, however, is to create a hook that returns 404 on the routes you want to disable based on a logic chosen by you.
The result for the end-user will be the same.

**Comment by sandro-pasquali** [comment]
Thanks. As necessity often does, this constraint led me to simply use a proxy for route handlers, such that the proxy could decide whether to handle the route or not. (Also allows hot reloading of route handlers, btw).
