### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by IwHy4XnXCM** [fastify/fastify#181]
First of all, congratulations, this library looks fantastic.

I've looked through the documentation and can't find any mention of HTTP/2 support. Is there anything in the works? Would it be easy or difficult to implement?

Thanks!

**Comment by delvedor** [comment]
Hi, thank you for the interest!
At the moment HTTP/2 is not supported, but we are working on it ;)

**Comment by UNST4BL3** [comment]
@delvedor Thanks! I'll also ask this here - I believe the library could be sped up by eliminating a function call. Fastify responds using something like `reply.send({ hello: 'world' })`. Koa responds simply by `ctx.body = 'world'`. Thoughts on this?

**Comment by delvedor** [comment]
I don't know Koa really well, but somewhere a function call must be done to send the data back to you clients, as far as I know they use a lot `async/await`, probably they are doing something there.
But again, I'm not a koa user.

Regarding the `.send` api is needed, because we perform different operation once you call it, such as hooks and logging.

If you want you can also use `async/await` and just return the value:
```js
fastify.get('/return', async (req, reply) => {
  return { hello: 'world' }
})
```

Check out the docs about [reply](https://github.com/fastify/fastify/blob/master/docs/Reply.md#promises) :)

**Comment by mcollina** [comment]
I think we should implement HTTP/2 support using the `--expose-http2` flag in Node 8.

**Comment by codepunkt** [comment]
Yes, please! Having http2 would make me try this instead of express for my next API :-)

**Comment by develar** [comment]
If someone will use Fastify and Server Push — it really works. Pitfall is that `:path` must starts with `/` otherwise `stream` event will be not fired on client (and it is not Fastify issue, the same if use http2 module directly).

**Comment by delvedor** [comment]
@develar thanks for sharing!
