### ISSUE TITLE
Is it a good practice to do decorateRequest the DB client?

### ISSUE THREAD

**Issue by bittukr20** [fastify/fastify#1834]
- I am writing the route handlers in different files as there are many routes and writing in same file it's make it bulky.
- So I wanted to know instead of doing "fastify.decorate(db, 'dbConnectionObject')", If I am doing "fastify.decorateRequest(db, 'dbConnectionObject')", then I will be getting dbClient by "request.db" itself, will it be a good practice or not.
- is there will be any performance decrement with that.
- Current approach that I am following is: 

**Route Handler file code example:** 
```
const handlerFunction = fastify => async (request, reply) => {
    const client = fastify.dbClient;
    //do something with db client
}
```

**Route Declartion file code example:** 
```
async function(fastify) {
  fastify.route({
    method: "GET",
    url: "/something",
    schema: abc,
    handler: handlerFunction(fastify)
  });
};
```

I am using fastify instance as a closure in my route handler

**Comment by allevo** [comment]
Hi! 
Fastify internally uses the JavaScript prototype Request so the connection pool is not assigned to every Request instance.
I don't if the object creation time depends on how its prototype is heavy (I think not).

In some plugins (mongodb, redis etc...) the connection pool connected to the database is directly attached to fastify.
This is because the fastify instance lives "forever".

Are there some reason not to attach the pool to fastify? 

NB: fastify binds all handlers to the right fastify instance according with the encapsulation. The code above can be simplified use this feature avoiding the arrow functions

**Comment by bittukr20** [comment]
Thanks, I forgot callee of the handler function is "fastify", and inside the handler(if I am not using arrow functions) I can use decorators using "this.someDecorator". It's solved my problem.

**Comment by bittukr20** [comment]
Tomas also told not to use the decorateRequest as it will increase the burden on request object on every request.
https://github.com/fastify/fastify-mongodb/issues/9#issuecomment-335079761

**Comment by allevo** [comment]
Yeah. This is why I wrote
'I don't know if the object creation time depends on how its prototype is heavy (I think not).'

Fastify create a new Request instance for every incoming message. The Request object has a prototype decorated with all declared decorations (the pool for example).
Maybe if the Request prototype has many properties, the Request object creation takes time (and memory).

This is why all plugins decorate the fastify instance instead of the Request.

**Comment by bittukr20** [comment]
Great I agree, Got my answer. Thanks a lot
