### ISSUE TITLE
Replace .npmignore with files whitelist in package.json

### ISSUE THREAD

**Issue by SerayaEryn** [fastify/fastify#1866]
## 🚀 Feature Proposal

At the moment we are using the `.npmignore` as a blacklist of files that should not be included in the npm package.
I propose to replace the `.npmignore` file with the `files` field in the package.json:
https://docs.npmjs.com/files/package.json#files

## Motivation

Prevent new files being included in the package.json if they shouldn't be included. For example the `build/build-validation.js` is included into the npm package, because it is missing in the `.npmignore`. 
Furthermore it would easier to maintain, I think.

I can open a PR for this.

**Comment by mcollina** [comment]
Unfortunately files in package.json causes significant issues when adding new files to the project, resulting in a broken module. A missing entry in .npmignore just increase the zipped size and it does not cause any sort of runtime issues. It is essentially safer.

That file is shipped because we ship the full development experience, so that an “npm install” would be sufficient for developing the module.

**Comment by SerayaEryn** [comment]
Thanks for the explanation. :) I'll just close the issue then.
