### ISSUE TITLE
Wildcard path dont work

### ISSUE THREAD

**Issue by underfin** [fastify/fastify#1896]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🐛 Bug Report

Wildcard path dont work.

## To Reproduce

Visit `/css/1`,only console.log('handle') in handle, the middleware not work.
(It work when use single path `/css` middleware.)
 
Paste your code here:

```js
const fastify = require("fastify")();
fastify.use("/css/*", function() {
  console.log(1111);
});
// fastify.use("/css", function() {
//   console.log(2222);
// });

fastify.get("/css/*", function(req, reply) {
  console.log("handle");
  reply.send("aaa");
});

fastify.listen(3001, function(err, address) {
  if (err) {
    console.error(err);
    process.exit(1);
  }
  console.info(`server listening on ${address}`);
});
```

## Expected behavior

The  wildcard path middleware shuold fired when visit `/css/1`

Paste the results here:

```js

```

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by underfin** [comment]
nestjs#3149

**Comment by Eomm** [comment]
Good catch!
The docs are [wrong](https://github.com/fastify/fastify/blob/master/docs/Middleware.md#restrict-middleware-execution-to-a-certain-paths). We should fix it.

After digging a bit you must write your middleware like this to let it works:

```
fastify.use('/css/(.*)', function (req, res, next) {
  console.log(1111)
  next()
})
```

Under the hood, we use [path-to-regexp](https://www.npmjs.com/package/path-to-regexp#unnamed-parameters) for the `.use` method since it is a utility to migrate from express to fastify.

If you are writing your middleware, I would suggest you use [`preHandler` hook](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#preHandler) instead.

**Comment by Krystofee** [comment]
I'll take this issue.

**Comment by mcollina** [comment]
Thanks!

Il giorno mar 15 ott 2019 alle 20:15 Kryštof Řeháček <
notifications@github.com> ha scritto:

**Comment by zekth** [comment]
Can we close this one?

**Comment by mcollina** [comment]
yes!
