### ISSUE TITLE
Set route options dynamically inside the route

### ISSUE THREAD

**Issue by abenhamdine** [fastify/fastify#190]
***Issue originated from discussion in https://github.com/fastify/fastify/issues/178#issuecomment-328041354, created here to ease tracking.***

Options object allows notably  to specify a schema, which brings validation feature and speeds up serialisation of the response (I noticed 25% perf increase for a big json response whith schema specified).

In our application, the responses to the routes are generated dynamically, based on data model passed by the client (it's a custom api which is a mix of REST and graphQL like).

So it's not possible to know the schema before the route is called (the same route could use different schemas), and thus specifying the schema for the route.

A possible solution would be to generate the schema dynamically, once the route is hit, but then I don't see how to set the options inside the route.

Is there any method to define the schema ***inside*** the route ?

Something like ? :

```js
fastify.get('/',  function(req, res) {
     // build options dynamically
     const options = myFunctionWhichGenerateOptionsDynamically(req)
     // apply options on response
     res.setFastifyOptionsToAllowSchemaUse(options)
     res.send(dataBig);
 });
```

**Comment by allevo** [comment]
Hi,
  currently `fastify` doesn't support this feature because the schema is stored in `Store` object. See [here](https://github.com/fastify/fastify/blob/master/fastify.js#L303).

But... if you want to do this, you can right now!
Seeing [`send` method](https://github.com/fastify/fastify/blob/master/lib/reply.js#L29) of `Reply`, it could be possible to send a string directly.
So the serialization can be made out of the framework.

For example:
```js
const fastJsonStringify = require('fast-json-stringify')

const schemaCache = {}
fastify.get('/',  function(req, reply) {
  const responseSchemaType = getResponseSchemaType(req)
  if (!schemaCache[responseSchemaType]) {
    schemaCache[responseSchemaType] = fastJsonStringify(getSchemaFromType(responseSchemaType))
  }
  const responseBody = getResponseBody(req)
  const responseBodyString = schemaCache[responseSchemaType](responseBody)
  reply.send(responseBodyString)
});
```

@delvedor @mcollina I'm 👎  to store the response schema inside `Reply` object too. Thoughts ?

**Comment by mcollina** [comment]
If you need multiple schemas, you can just use https://github.com/fastify/fast-json-stringify and send it down as a string and setting the correct content-type header.
