### ISSUE TITLE
Allow defining error responses

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#1930]
## 🚀 Feature Proposal

As discussed in https://github.com/fastify/fastify/pull/1888#discussion_r332106310  we have several points in the framework where it is assumed a response will be `content-type: application/json`. However, people use Fastify for more than just that one content type. So it would be appropriate to allow them to define how these responses should be constructed and sent.

**Comment by mcollina** [comment]
I’m definitely +1 on this

**Comment by alemagio** [comment]
Hi, I would like to work on this.
I believe, following the comment mentioned in the description, that this is already happening on some parts of the framework, so I will take those as examples.

**Comment by mcollina** [comment]
Awesome @alemagio, we'll wait for your PR!

**Comment by alemagio** [comment]
After some investigation i found that the default content-type is used a lot of times.
Do you think it should be a config parameter?
For errors, for example, should the user be able to define a default content-type header?

**Comment by delvedor** [comment]
@alemagio yes, the user should be able to customize the response completely :)
The best-case scenario is that all these cases were we are returning a json will call the `defaultErroHandler`, so the user can decide what to do.
The problem (you can find many discussions about this) is that often we can't have access to the default error handler.

A good strategy could be to have an option, something like `frameworkErrors`, which by default returns the JSON we are building, otherwise, the user can override it and do what they prefer. Clearly, this method will not support encapsulation.
```js
const fastify = require('fastify')({
  frameworkErrors (error, req, reply) {
    // custom handling
  }
})
```

**Comment by alemagio** [comment]
I created a draft PR to show my idea.
Hope it is useful.

**Comment by RafaelGSS** [comment]
Hey there, this issue is already fixed?
