### ISSUE TITLE
Use `next` types in V2

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#1939]
I see a lot of PR's come through with small improvements to the current V2; however, these will eventually get replaced in V3 with #1569. Is there a way we can make the new types available to V2 users as an 'opt-in' feature until V3 is released? I had two ideas:
1. Ship both types (in V2 and allow the user to specify which one to use via some configuration. (more experimentation needed how to implement this nicely)
2. Make the new types temporarily available as an npm package and advise users to install it if they so please.

Appreciate your thoughts and input before I start working on this!

**Comment by mcollina** [comment]
@Ethan-Arrowood I would just focus on getting v3 out of the door as soon as possible instead of trying to ship them separately. I'd love to target January to drop Node 6 and 8, and this seems feasible - the biggest breaking change are the new types.

I'm not too worried on missing properties on the new types: those will get noticed and added by the community really quickly after we launch.
