### ISSUE TITLE
How to avoid duplicated decorators?

### ISSUE THREAD

**Issue by fralonra** [fastify/fastify#1955]
Decorators in different plugins may conflict if they happen to have the same property name in the same scope. For example, if both `plugin-a` and `plugin-b` decorates a property named `c`, only the the first decorator would success.

Is there a way to avoid this issue gracefully?

**Comment by mcollina** [comment]
You can’t. I think a better way is to create two plugins to wrap the two parts of your application that need the decorators.

**Comment by RafaelGSS** [comment]
> For example, if both plugin-a and plugin-b decorates a property named c, only the the first decorator would success.

Override in this case sounds good (if already don't do it)

**Comment by Eomm** [comment]
The key point is that we don't know if the user is aware or not that a plugin is attaching a decorator to the fastify instance, so the error during development "implement" the user knowledge I think.

Because if we override. plugin-a could be different from plugin-b and add bugs because we think to use the decorator of plugin-a but instead is plugin-b 🤯

**Comment by RafaelGSS** [comment]
Yep, display a warning message is nice too

**Comment by fralonra** [comment]
Can we recommend plugin developers to provide an additional option in their plugins if they are using decorators? This option will define the actual property name that attached to the application. So that users can change the property name if they conflict with other plugins.

**Comment by RafaelGSS** [comment]
Is a good approach too.

I think that adding to the Plugins section in docs a **note** for it, is needed too.
