### ISSUE TITLE
Schema and route declaration order conflict.

### ISSUE THREAD

**Issue by weiliddat** [fastify/fastify#1960]
## 🐛 Bug Report

Initially opened at https://github.com/fastify/fastify-cors/issues/47 because upgrading the cors plugin caused shared schemas to fail. I looped through the debugger many times and I think I found the issue.

This was because the `fastify-cors` plugin starting from version 2.2.0 added a default line that hide OPTIONS routes from swagger. [Relevant commit](https://github.com/fastify/fastify-cors/commit/a28da42af1f92b819241c975436bade27f5dc9b2).

If a shared schema was added after the cors plugin was registered, and used in a subsequent route declaration, the list of schemas attached to the default schema compiler (ajv in this case) is already set, and additional referenced schemas can't be found.

To see what I mean, set a breakpoint at line 229 in `fastify/lib/route.js` where `buildSchema` is called. If you inspect `this[kSchemaCompiler]`'s bound `this`'s `_refs` field, you'll see that in the cases where it works, there is a schema keyed `https://example.com/bson/objectId`; in cases where it doesn't, this property is missing.

## To Reproduce

Referring to the sample code below...

Running the script as is will throw a `FST_ERR_SCH_BUILD` error, saying it cannot find the `https://example.com/bson/objectId` ref.

Any of the options will make it work, and show the right properties in `_refs`.
1. Comment out the line below `1a`.
2. Comment out `2`, and uncomment `3`.
3. Move `1` below `2`.

```js
const fastify = require('fastify')({ logger: true });
const fp = require('fastify-plugin');

/**
 * 1. An example of a plugin declaring a route with one of the options
 * being a schema option.
 */
fastify.get(
    '/',
    /**
     * 1a. The option line below is one of the cause of the issue.
     */
    { schema: { random: 'options' } },
    (req, reply) => reply.send(),
);

/**
 * 2. Registration of shared schemas used throughout the server in a plugin.
 */
fastify.register(fp(async f => f.addSchema({
    $id: 'https://example.com/bson/objectId',
    type: 'string',
    pattern: '\\b[0-9A-Fa-f]{24}\\b',
})));

/**
 * 3. Registration of shared schemas used throughout the server inline.
 */
// fastify.addSchema({
//     $id: 'https://example.com/bson/objectId',
//     type: 'string',
//     pattern: '\\b[0-9A-Fa-f]{24}\\b',
// });

/**
 * 4. Another route declaration, this time using the shared schema in $ref-way form.
 */
fastify.get(
    '/:id',
    {
        schema: {
            params: {
                type: 'object',
                properties: {
                    id: { $ref: 'https://example.com/bson/objectId#' },
                },
            },
        },
    },
    (req, reply) => reply.send({ hello: req.params.id }),
);

/**
 * Start the server.
 */
fastify.listen('1337', '127.0.0.1');
```

## Expected behavior

Perhaps this is an expected behavior but it seems like a gotcha since there shouldn't be any conflict between declaring routes/schemas in any order, as long as the declared schema happens before the route that uses it and is in its inherited scope.

## Your Environment

- *node version*: 12
- *fastify version*: >=2.9.0
- *os*: Mac/Linux
- *any other relevant information*

**Comment by mcollina** [comment]
Thanks for reporting! This looks like a bug. It seems you have done a significant amount of research - would you be able to send a PR to fix this here?

**Comment by weiliddat** [comment]
I would like to but I need some help in finding out whether it's a problem of plugin encapsulation, order of route declaration, or schema compilation.

I can't seem to figure it out past that the schema compiler is not being able to get the shared schemas in this case.

**Comment by mcollina** [comment]
It's definitely a problem of the encapsulation of the schemas.

**Comment by Eomm** [comment]
I had time to check if this bug still lives in #2023 for v3, and it is there 😕

I understood the bug:

The `schema` parameter in the first route, trigger the build of the compiler:
https://github.com/fastify/fastify/blob/7fa4bddca07aac18e0600cff40d97b95a96ab970/lib/route.js#L233

at that stage the `externalSchemas` is empty so the `Ajv` instance is built without the schemas.
This happens because the functions' order is the following:

- fastify root instance
  - after load the route `/` (`afterRouteAdded`) -> build empty ajv
  - after register the plugin -> execute the `addSchema`.. but ajv is already created
  - after load the route `/.id` -> the ajv instance doesn't have the schema

As @webdevium pointed out the workarounds are:

- don't trigger the build of the compiler (commenting the schema in `1a`)
- run the `addSchema` in sync, without encapsulating it in the `register`

To solve it I see only a rewrite of the execution order of compiling the schemas:
- the routes should be loaded on `preReady`
- or move the compiling on `preReady`

but `preReady` is only an event and can't stop the server startup right now..

@mcollina do you have other ideas?

**Comment by mcollina** [comment]
We can safely move the schema compilation inside `preReady` - there is no harm to it.
