### ISSUE TITLE
Use Pino v6

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#1973]
In fastify v3 we will use Pino v6.

**Comment by MichielDeMey** [comment]
Is a v6 release planned for Pino? Can't seem to find any pre-releases or next branch for v6. 🤔

**Comment by jsumners** [comment]
@MichielDeMey yes. We just haven't created such things yet. We are still nailing down what constitutes a v6 and, more importantly, trying to find the time/energy to work on those things. Having said that, I do not see it as a big blocker to a Fastify v3.

**Comment by mcollina** [comment]
We need pino v6 to be out, mainly because it removes old node versions. Pino options are part of fastify own options, so we are a bit coupled.

I plan to release some alpha version of Fastify before we update pino. Note that I think there is one outstanding thing for pino v6, and I don’t think it’d be a blocker.

**Comment by Eomm** [comment]
Could we close this or there are some new features we could benefit to add in the fastify's option object?

**Comment by mcollina** [comment]
It’s done!
