### ISSUE TITLE
Avoid calling buildSchemaCompiler for every route

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#2006]
https://github.com/fastify/fastify/blob/e22492757660152e270f2092d80d0d17d7756ee6/lib/route.js#L221-L242

Related: https://github.com/fastify/fastify/issues/1598

**Comment by Darking360** [comment]
Greetings. I'm new to the code but I've been reading a little bit of how it works right now, I see that it uses `ajv` on the `buildSchemaCompiler ` that comes from `./validation`. But it pulls the `externalSchemas` with this line:

```
const externalSchemas = this[kSchemas].getJsonSchemas({ onlyAbsoluteUri: true })
```

So I assume that's not changing, so maybe the call for `buildSchemaCompiler` could be moved to a const before and only be called if it doesn't exist? So the subsequent calls find that variable already created and don't call `buildSchemaCompiler` again 🤔 

Not sure if that's correctly called "constant", if not, `let` and change it when the route's schema changes? Sorry if I don't have the complete picture of the thing yet 😅

**Comment by Eomm** [comment]
I took a look some days ago.

This function is not executed for every route, because `this.setSchemaCompiler` is called and will set `this[kSchemaCompiler]`, that avoid the call to `buildSchemaCompiler`. 
It is executed for the first context that is being created.

The use case is this:
we need to provide the schemas (added via `addSchema`) to a compiler, but we don't have it.
We can't create it by default (because there is a test that checks that it must be null)

Right now I'm not sure how this could be improved in v2

**Comment by Eomm** [comment]
I think this could be closed since it has been optimized in v3:

https://github.com/fastify/fastify/blob/db39fa74c0d9d5ead9371e414f533f33c2bfd5b5/lib/schema-compilers.js#L16
