### ISSUE TITLE
Route onReponse hook to contain the payload

### ISSUE THREAD

**Issue by flaviotulino** [fastify/fastify#2019]
## 👉 [Please follow one of these issue templates](https://github.com/fastify/fastify/issues/new/choose) 👈

Hello all, as per [2.9.0](https://github.com/fastify/fastify/releases/tag/v2.9.0), the route declaration now supports the `onResponse` hook. 
According to the documentation [here](https://github.com/fastify/fastify/blob/master/docs/Routes.md) the signature is (request, reply, payload, done) like the `onSend`, but it appears to be (request, reply, done).

Can anyone help?

**Comment by delvedor** [comment]
Hello! You are right, the documentation is wrong:
https://github.com/fastify/fastify/blob/f2078721ba586df2647fe2936bad66f879815352/lib/reply.js#L495-L501

Would you like to send a pr? :)

**Comment by flaviotulino** [comment]
Honestly, I think the payload in the `onResponse` is a nice to have. 
It would be useful to run something without the overhead the `onSend` causes. 

Let's imagine I wanted to cache the payload without passing through the serialisation process that happens in the onSend.

Would this be a feature request?

**Comment by RafaelGSS** [comment]
> Let's imagine I wanted to cache the payload without passing through the serialisation process that happens in the onSend.

Maybe can be good in this case. But, I don't know if is overhead, because the response serialized should send without the hook.

**Comment by delvedor** [comment]
Currently, we can't add the payload in the `onResponse`, because that hook is being fired in a completely different context and we don't have access to the payload.
Anyhow, running the `onSend` hook doesn't cause any more overhead that the `onResponse` hook causes. If by "overhead" you mean "response time", then you can use a fire and forget function :)

Final note: by your message I fear there is some misundersataing.
The serialization happens in any case, the difference is that in the `preSerialization` hook you can access the payload before it's serialized, while in the `onSend` has the already serialized payload.
See our docs section about the hooks: [fastify.io/Hooks](https://www.fastify.io/docs/latest/Hooks/).

Closing as the issue has been resolved in #2020.

**Comment by radiorz** [comment]
Thanks bro. What is the fire and forget function? What should I do?
If you could give an example I will apreciate it.

**Comment by jlenon7** [comment]
Hey @delvedor!

But in `onSend` hook, the "response time" is equals to zero because the response has not been sent yet. The response body and the response time are two important data that I need to generate good metrics. Do you have any tip of how I could get these two data in one hook?

**Comment by jlenon7** [comment]
> Currently, we can't add the payload in the `onResponse`, because that hook is being fired in a completely different context and we don't have access to the payload.

In `onResponse` hook, I've the response time but not the response payload. 

And about the architecture, I'm using [FluentD](https://www.fluentd.org/) to collect the logs from the `stdout` of the application and distribute to many other places like some Loki database. Currently, I'm using the `onResponse` hook (where I've the response time) to send the log to `stdout`, but I also need the response payload.

**Comment by metcoder95** [comment]
>I did a workaround by creating an onSend hook that sets the body variable in the reply:

Yeah, I was about to suggest you that though I wouldn't recommend it. But it does the work.

>That way I can capture it in the onResponse hook. However, every time that a new onSend hook is created, I will need to update this variable, since some change might have been done in the payload.

On the other hand, you can create a more specific property that is attached to the `reply` object and is used only for the given purpose.
Otherwise, also have in mind that by not decorating the `reply` you're missing some optimizations done by fastify while instantiating the `reply` object.
