### ISSUE TITLE
Schema precompiler toolchain

### ISSUE THREAD

**Issue by davidmarkclements** [fastify/fastify#2049]
## 🚀 Feature Proposal

Normally schemas are compiled at runtime, create an optional compile step for schemas to be optimized prior to server start.

## Motivation

Primarily as a way to reduce serverless init time, but could also be used for non-serverless reasons. 

### CLI

* `fastify-schema-precompiler -d build app.js`
* deploy build

### Webpack plugin

```
const SchemaPrecompiler = require('fastify-schema-precompiler/plugin');

module.exports = {
  plugins: [
    new SchemaPrecompiler([{ from: '.', to: 'build' }])
  ],
};
```

**Comment by Eomm** [comment]
Hi,
I'm thinking right now how it could be by users:

https://github.com/fastify/fastify/blob/a3010963df77a4d717601d69b03bd67b754cf554/lib/schema-compilers.js#L26-L30

The idea is to let devs write plugins around this new signature.

In my mind I have this process:
- the server starts in production for the first time and a ValidatorCompiler plugin will store the generated functions to somewhere
- the server starts another time and the plugin will use the stored functions instead of generating them

Or:

- the server start in a dev env and a ValidatorCompiler will store the generated function to a file
- the user commit the file
- the ValidatorCompiler plugin will read the file commited instead of generating those functions

Do you think it could fit your needs?

**Comment by jsumners** [comment]
How would this work if Fastify is not handling the schema container?

**Comment by wtgtybhertgeghgtwtg** [comment]
If `fastify` was altered to take a schema or a compiled schema, you could probably just use `preval.macro` or something.
```js
// `mySchema` is uncompiled.
fastify.post('/my/route', {schema: mySchema}, handler);
```
```js
import preval from `preval.macro`;

// `mySchema` is precompiled.
fastify.post('/my/route', {schema: preval`myFunctionToCompileTheSchema(mySchema)`}, handler);
```
It might be preferable to just make a wrapper macro to avoid strings and maybe caching issues.
```js
import myFunctionToPrecompileTheSchema from 'my-macro-to-do-that';

fastify.post('/my/route', {schema: myFunctionToPrecompileTheSchema(mySchema)}, handler);
```
