### ISSUE TITLE
Provide an OpenTelemetry module

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#2097]
## 🚀 Feature Proposal

The [OpenTracing](https://opentracing.io/) and [OpenCensus](https://opencensus.io/) projects have merged into [OpenTelemetry](https://opentelemetry.io/). I think it would be a good idea for us to provide a module for tracing Fastify based applications. See https://github.com/open-telemetry/opentelemetry-js/tree/master/packages/opentelemetry-node for information on the plugin framework.

## Motivation

Tracing is vital for understanding a system at run time. Currently, we rely on third parties to decide we are worthy of taking the time to support us. The only two I know of right now are [Elastic APM](https://github.com/elastic/apm-agent-nodejs/blob/c56f894138c81f0b07146f86c3ba7139bb68a59c/lib/instrumentation/modules/fastify.js) and [DataDog Tracing](https://github.com/DataDog/dd-trace-js/tree/5348eaad6f1a86d57b87ffd3de6397feb1dcb417/packages/datadog-plugin-fastify/src). By providing our own module to this open standard, we make it easier for Fastify to be used in organizations that require tracing.

**Comment by mcollina** [comment]
This would be important to add!

**Comment by jsumners** [comment]
Maybe this is taken care of by https://www.datadoghq.com/blog/opentelemetry-instrumentation/ ?

It seems implied in https://github.com/DataDog/dd-trace-js/issues/820 

Maybe @irabinovitch can provide some clarification?

**Comment by irabinovitch** [comment]
@jsumners We have donated to libraries we use for auto-instrumentation to the OpenTelemetry project.   So far Python and JAVA have been merged, and work on exporters for those languages and .net has begun.  I do not believe nodejs has begun reviewing the donation yet.

**Comment by jsumners** [comment]
But does that mean your Fastify module is up for inclusion?

**Comment by mcollina** [comment]
@irabinovitch what's the status of this?
There is a plugin that has started to implement this, should we move forward with it ourselves or are you planning to contribute/develop one from the opentelemetry org?

**Comment by Eomm** [comment]
I started looking at this and for what I understand:

- the nodejs API for tracing: [@opentelemetry/node](https://github.com/open-telemetry/opentelemetry-js/tree/master/packages/opentelemetry-node) is now in beta stage
- the org opentelemetry is providing support to trace nodejs core modules ([http/https/grpc](https://github.com/open-telemetry/opentelemetry-js#core))

>  work on exporters for those languages and .net has begun. I do not believe nodejs has begun reviewing the donation yet.

I'm not sure to completely understand, but looking [the site](https://opentelemetry.io/registry/?s=node) there are some exporter (azure, prometheus, zipkin, GCM etc..) already published, so I think this review has begun.

> But does that mean your Fastify module is up for inclusion?

Good question, looking the contribution for the [`express`](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/master/plugins/node/opentelemetry-plugin-express) module is made by the opentelemetry team (I don't have the express knowledge to understand if all the express feature are traced by the [`@opentelemetry/plugin-express`](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/master/plugins/node/opentelemetry-plugin-express#opentelemetry-express-instrumentation-for-nodejs) plugin)

--- 

Tracing HTTP with fastify it is already possible (**quick demo at the bottom), it would be interesting to add this feature out of the box with fastify since all works based on monkey patching (and we cannot load a plugin before the fastify server itself) 

<details>
  <summary>Example click to expand</summary>
  
```js
'use strict'

// must load first
const opentelemetry = require('@opentelemetry/api')
const { NodeTracerProvider } = require('@opentelemetry/node')
const { SimpleSpanProcessor } = require('@opentelemetry/tracing')
const { JaegerExporter } = require('@opentelemetry/exporter-jaeger')

const provider = new NodeTracerProvider()

const exporter = new JaegerExporter({ serviceName: 'fastify' })
provider.addSpanProcessor(new SimpleSpanProcessor(exporter))

// ready to monkeypatch
provider.register()

const tracer = opentelemetry.trace.getTracer('http-example')

// enable http tracing
const http = require('http')

const serverFactory = (handler, opts) => {
  const server = http.createServer((req, res) => {
    const currentSpan = tracer.getCurrentSpan()
    console.log(`#### --> traceid: http://localhost:16686/trace/${currentSpan.context().traceId}`)
    const span = tracer.startSpan('handleRequest', {
      parent: currentSpan,
      kind: 1, // server
      attributes: { key: 'value' }
    })
    // Annotate our span to capture metadata about the operation
    span.addEvent('invoking handleRequest')
    req.on('error', () => { span.end() })
    res.on('end', () => { span.end() })
    handler(req, res)
  })

  return server
}

const fastify = require('fastify')({
  serverFactory,
  logger: true
})

fastify.get('/helloworld', (request, reply) => {
  setTimeout(() => { reply.send('slow reply') }, 1000)
})

fastify.listen(8080)
```
</details>

**Comment by mcollina** [comment]
@Eomm looking at your example, I would do something differently. I would hook into Fastify hooks and provide a bit more guidance on the various steps.
