### ISSUE TITLE
Disable logger on specific route

### ISSUE THREAD

**Issue by BinaryShrub** [fastify/fastify#2120]
## 💬 Questions and Help

I want to disable logging on my health route `POST /health` so it doesn't pollute my logs; is there a way to do this?

**Comment by mcollina** [comment]
https://github.com/fastify/help/issues/140

This is probably our most _asked_ question. I'd just like to understand more why you was not able to find this info (Which is in the docs and on multiple issues). Where would you expect to find it?

**Comment by mkinoshi** [comment]
@mcollina @Eomm I initially couldn't find the solution for this either mainly because I was trying to find the solution in the logging section. Once you say it is under the route section, it seems very obvious since it is related to how you configure routes. However, it might be helpful to mention a little bit in the logging section and create a link to the description in the route section.

**Comment by jsumners** [comment]
Improvements to docs PRs are always welcome.

**Comment by mkinoshi** [comment]
Sounds good, yeah I can work on it!

**Comment by bkyerv** [comment]
in the documents it says that the logger can be turned off when instance of fastify object is initiated like so 'const fastify = require('fastify').({logger:false}). However there are cases when the whole project structure is auto generated using cli or 'npm init fastify' command, how do we turn off the logger in this case? in general where can we find the root file where 'fastify' object is initiated so we can change certain configuration such as logger for example in future?

**Comment by climba03003** [comment]
> 
> 
> in the documents it says that the logger can be turned off when instance of fastify object is initiated like so 'const fastify = require('fastify').({logger:false}). However there are cases when the whole project structure is auto generated using cli or 'npm init fastify' command, how do we turn off the logger in this case? in general where can we find the root file where 'fastify' object is initiated so we can change certain configuration such as logger for example in future?

Please check the document of `fastify-cli` and if you have any issue, open in there.
You can start with `fastify start -l silent xxx.js` change the log level to `silent`.

**Comment by grreeenn** [comment]
as Google leads here as a first link to `fastify logger exclude`, I'll leave the solution here, jus so you'd save your time.

First of all, the docs section @mcollina talked about can be found [here](https://www.fastify.io/docs/latest/Reference/Routes/#custom-log-level). This section doesn't specify how to disable logs though; in order to make it work, you need to explore a bit of Pino (the default logger) [documentation about log levels](https://github.com/pinojs/pino/blob/master/docs/api.md#logger-level).

Combining the above together, disabling log for the certain route is done from this route registration as follows:

```
fastify.register(require('./routes/your-route'), { logLevel: 'silent' }) 
```

or from the route declaration as follows:
```
fastify.get('/your-route', { logLevel: 'silent' }, (request, reply) => {
  reply.send({ hello: 'world' })
})
```

**Comment by BibbyChung** [comment]
Another way is to set it to be disabled by default.

`
fastify.addHook('onRoute', (routeOptions) => {
  routeOptions.logLevel = 'silent'
})
`
