### ISSUE TITLE
"http-method-override" header

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#214]
Because of https://github.com/fastify/fastify/pull/170, no hooks are fired before routing.

Unfortunately an API that allows the `http-method-ovveride` header to override the http method should replace the `method` request property with the header value. See [method-override](https://github.com/expressjs/method-override) for an example

How we can handle this?
Maybe a `prepareRequest` method can be useful :fearful:
@mcollina @delvedor  thoughts?

**Comment by mcollina** [comment]
first of all, is that needed in 2017?

is there another case where we need to run something before routing? or we just need to support this as a core feature?

**Comment by allevo** [comment]
> first of all, is that needed in 2017?

LOL 👍 

Image that we have to create a CRUD on DB in REST API. The `GET` method is used to retrieve the data. We can use the querystring or filtering the data but in some case, the query reaches the max limit allowed from webserver and the backend receives a truncated querystring or a 414 error code.
Maybe you would use the body for defining your query. But... some clients don't allow this feature (like xhr from browser). So a possible workaround is to perform a `POST` with this header.

NB: however seeing [around](https://stackoverflow.com/a/983458/1956082) passing the body into a `GET`request is allowed but useless so the workaround is not so good for an architecture choose.

> is there another case where we need to run something before routing? or we just need to support this as a core feature?

I don't think there's another feature that requires to be run before routing. Maybe create a `hook` or a function is a premature study.
For the time being I'll implement this feature inside `fastify` as is. Tomorrow we'll see what happens

**Comment by mcollina** [comment]
@allevo it should be disabled by default, it might be a security risk.

Something like `'allowMethodOverride'` at route-level.

**Comment by delvedor** [comment]
Closing this, if you want to continue the discussion feel free to reopen :)

**Comment by jakewhelan** [comment]
I'd like to revive this discussion because I'm having the exact problem proposed in the OP.

Due to some corporate politics I only have the `GET` and `POST` methods available to me, but on the server I want to build the API using others such as `PATCH` and `DELETE`. 

The `X-HTTP-Override-Method` header is actually _suggested_ at my company and considered the solution as far as they're concerned: that's it, end of story. I'm not all that interested in trying to steer such a big ship in another direction, either.

What are the options within Fastify to support this method override behaviour now that there are no pre-routing hooks?

I'm pretty disappointed to discover this problem because without this feature my options are now:
- Refactor entire service to use another framework
- Refactor all non-POST endpoints to be POST
- Configure some type of reverse-proxy to do the override.

All these options suck.

**Comment by mcollina** [comment]
Would you like to send a PR/work on an implementation?

**Comment by jakewhelan** [comment]
I'd love to if you can point me in the right direction.

My efforts so far to monkey patch this haven't been fruitful.

**Comment by mcollina** [comment]
I think this should be supported in a way similar to how we support route versioning (via headers). A PR to find-my-way to add support might be the right spot.

**Comment by jakewhelan** [comment]
Here's a solution using `fastify-reply-from`

```js
import fastify from 'fastify'
import fastifyReplyFrom from 'fastify-reply-from'

const proxy = fastify({
  logger: true,
  pluginTimeout: 10000
})

proxy.register(fastifyReplyFrom, {
  base: 'http://localhost:3101'
})

proxy.get('/*', (request, reply) => {
  const { url } = request.raw
  reply.from(url)
})

proxy.post('/*', (request, reply) => {
  const { 'x-http-method-override': method = 'POST' } = headers
  reply.request.raw.method = method
  reply.from(url)
})

proxy.listen(3100, err => {
  if (err) {
    app.log.error(err)
    process.exit(1)
  }
})
```

**Comment by delvedor** [comment]
Closing this, if you want to continue the discussion feel free to reopen :)

**Comment by mokevnin** [comment]
here you go: https://github.com/corsicanec82/fastify-method-override
