### ISSUE TITLE
[general ux is so-so] example: setting up a proxy

### ISSUE THREAD

**Issue by desmap** [fastify/fastify#2272]
This is neither a real bug nor a question but some issues I had with using fastify. Coming from Koa, I wanted to give fastify a try because of its fast fastify-gql. 

I also needed a proxy middleware which can do http2 and websockets out of the box which is with koa or express just an one-liner. The respective fastify module ('fastify-http-proxy') does not have websockets. Then, there are more modules where - if you just check them out briefly - it's not really clear how they differentiate. They are fast-proxy, fast-gateway, fast-reply-from. Then there is the option to embed legacy express modules via middie which I also tried. I still couldn't find an intuitive way to setup a proxy

If you are time-constrained it's quite tedious to get the stuff up and running. Guess I missed something and should have read the docs more but in contrast, setting up a full-featured proxy shouldn't be any rocket science, be documented or just be intuitive. The only thing I found was, 'a PR is welcome' re websockets support in the issues of fastify-http-proxy.

Edit: Other stuff is then again very elegant and buttersmooth like setting up the graphql server.

**Comment by mcollina** [comment]
Thanks for coming and complaining about a “so-so” UX. I would invite you to reflect that you are complaining for something that you are not paying and it is provided for free to you. Anyway, would you like to help in improving it?

As far as I know there is currently no way to proxy a websocket, and the comment “please send a PR” still stand.

**Comment by desmap** [comment]
Blaming me who is just *testing* if a lib with barely any downloads and who is thinking putting fastify into production that I am not paying and want stuff for free is... yeah, a great way to start a convo.

In contrast, putting out a proxy (fastify-http-proxy) without websockets support (I mean every dev server needs websocket) *and* pretending fastify has such a rich ecosystem is a bit odd. Then, if people note that a crucial part is missing, you play the it's-free OSS,-you-don't-pay game. I think that's not how OSS works and maybe a reason for being the liv with the least traffic. Before anyone invests their time for PRs, they must be convinced that a lib, its ecosystem, their culture are worth to be joined. That's the reason you just cannot welcome people who give feedback with 'a PR is welcome'. That's being passive-aggressive. I am sure that being maintainer is also not easy but that's the signal you send.

**Comment by desmap** [comment]
to get back to the discussion...

> there is currently no way to proxy a websocket

do you mean in fastify-land or in general? 

if latter, express' http-proxy-middleware supports ws. So, shouldn't it not be possible to employ that lib paired with fastify's express compatibility libs (middie and that other one, I forgot the name)?

**Comment by mcollina** [comment]
There are a lot of different ways to give good feedback and ask for a feature, and this was definitely not one. 

> If you are time-constrained it's quite tedious to get the stuff up and running. Guess I missed something and should have read the docs more but in contrast, setting up a full-featured proxy shouldn't be any rocket science, be documented or just be intuitive. The only thing I found was, 'a PR is welcome' re websockets support in the issues of fastify-http-proxy.

This is dismissive of all the work that is needed to build and maintain a production-grade proxy. Again, I urge you to reflect on this sentence and how you could have framed this better. I know how much time I spent on getting it done and I know how much time http-proxy took to be developed by its authors.

This community is about building a web framework together and share its maintainance and evolution costs. Asking "please send a PR" is a matter of fact: no one will do the work for you. It's also a community of learners and we tend to experiment on things.

---

Let's dig in fastify-http-proxy: I wrote that module because I needed a way to rewrite HTTP requests on the fly in production. I did not need websocket support then and I do not need it now. Only a few people asked for it in that repo, so I do not think it was ever a must have feature. Note that neither express, Koa or any other ships with it either - nor it's maintained by their respective core team.

The way I have used Fastify with React or Vue is by having their respective dev servers (e.g. what comes out of create-react-app or analog) forward everything to Fastify and not viceversa.

Anyway, it would be cool to add websocket to fastify-http-proxy.
