### ISSUE TITLE
typescript definition for ready() is wrong

### ISSUE THREAD

**Issue by m-ronchi** [fastify/fastify#2343]
## 🐛 Bug Report

fastify.ready() resolves with no value, but d.ts declares to return Promise<FastifyInstance>

## To Reproduce

```ts
let server: FastifyInstance;
server = await fastify().ready();
```
this code compiles, but `server` is undefined

## Expected behavior

Either:
1. TS fails to compile (fix the signature to be Promise<void>)
1. or `ready()` resolves with the correct instance (fix the implementation)

## Your Environment

- *node version*: 12
- *fastify version*: >=2.15
- *os*: Mac

**Comment by Ethan-Arrowood** [comment]
Would you like to send a PR fixing the types? Thank you for pointing this out!

**Comment by temsa** [comment]
@Ethan-Arrowood @m-ronchi @mcollina up to 2.14.0 the `ready()` type was correct as the server instance was returned.

Since `2.15.0` and the different implementation for `onReady` , the server is not reaturn when the promise resolves, and a such it feels more like a *breaking change*. The best behavior would be ( if not releasing a `3.0.0` for this ) to release a `2.15.1` returning the server instance when successfully running `await fastify().ready();` , not to fix the TS type

**Comment by mcollina** [comment]
@Eomm can you please help here? You did the backport.

**Comment by simoneb** [comment]
@mcollina @Eomm I would suggest reverting to the previous behavior returning a Promise from the `ready()` method. This change is a breaking one otherwise.

**Comment by Eomm** [comment]
It seems an unwanted feature since the doc doesn't mention it in the [async/await](https://www.fastify.io/docs/v2.14.x/Server/#ready) statement and I remember that for the #2345 I looked for tests for this but there was not (for this I thought it was a typing issue)

It would be helpful if someone could start a PR with tests and I will check later.

As a workaround it should be enough to write:

```
const app = fastify()
await app.ready();
server = app.server
```

**Comment by simoneb** [comment]
> As a workaround it should be enough to write:
> 
> ```
> const app = fastify()
> await app.ready();
> server = app.server
> ```

Yes, this worked for us.

**Comment by Eomm** [comment]
What is the use case to get the server with the `ready` method?
Because the `ready` is resolved [before the HTTP server is started](https://github.com/fastify/avvio/tree/v6.x#ready).

The old `ready` exposed in 2.14, was the `avvio` function. it returns the fastify instance that just started since the [interface with a callback with 3 param is](https://github.com/fastify/avvio/tree/v6.x#appreadyfuncerror-context-done):

```
app.ready(function (err, context, done) {
  if (err) throw err
  assert.equal(context, server) // <------ this would be the `app` in the example before
  done()
})
```

In avvio 6.x there is this test: https://github.com/fastify/avvio/blob/v6.x/test/async-await.js#L223
that would mean that my workaround should be wrong 😅 

```
const app = fastify()
await app.ready();
server = app // this is like the test linked above
```

To confirm this, the following test passes in 2.14, and fail in 2.15:

```
t.test('ready return the server with Promise', t => {
  t.plan(1)
  const fastify = Fastify()

  fastify.ready()
    .then(server => { t.deepEquals(server, fastify) })
    .catch(err => { t.fail(err) })
})
```

So could you explain better your use cases?

**Comment by Eomm** [comment]
Clear, but it seems strange that this works since

```
await app.ready();
server = app.server

// it is not like:

server = await app.ready();
```

could you recheck since if I would apply the change to return the fastify instance as it was before

**Comment by simoneb** [comment]
I'm not sure what you're asking but this is the change we had to do to make our code work with 2.15:

![image](https://user-images.githubusercontent.com/20181/86127401-15d5df80-bae0-11ea-9476-743155c4fc4b.png)

From this, I assume that `ready()` was returning a promise that resolved to `fastify`

**Comment by Eomm** [comment]
Fixed
