### ISSUE TITLE
Calling fastify.getSchema in v2.15.1 throws error fastify.getSchema is not a function

### ISSUE THREAD

**Issue by eadmundo** [fastify/fastify#2377]
## 🐛 Bug Report

Calling [`fastify.getSchema`](https://www.fastify.io/docs/v2.15.x/Server/#getschema) in v2.15.1 throws error `fastify.getSchema is not a function`

It looks like installing `2.15.1` via `npm install fastify` installs `lib/schemas.js` from the [`2.x` branch](https://github.com/fastify/fastify/blob/2.x/lib/schemas.js), which does not contain the method `getSchema`, whereas the version of `lib/schemas` at the [`v2.15.1` tag](https://github.com/fastify/fastify/blob/v2.15.1/lib/schemas.js#L40) does contain it. The version number at the `v2.15.1` tag is [`3.0.0-rc.4`](https://github.com/fastify/fastify/blob/v2.15.1/package.json#L3)

## To Reproduce

https://github.com/eadmundo/replicate-missing-get-schema

```js
const fastify = require('fastify')({
  logger: true
})

fastify.addSchema({
  $id: 'new-schema'
})

const start = async () => {
  try {
    await fastify.ready()
    fastify.getSchema('new-schema')
    await fastify.listen(3000)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
```

## Expected behavior

Expected server to run without error.

## Your Environment

- *node version*: 12.16.0
- *fastify version*: 12.15.1
- *os*: Mac

**Comment by Eomm** [comment]
The site shows the wrong doc, check out the `/docs` in github;
This issue is related to https://github.com/fastify/website/issues/174 , so the site is wrong cause the tag! Nice spot!

The v2.15.1 tag is wrong, the [v2.15.0](https://github.com/fastify/fastify/commits/v2.15.0) it is ok. @mcollina could you check it?

To get your schemas, you need to use [getSchemas](https://github.com/fastify/fastify/blob/2.x/docs/Validation-and-Serialization.md#retrieving-a-copy-of-shared-schemas) in v2

**Comment by mcollina** [comment]
I fixed the tag, my bad!
