### ISSUE TITLE
Redirecting Errors on the Docs page

### ISSUE THREAD

**Issue by iandrc** [fastify/fastify#2421]
## 🐛 Bug Report

Some redirections on the [Fastify docs page](https://www.fastify.io/docs/latest/) are broken (actually, the majority of them if not all). 

We can observer an error only for the following versions:
* `v3.0.x`
* `master`
* `latest`

I guess those errors were introduced by [PR #2283](https://github.com/fastify/fastify/pull/2283), and, respectively, the root cause of the problem is the [issue #2265](https://github.com/fastify/fastify/issues/2265). 

In order to fix the docs, we should roll back to the previous approach, that specifies absolute paths. 

## To Reproduce

Refs: [#177](https://github.com/fastify/website/issues/177), [#178](https://github.com/fastify/website/issues/178), [#179](https://github.com/fastify/website/issues/179)

## Expected behavior

A user should be redirected to the correct page instead of `404 Page`

## Your Environment
- *os*: Mac, Windows, Linux

**Comment by iandrc** [comment]
@Eomm @mcollina what do you think about this? Should we change it back?

**Comment by mcollina** [comment]
I think so yes! Would you like to send a big PR?

**Comment by Eomm** [comment]
I don't think all the links will be fixed because we had mixed relative links and absolute ones.
The issue with absolute is that if you navigate a version 2.x.x, you will be redirected to `master` in the github doc

I think we should fix this step in the remapping (since is not doing what is intended for):
https://github.com/fastify/website/blob/b75acffb399c7fcdfa734a082e365c2c21889aad/src/scripts/processReleases.js#L152

in the mapping:

https://github.com/fastify/website/blob/b75acffb399c7fcdfa734a082e365c2c21889aad/src/scripts/processReleases.js#L146
