### ISSUE TITLE
Make types a little less wordy by removing the Fastify prefix

### ISSUE THREAD

**Issue by naseemkullah** [fastify/fastify#2447]
e.g. FastifyReply could just be Reply and so on

**Comment by naseemkullah** [comment]
@Ethan-Arrowood  thoughts? Could we maybe have alias exports at least? (Instance, Request, Reply, etc. without the Fastify prefix)

**Comment by delvedor** [comment]
I think the idea about having verbose names is to be sure to not cause conflicts with other type definitions.
In another project I'm working on I got the exact same issue, but in the other way around "make the names more verbose".

TL;DR naming is hard and the TypeScript community is never happy 😜

**Comment by naseemkullah** [comment]
If using Fastify you are unlikely using another web framework in the same project/file and so there should not be a conflict with `Request` for example generally. 😄

What's the other project btw? It might be valid in that case but I would need more context.

**Comment by Ethan-Arrowood** [comment]
From my experience, typescript libs with simple names require me to often us `import whatever as SomethingWhatever` because `whatever` conflicts with some other import or something I defined. When authoring these types I found it very valuable to just name everything `FastifyWhatever`. 

@delvedor got it right though. Naming things is hard and no solution is ever perfect.

I'm not against adding named alternatives to our types but it might be more effort than its worth. Most TypeScript devs are using an editor/ide with codesense/intellisense so you're probably not typing them out yourself anyways.

**Comment by delvedor** [comment]
@naseemkullah the module is the ELasticsearch client, see https://github.com/elastic/elasticsearch-js/issues/1105.

Given that you can import types as aliases with TypeScript, I would recommend doing so :)

**Comment by naseemkullah** [comment]
> @naseemkullah the module is the Elasticsearch client, see [elastic/elasticsearch-js#1105](https://github.com/elastic/elasticsearch-js/issues/1105).
> 

I see....

> Given that you can import types as aliases with TypeScript, I would recommend doing so :)

Fair enough! Thanks everybody.
