### ISSUE TITLE
Expose function signature/types on custom modules when registering via plugin.

### ISSUE THREAD

**Issue by bluebrown** [fastify/fastify#2495]
When using fastify without any build steps for a better module resolution. So, using node require. The plugin system masks the function signature of the custom modules.

This image shows that vscode knows the function signature of custom modules.   
![image](https://user-images.githubusercontent.com/39703898/90309350-d9b7dc00-dedf-11ea-8e60-6ae716748aef.png)

But after registering it as plugin  
![image](https://user-images.githubusercontent.com/39703898/90309472-d3762f80-dee0-11ea-8e74-d69d08879bdd.png)

I think this behavior is expected as in the plugin definition, fastify is just passed as first argument to the callback, so there is no way of knowing what this actually is. 

After all I don't think this can be fixed or is worth the effort. It just a little inconvenient. I guess if one really wants to, they could use something like typescript + webpack. But it feels not good having to introduce a build step for a node app, where there is normally not build step required.

**Comment by fox1t** [comment]
This particular issue is not fixable. Decorate function adds a runtime property to an already created object (fastify instance). The only way we have to let TS knows about it is to use [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation). In this case, you've written the function and decorated the instance, but since you are using JS the module augmentation is of course missing.

Usually, we do this at plugin level. You can find a reference here: https://github.com/fastify/fastify-swagger/blob/master/index.d.ts#L5

Fun fact: the same problem is present even if you use TS and don't provide the module augmentation. `.decorate` is just too JavaScripty for the poor TypeScript :)

**Comment by fox1t** [comment]
Fun fact n.2: if you use the decorated function in the same file where it is declared and the same name, VS Code tries to be smart and fakes the types:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/1620916/90330399-b7d85b00-dfac-11ea-9e3a-b420d3f4c760.png">

XD

**Comment by weiliddat** [comment]
Yeah you could use module augmentation, which is the most straightforward, but could be problematic if you only declare/use a decorated function in one route and not in another (because it would appear as valid on every FastifyInstance).

Ideally, we would be able to:
1. Decorate and concretize some kinda generic type union of FastifyInstance and some GenericDecoratedInstance, perhaps using guards or indexed types on the prop names (trying but seems pretty complex to me)
2. Export a DecoratedFastifyInstance that extends the base FastifyInstance, then you could union/intersect these in your routes. Problem is that calling `decorate` doesn't signal to TS that the property is added to FastifyInstance (not really possible right now, maybe with (1) it will be).

![image](https://user-images.githubusercontent.com/899658/90335923-91c8b000-dfd8-11ea-8879-3b05ccb993c4.png)

**Comment by fox1t** [comment]
@weiliddat This issue is about JS source code and VS Code auto-completion on JS files. It is not fixable for the user since there is not a real TS interface (since the code is written in JS).

Returning to your suggestion, I could agree that would be nice to achieve that, but this is a TS limitation: it is not possible to extend a namespace/instance of an already created object only in some part of your application. 

We can use this as an example: let's say you are using an external plugin that has its own types and decorates the fastify instance using `decorate` method. 
How can we limit the decoration just for a specific instance of fastify without changing the behavior of `decorate` method (it decorate the original object and doesn't return a new instance with an additional prop)? Even if we decide that the `decorate`  will return a new instance, how it will be even possible for a user to use it in his own code since the instance that is created is encapsulated inside the plugin code?

**Comment by weiliddat** [comment]
You're right my bad. I overlooked that this particular case is in JS and so there is no TS declaration that you can add to this (well you can use JS docs each time you use FastifyInstance but it's probably too verbose and brittle to update all the time).

About the more general case of automatic type signatures for decoration, this is exactly the issue I face when using fastify for work projects (I've used it in ~ 10 or so services since v1, but only 2 of them use TS). I thought this would be a good point to document/discuss what should be recommended to people who want to use TS for compile-time checks on decorated instances/req/reply.

So far the solutions are to
1. Use augmentation, like mentioned earlier. This is the most straight forward.
```TypeScript
declare module 'fastify' {
  interface FastifyInstance {
    hello: () => 'world';
  }
}
```

This is only a loose check though, since this comes with the problem where other parts of the plugin graph might not have access to some decorated properties on FastifyInstance, and users will not be able to easily tell this. In the following example (where hello/foo plugins decorate fastify with hello/foo functions that returns 'world' or 'bar'):

```TypeScript
import Fastify from 'fastify';
import { helloPlugin } from './helloPlugin';
import { fooPlugin } from './fooPlugin';

const fastify = Fastify({ logger: true });

fastify.register(async function (fastify) {
  await fastify.register(helloPlugin);

  fastify.get('/hello', async () => fastify.hello());
});

fastify.register(async function (fastify) {
  await fastify.register(fooPlugin);

  fastify.get('/foo', async () => fastify.hello()); // <--- TS doesn't catch this
});

fastify.register(async function (fastify) {
  fastify.get('/splat', async () => fastify.foo()); // <--- TS doesn't catch this
});

fastify.listen(4242).catch(console.error);
```
If you run this and navigate to localhost:4242/hello, it works, but not for /foo and /splat, giving you a runtime error that .hello() and .foo() are not functions on fastify.

If you have a lot of module augmentations on FastifyInstance, this could become a problem. Of course, you can also solve this by running tests against your endpoints, but that's less elegant than I thought TS would allow me to be.

2. Use a mix of interface extensions and guards. In the following example, each decorator would extend the FastifyInstance, and then provide an assertion function that throws if the decorated property/method is not on fastify.

```TypeScript
import Fastify, { FastifyPlugin, FastifyInstance } from 'fastify';
import fp from 'fastify-plugin';
import _ from 'lodash';

const decorateHello: FastifyPlugin = (fastify, opts, next) => {
  fastify.decorate('hello', function hello() {
    return 'world';
  });

  next();
};

export const helloPlugin = fp(decorateHello);

export interface HelloDecoratedFastifyInstance extends FastifyInstance {
  hello: () => 'world';
}

export function isHelloDecorated(
  fastify: unknown,
): asserts fastify is HelloDecoratedFastifyInstance {
  if (
    _.isNil(fastify) ||
    !(fastify instanceof Fastify) ||
    !_.isFunction(_.get(fastify, 'hello'))
  ) {
    throw new Error('Fastify instance is not helloDecorated');
  }
}
```

In usage, it's a bit more verbose, since you have to run the assertion each time you register each plugin, but it provides both compile time and run time type safety.

```TypeScript
import Fastify from 'fastify';
import { isHelloDecorated, helloPlugin } from './helloPlugin';
import { isFooDecorated, fooPlugin } from './fooPlugin';

const fastify = Fastify({ logger: true });

fastify.register(async function (fastify) {
  await fastify.register(helloPlugin);

  isHelloDecorated(fastify);

  fastify.get('/hello', async () => fastify.hello());
});

fastify.register(async function (fastify) {
  await fastify.register(fooPlugin);

  isFooDecorated(fastify);

  isHelloDecorated(fastify); // <--- server startup throws here

  fastify.get('/foo', async () => fastify.foo());

  fastify.get('/fooHello', async () => fastify.hello()); // <--- thus catching this
});

fastify.register(async function (fastify) {
  fastify.get('/splat', async () => fastify.foo()); // <--- TS catches this!
});

fastify.listen(4242).catch(console.error);
```

If you try running these, you'll have to comment out the lines with the comments since either TS or the assertions will catch improper usage of the decorated methods.

3. Some kinda generic encapsulation of this behavior, but this requires the ability to modify/return the instance with additional properties.

I tinkered a bit with mapped types, and found a partially working solution that returns the right intersection on an object with dynamic props, but the original variable doesn't get updated with this intersecting type (nor class instances themselves). This would make it really awkward to pass the resulting type around.

```TypeScript
function set<T, K extends string, O extends T & Record<K, V>, V extends any>(obj: T, path: K, value: V): O {
    // non-working internals
    return obj as any;
}

class Person {
    name: string;
    age: number;
    [index: string]: any;

    constructor(name: string, age: number) {
        this.name = name;
        this.age = age;
    }
}

let jane = new Person('jane', 25);

jane.height = 170; // jane is still a Person, where height is a known property

jane = set(jane, 'height', 170); // jane is still only a Person

let janeWithHeight = set(jane, 'height', 170); // janeWithHeight is a Person & Record<'height', number>
```

**Comment by weiliddat** [comment]
After mulling over this, I think approach 2 should be the recommended solution, since decoration is a runtime (startup, but still runtime) addition to Fastify instances, and having an runtime assertion + compile time type guard would be helpful.

If you think this could be helpful, I could open a PR against the docs in the TypeScript section in addition to declaration merging.

@Ethan-Arrowood, maybe you can chip in if you're available, since it seems like you wrote that section.

**Comment by fox1t** [comment]
I still have hard time figuring out how this could work into the wild: there are many plugins that are written just in plain JS and others that are written by the community. How can we enforce all plugin developers to expose always that assert function? Probably, it would be more helpful to expose it on fastify instance itself, same as for https://www.fastify.io/docs/latest/Decorators/#hasrequestdecorator and https://www.fastify.io/docs/latest/Decorators/#hasreplydecorator

I think that this would be a way better and more consistent API.

Speaking of TS typings, again, it is impossible to achieve consistency since we are decorating an object at runtime, after it is already instanced: you can do what you said basically only for "local" plugins but not for the plugins imported from node_modules. Again, am I missing something?

**Comment by weiliddat** [comment]
I don't think you could/should enforce this on all plugin developers, just like how you cannot enforce using TS or providing type declarations on plugin developers. This is merely a guide, just like how adding augmentations is a guide.
The intention here is, I think that polluting the global FastifyInstance interface is not a good idea in larger codebases, and this is a solution for dealing with it. Providing different ways to deal with it helps since the developer that consumes plugins sometimes have to deal with untyped (or worse, mistyped, which TS cannot fix on the consuming side) plugins.

I missed Fastify's own decorator checks - I'll experiment with that and maybe we'll have a better solution.

On the last point, it is possible to add extended interfaces and appropriate asserts/guards to node_modules plugins. Just add them separately in a file where you keep plugin declarations/helpers (for e.g. I name those vendor.ts and vendor.d.ts). However if there is already an augmented FastifyInstance interface, it's not that useful on compile time then, ironically.

**Comment by fox1t** [comment]
I disagree about to enforcement statement: we need a standard way to deal with type decoration and using the one that is provided by TS itself (interface augmentation) is the most safe choice here. For the last point you are, again, suggesting to do something at the user code level, but we need it at fastify/fastify-plugin level. As far I as know there is no way to make TS aware of "decoration contexts".

**Comment by weiliddat** [comment]
I don't understand what's the disagreement about — type augmentation is TS, but so is extending an interface, guarding, and intersection types. Also, isn't writing an interface augmentation something that plugin developers or users have to do anyways? Isn't that already additional code that someone has to write?

I agree that TS has its limits right now regarding contextual augmentation (or changing interfaces). However, you're suggesting to me that we should not look for solutions, or at the very least workarounds?

**Comment by fox1t** [comment]
Sorry for not being clear, here. I am not suggesting that we should not look for solutions. We already looked for many of them and this seemed the best solution.
If you want you can make a PR and we can discuss more about the solution you are proposing. However, we need to remember our constraints:
1. it has to work when a plugin is imported from node_modules
2. decorate modifies an already instantiated object and does not create a new one
3. types checkings doesn't have to add any runtime cost
4. it has to be easy to decorate fastify instance for the plugin developers
:)
