### ISSUE TITLE
JSON schema oneOf not working

### ISSUE THREAD

**Issue by BlackGlory** [fastify/fastify#2744]
## 🐛 Bug Report

JSON schema `oneOf` not working.

## To Reproduce

```js
const fastify = require('fastify')

const server = fastify()

server.post(
  '/test'
, {
    schema: {
      body: {
        data: {
          oneOf: [
            { type: 'number' }
          , { type: 'string' }
          ]
        }
      }
    }
  }
, (req, reply) => reply.send(req.body)
)

server.listen().then(console.log)
```

```sh
$ curl -X POST http://127.0.0.1:6829/test --header 'content-type: application/json' --data '{"data":123}'
{"statusCode":400,"error":"Bad Request","message":"body.data should match exactly one schema in oneOf"}

$ curl -X POST http://127.0.0.1:6829/test --header 'content-type: application/json' --data '{"data":"123"}'
{"statusCode":400,"error":"Bad Request","message":"body.data should match exactly one schema in oneOf"}
```

## Your Environment

- *node version*: v12.19.0
- *fastify version*: 3.9.2
- *os*: WSL1

**Comment by climba03003** [comment]
I think it is not a bug but is the intend behavior of ajv.

You can see in this [line](https://github.com/fastify/fastify/blob/master/lib/schema-compilers.js#L31), ```ajv``` is enabled ```coerceTypes```.
When ```coerceTypes``` is enabled, ```ajv``` will try his best to convert the data according to the specified type in schema.

"123" will convert to both "string" and "number", so ```oneOf``` cannot be meet.
123 will also convert to both "string" and "number", so ```oneOf``` cannot be meet.

In order to make it works, you need to start fastify to use the following code.
```javascript
fastify({
  ajv: {
    customOptions: {
      coerceTypes: false,
    },
  },
})
```

**Comment by BlackGlory** [comment]
@climba03003 Thanks, this problem is indeed related to `coerceTypes`.
Why is `coerceTypes: true` the default option for fastify?
