### ISSUE TITLE
Serverless as first class citizen

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#2746]
## 🚀 Feature Proposal

Currently, we are advertising that Fastify is not best suited for serverless environments.
This is true, any kind of support needs to have some workaround, see our [serverless docs](https://www.fastify.io/docs/latest/Serverless/).

I think we should address this, and provide better support for serverless environments,  instead of relying on external packages or workarounds.

## Motivation

Serverless and FaaS are becoming more and more used in the wild, and given the enormous flexibility that Fastify provides, I think we should do a better job at supporting this world.
The main challenges are:

- Fastify comes with its own server unless you use http injection.
  FaaS systems already give you a parsed request ready to use.
- Cold starts are an issue, Fastify has a fast booth, but it can be improved.
  We can experiment with schema precompilation and v8 snapshots.

## Example

The first problem can be solved by adding a new top-level generic API to inject an already parsed http request, with body, query, and so on. Then Fastify internally will skip request body collecting/parsing and part of the response sending.

```js
const fastify = require('fastify')()

// your app...

fastify.request({
  method: 'POST',
  url: '/foo/bar',
  query: { hello: 'world' },
  body: { is: 'fast' }
}, (response => console.log(response))
```

Then, we could support each major cloud provider with a lightweight plugin that connects the dots.

```js
const lambdaAdapter = require('fastify-aws-lambda')
const fastify = require('fastify')()

// your app...

module.exports = lambdaAdapter(fastify)
```

Regarding schema precompilation and other optimization strategies, [fastify-cli](https://github.com/fastify/fastify-cli) could definitely be handy, especially for improving the local development experience.

Feedbacks are welcome!

**Comment by AyoubElk** [comment]
I'd like to work on this.

The current implementation idea I have is to add `serverlessMode` option to fastify that would allow skipping all non-necessary operations in a serverless context, but I still don't have a full view on what needs to be skipped besides:
- creating a server and listening on a port
- sending a response use `res` object & setting response listeners (I presume this would need to be updated to and handled by each serverless adapter)
- running preParsing hooks
- handling request timeouts? (Not sure how this should be handled?)
Feel free to add more items to this list

Do you think this would be a viable approach? If so, I'll try to get a draft PR started in the following days.

**Comment by RafaelGSS** [comment]
Also, the https://github.com/fastify/benchmarks/pull/139 should give us better visibility on it.

**Comment by MetCoder95** [comment]
Any idea of how the API should look like and the configs as well?

Also, how do we benefit from V8 snapshots, it's there a way to trigger them from Node.js on runtime?

**Comment by MetCoder95** [comment]
Does this still on the radar?

**Comment by zekth** [comment]
I think we'll have to wait for this to be done : https://github.com/nodejs/node/issues/35711

At least regarding the v8 snapshots

**Comment by MetCoder95** [comment]
I knew it was wip for the v8 snapshots but didn't know about the issue. Thanks, we should wait then 🙂

**Comment by tinchoz49** [comment]
Hey @delvedor, I was playing with the excellent idea of `aws-lambda-fastify` and trying to simplify the process to inject the request from serverless. In my branch the result was very good, it increases the performance of fastify for serverless by 3x.

https://github.com/tinchoz49/aws-lambda-fastify/tree/tinchoz49/major-refactor-faster

I think having a  `fastify.request` method could allow us not only to work with serverless but also to integrate the architecture of fastify into frameworks like `uwebsocket` where their Server implementation is far away of being compatible with the node http server interface that fastify needs.

The crucial part of fastify is the router, that's where things like `queryString` are parsed and we don't have a way to pass directly a searchParams that is already parsed. For example, right now aws-lambda-fastify received an already parsed searchParams  object, then light-my-request convert the object into url params and the find-my-way parse `again` into the same initial object.

A suggestion:

If we can have a way to setup a different routing solution for fastify (always compatible with find-my-way) we can start to experiment with an alternative lookup that perform better with serverless, without having to modify fastify.

```js
fastify({
  routingFactory: opts => FindMyWay(opts)
})
```

**Comment by Eomm** [comment]
Your results are great!

> For example, right now aws-lambda-fastify received an already parsed searchParams object, then light-my-request convert the object into url params and the find-my-way parse again into the same initial object.

Could you list the optimization you found? Or, is the custom router the only bottleneck?
I think that facing all your findings one by one will improve the module for sure!

**Comment by tinchoz49** [comment]
Hey @Eomm, how are you? 

A few things that I found:

1. **routing**: I think the router as it is does an amazing job in performance. The only problem (my personal opinion) with the router is that is closely tied to the Request/Response interface of the `http` module, something that we don't have in serverless and most of the routing and parsing are solved by the serverless architecture.
But I don't want to change `find-my-way`, it works very well doing what it does. That's why I think that having the chance to provide a `custom routing` implementation for fastify we could solve any particular problem with the routing and serverless.

2. **avoid the ready call**:  I find that trying to avoid to call the ready() in every request gives a huge performance increase: https://github.com/tinchoz49/aws-lambda-fastify/blob/tinchoz49/major-refactor-faster/index.js#L26

3. **create a light version of Request and Response**: In my solution I choose to take some ideas from light-my-request but I build the Request/Response object on top of `streamx` that seems to be more simple than node streams and I think that is good in this case. If you check [req-res.js](https://github.com/tinchoz49/aws-lambda-fastify/blob/tinchoz49/major-refactor-faster/req-res.js) you will see that Request/Response are very simple and yet valid streams for fastify.

4. **try to work with strings in the response**: AWS expect a string response `utf8` or `base64` for the body, so we can try to avoid to work with buffers and just use the string response from fastify. Minimize every unnecessary buffer allocation or encoding/decoding it helps a lot here.

**Comment by Eomm** [comment]
1. let me try something about it
2. This is not clear to me: you need to call the `await app.ready()` should help the cold start as the lambda should not recreate the `app` instance. Is it working like this? 
3. Interesting: but you can already to it by using the standard inject:

```js
app.inject({
  Request: customImplementation
})
```

(we should add the same feature for `Response`. Could you try if your `req-res.js` class work?

4. need to check if it is already doable

**Comment by mcollina** [comment]
This was done
