### ISSUE TITLE
Credits are confusing & inaccurate

### ISSUE THREAD

**Issue by alexhultman** [fastify/fastify#280]
Looking at the Git history of this repo, it is obvious that **Tomas Della Vedova** have committed **by far** the most from the very beginning to the end. It is also clear that he wrote the main component, the router. But if I then look at the LICENSE file I only see this line:

Copyright (c) 2016-2017 **Matteo Collina** and the Fastify team

The only name mentioned is Matteo Collina, which by the looks of the history hasn't really done that much. I have a real problem with miscrediting and this feels shady. Why is Tomas not even mentioned in the LICENSE and why is he mentioned second in the README?

@delvedor

**Comment by delvedor** [comment]
Hi! Thank you for checking out the project!

In my opinion Open Source is not about who has written more code, but it is contributing to something, make it cool, learning new stuff, meet new people and help other people that might have your same problems.
I don't care who has written more code, I don't care about that at all.

The original idea of this framework was of @mcollina, and since we worked together on [fast-json-stringify](https://github.com/fastify/fast-json-stringify) he asked me if I wanted to join him in this adventure.
Matteo was so kind and helped me a lot, I learned a crazy amount of stuff thanks to him and the work done with this framework.
Yes, I have written more code, but try to check out who is reviewing every pull request. @mcollina is a highly skilled developer and helped my and other people who worked on this repository to write their code better not only because he needs good code for the framework, but because he wanted to help others to improve.
This is open source.

If @mcollina wants to add my name to the credits is not a problem, but I really don't care.
Is that even important?
We are here to try building something new and innovative, and also to have some fun together, not for arguing on some useless things.

So, again, thank you for checking out the project, but please try to change prospective. It is not a matter of lines of code, it is a matter of help each other growing as developers and as people.

Have a nice evening!

**Comment by alexhultman** [comment]
Well from a legal point of view you already have copyright on what you have written, automatically, and since you have produced more copyrighted code you also own more copyright. I would argue you *should* be mentioned in the license and in fact stand as the main author since that is your legal right. Sugar in candy is the main ingredient and that's why it is listed first. This project contains most of your work. But yeah I won't force you to, I just don't like when others take advantage of people.

**Comment by mcollina** [comment]
The problem in what you said @alexhultman are the words: “shady”, “taking advantage of”, and stuff like that. Like I am a monster that is exploiting @delvedor. I would argue that what Tomas and I do is our own business.

If ever we need to be grateful to some and put credits where they are due, we would have to put the names of LetzDoIt and nearForm, those companies sponsored most of the work here. This library would not be there if they didn’t support us. Again, none of this is your business.

This library is *novel*, and I encourage you to walk around and check the main features, and who conceived them. I did the plugin system and fast-json-stringify. Tomas helped there and did the router. I jumped in every PR and helped with reviews and feedbacks. And I fixed hard things when we were stuck.
5 lines of code might take 2-3 days of work, and the numbers of commit (or lines of code) are really not a good representation of the partecipation to a project.

If you think I am shady, I take advantage of people, and I exploit OSS for my own good, you should really ask around. Again, this is none of your business.

In the end, I do not think you have any ground to come and police us. You are welcome to be part of this community if you want to contribute in any meaningful way. To be clear, this is not meaningful.

You are right on one thing. Credits are a mess in this library, and it is time to clean up and put the name of all the team in the README. It has been on my list for a while. No one reads a LICENSE file, but everyone skims the README.

**Comment by alexhultman** [comment]
Yeah I guess Matteo Collina does what Matteo Collina does and Matteo Collina does not bother with proper credit disclosure. Have a nice weekend Matteo Collina, Matteo Collina deserved it. Bye Matteo Collina.

**Comment by mcollina** [comment]
I've locked this conversation, as it is moving into a personal assault on me. Sorry.
