### ISSUE TITLE
Inspect route's hooks

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#2993]
## 🚀 Feature Proposal

Get read-only access to the hooks of a route on the `onRoute` hook.

## Motivation

When a codebase grows over time and it is maintained by different people in different time frames -adding plugins-, it becomes difficult to understand the status of a route:

- how many hooks is the route running?
- do I need this hook for all the routes?

Analyzing this information can ease the refactor of a code base to split them into multiple microservice since missing shared schema or decorator lead to a failed start, instead a missing hook is silent.

This feature could lead to an enhanced `printRoutes()` that shows the hooks attached to each route

## Example

The snipped should give the `route.hooks.onRequest` array that contains the `myOnRequest` function

```
const fastify = require('fastify')()

fastify.addHook('onRoute', (route) => {
  console.log(route)
})

fastify.register(async (fastify) => {
  fastify.addHook('onRequest', function myOnRequest () {})
  fastify.get('/hello', () => {})
}, { prefix: '/bar' })

fastify.ready(() => {
  console.log(fastify.printRoutes())
})
```

**Comment by mcollina** [comment]
Yes indeed! This would be a nice feature to add.

**Comment by polymathca** [comment]
I put together a PR with a first stab at this. I borrowed the `prettyPrint` modifications I made to `find-my-way` but removed the radix display, as it felt very noisy with the hooks (and constraints) added to the mix.

Here's an output sample:

```
    │   │   ├── /new (POST)
    │   │   │   • (onTimeout) ["timeoutHook"]
    │   │   │   • (onRequest) ["anonymous","authenticate_token"]
    │   │   ├── /testing (GET) {"version":"1.0"}
    │   │   │   • (onTimeout) ["timeoutHook"]
    │   │   │   • (onRequest) ["anonymous","authenticate_token"]
    │   │   │   /testing (GET, PUT) {"version":"1.1"}
    │   │   │   • (onTimeout) ["timeoutHook"]
    │   │   │   • (onRequest) ["anonymous","authenticate_token"]
    │   │   └── /update (POST)
    │   │       • (onTimeout) ["timeoutHook"]
    │   │       • (onRequest) ["anonymous","authenticate_token"]
```

It is triggered by `printRoutes({includeHooks: true}) and accepts an array of hooks to explicitly display, e.g. `{ showHooks: ['onRequest', 'onSend', 'onTimeout'] }` or will import the full list from `lib/hooks.js (supportedHooks)` if the array isn't present.

I'm very open to alternatives to the current display. The bullets are there to make it easy to discern the hooks vs. routes (vs. handlers, vs. constraints) at a glance, but I'm not sure if it's possibly too noisy.

I don't know how this would affect the `prettyPrint` updates from `find-my-way` as there's a significant amount of overlap now. This seemed appropriate in `fastify` as it is targeting the hooks feature, so I'm not sure how best to handle the duplication of code. In order to maintain backwards compatibility, I kept the existing binding to `router.prettyPrint` as the default behaviour, and put this behind `fastify.printRoutes({ useNative: true })` but can refactor that and revise the existing tests if that's complicating things too much.
