### ISSUE TITLE
support to import

### ISSUE THREAD

**Issue by miguelAliaga** [fastify/fastify#305]
hi, it is not an issue, is a question instead. How I use import syntax  and how to use 
**--experimental-modules** used in node v8.5.0.

Thank for give us an amazing fw ;)

**Comment by StarpTech** [comment]
Hi @miguelAliaga this question has nothing to do with fastify. Please ask questions about nodejs here https://github.com/nodejs but I try to answer your question.

There is also support for commonjs modules. You would require fastifiy like:  `import fastify from 'fastify'`

Here is a link to a turorial http://2ality.com/2017/09/native-esm-node.html if you don't know ES6 Modules.
BTW: I just want to check it out but it seems Node.Js `8.5.0` has an critical blocker to use ES6 Modules https://github.com/nodejs/node/issues/15374#issuecomment-329952573 so we wait for the next release `8.5.1`

**Comment by delvedor** [comment]
Hi @miguelAliaga, thank you for checking out the project!
`import` is just syntax, it is supported :)

Obviously you can't do something like:
```js
fastify.register(import plugin from '/plugin')
```
Because `import` works in a different way compared to `require`, since `require` is synchronous and works at runtime, while `import` works before your code starts.
Checkout the [import documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) :)
