### ISSUE TITLE
can't Host to heroku.com

### ISSUE THREAD

**Issue by insaneazka** [fastify/fastify#3054]
![Screenshot (66)](https://user-images.githubusercontent.com/82513502/116902171-03c74f00-ac65-11eb-9d69-a7952acedc6f.png)

## To Reproduce

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *node version*: 16
- *fastify version*: >="^3.15.0",
- *os*:  Linux
- *any other relevant information*

can't use in server heroku but in local run normal windows and linux sorry i bad in english

**Comment by jsumners** [comment]
https://github.com/fastify/fastify/blob/25fed20a2ad5010d8a01d3ecafa01f1cc3329466/docs/Server.md#listen

**Comment by prowe214** [comment]
Ran into this issue on an app that worked previously with no version changes. So I created a minimal node.js + Typescript + Fastify 3.25.2 (and tried 4.13.0) server, using the following `listen` implementation:

```ts
const main = async () => {
  const fastify = Fastify();

  fastify.route({
      url: "/",
      method: ["GET"],
      handler: async (req, reply) => {
          reply.send("Hello World");
      },
  });

  fastify.listen({ port: process.env.PORT || 3000 }, (err, address) => {
      if (err) {
          console.error("ERROR! -", err);
          process.exit(1);
      }
      console.log(`Server listening on ${address}`);
  });
}

main();
```

The boot timeout still occurred.  Switching to Express with the same code (adjusted for their syntax) and deploying to the same location did not have this issue.

```
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
```

All other relevant implementations noted in @jsumners link also did not solve the issue.  

I have enjoyed Fastify so I would love if you considered reopening this issue, or at least providing documentation noting the correct configuration to avoid this specific error in Heroku, because nothing really exists based on my extensive googling.

**Comment by mcollina** [comment]
https://www.fastify.io/docs/latest/Reference/Server/#listen < this explains what is happening.

**Comment by mcollina** [comment]
Specify the host and set it to 0.0.0.0.

**Comment by prowe214** [comment]
Oh understood, okay I'll mess around with it tomorrow.  I had that set up in the old config and could swear I tried it in the new one, but maybe I missed it.

Thanks for the reply!
