### ISSUE TITLE
"onRequest" hook not triggering when route is not found

### ISSUE THREAD

**Issue by luisorbaiceta** [fastify/fastify#3120]
## 💬  Why is the `onRequest` hook not triggering when the application doesn´t find a registered matching route?

When running the `npm init fastify` command and registering a plugin that adds a `onRequest` hook to be available for all the application, if the route is not found, the hook is not triggered and instead fastify passes control to the default error handler, which then throws the 404 not found error. Is this expected behaviour?

### Example plugin (project/plugins/deny.js)
```js
'use strict'
const fp = require('fastify-plugin');

module.exports = fp(async function (fastify, opts) {
    fastify.addHook('onRequest', async function (request) {
        console.log('This should trigger on every request');
    })
});
````

### Registered Route (project/routes/root.js)
```js
'use strict'

module.exports = async function (fastify, opts) {
  fastify.get('/', async function (request, reply) {
    return { root: true }
  })
}
````

The weird behaviour comes in the app.js file. If I register a `setNotFoundHandler` then the hook works as expected.

### App (project/app.js)
```js
'use strict'

const path = require('path')
const AutoLoad = require('fastify-autoload')

module.exports = async function (fastify, opts) {
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'plugins'),
    options: Object.assign({}, opts)
  })

  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'routes'),
    options: Object.assign({}, opts)
  })

  // -----------------------------------------------------------------
  fastify.setNotFoundHandler(); // IF I ADD THIS LINE THEN IT TRIGGERS THE ONREQUEST HOOK
  // -----------------------------------------------------------------
}
````

[Example Repo](https://github.com/luisorbaiceta/fastify-hooks-doubt)

## Environment

- *node version*: 14
- *fastify version*: >=3.0.0
- *os*: Windows

**Comment by mcollina** [comment]
It will be a while before I have time to take this on. If anybody else would like to give this a shot, please go! I'm not marking it "good first issue" as it's likely not.

From my point of view there is not much urgency either, as most applications would add a not found and error handler in production.

**Comment by weiliddat** [comment]
I wanted to help with this but I couldn't reproduce this.
I tested with fastify-autoload as @luisorbaiceta's example, and in a plain `fastify.register(require("./plugin/deny"))` style.
With and without setNotFoundHandler, they all fired the onRequest hook when a request comes in.
Will dig around and see.

### Environment
node version: 14.17.0 and 16
fastify version: main
os: Windows WSL2

**Comment by luisorbaiceta** [comment]
I will give it a shot and try to search where the race condition occurs. I'll send a PR as soon as I find something @mcollina

**Comment by weiliddat** [comment]
I can reproduce it now. I was just testing with found routes. 🤦‍♂️
So this also happens without fastify-autoload, and running it plain without fastify-cli.

**Comment by weiliddat** [comment]
So what I found so far, after a bit of logging on fastify and avvio.

### without calling setNotFoundHandler
```
[nodemon] restarting due to changes...
[nodemon] starting `node index index.js`
setNotFoundHandler after
addPlugin bound _after
addPlugin app
setNotFoundHandler after cb
addPlugin deny
addPlugin rootRoute
addHook onRequest
addPlugin bound _after
addPlugin bound _after
context.onRequest null
http://127.0.0.1:3000
```

### call setNotFoundHandler after plugins
```
[nodemon] restarting due to changes...
[nodemon] starting `node index index.js`
setNotFoundHandler after
addPlugin bound _after
addPlugin app
setNotFoundHandler after cb
addPlugin deny
addPlugin rootRoute
setNotFoundHandler after
addPlugin bound _after
addHook onRequest
addPlugin bound _after
addPlugin bound _after
setNotFoundHandler after cb
context.onRequest null
context.onRequest [ [Function: bound ] AsyncFunction ]
http://127.0.0.1:3000
```

`setNotFoundHandler` is initially called during [fastify startup](https://github.com/fastify/fastify/blob/caf108942b9009d17d638a1f4a581b37e4999465/fastify.js#L367) to [set default 404 handlers with a catch-all route](https://github.com/fastify/fastify/blob/caf108942b9009d17d638a1f4a581b37e4999465/lib/fourOhFour.js#L67-L152). 
This happens before the plugins are picked up.
The plugins add the onRequest hook and / route.
The onRequest hook on the catch all route is not updated with these hooks (which also makes sense since it's not a context that is explicit to the user).

If you call setNotFoundHandler with no arguments, then it still goes through [the same procedure of adding hooks from the context (now with additional hooks) to the default handler](https://github.com/fastify/fastify/blob/caf108942b9009d17d638a1f4a581b37e4999465/lib/fourOhFour.js#L133-L141).

The same thing will happen if you call setNotFoundHandler outside of the context that registers these plugins, for e.g. 
```
fastify
  .register(require("./app"))
  .register(async function (fastify) {
    fastify.setNotFoundHandler(() => "boo");
  })
  .ready(() => fastify.listen(3000));
```

This does not trigger the onRequest hook since it's a different context. So it makes sense in terms of encapsulation, just that it's not obvious to the user that the context of the default 404 handler is not global.

I think it makes sense to document this, but I wouldn't want to change this behavior since this will add unintended hooks and behaviors to the default 404 handler.

**Comment by mcollina** [comment]
The safest option is to document this behavior in v3, and possibly improve it in v4.

**Comment by weiliddat** [comment]
I added a short paragraph on the default behavior of `setNotFoundHandler`, and if you want to add hooks via plugins you can do so via calling it again in the right context.

**Comment by crispinkoech** [comment]
Hey @weiliddat, just following up from this issue; so my `onRequest` Hook is triggered when the route does not exist, this is the default behaviour, right? (I haven't attached a `setNotFoundHandler()`)

I'm using this hook to handle some authorization. How would I go around disabling this default behaviour? I'd prefer the application to respond with a 404 for unregistered routes, and a 401 (with invalid authorization) for registered ones.

**Comment by weiliddat** [comment]
Hi @crispinkoech. It depends on the plugin context at whatever is handling the route. It could be handlers registered for not found, or error handlers, or some kind of catch-all handler for unregistered routes. If you use another plugin, they could also run fastify.setNotFoundHandler for you (like how fastify-sensible sets setErrorHandler for you).

It might help if you printRoutes and printPlugins and show us what you have.
