### ISSUE TITLE
enum values not enforced by response schemas

### ISSUE THREAD

**Issue by mattyod** [fastify/fastify#3153]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.18.0

### Node.js version

14.16.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

Specified enum values for strings are not enforced in response schemas. Is this by design or a bug?

### Steps to Reproduce

With a schema such as:

```
{
  type: 'object',
  properties: {
    foo: {
      type: 'string',
      enum: ['bar'],
    },
  },
}
```

and reply code such as:

```
reply.code(200).send({ foo: 'foo' });
```

The object `{ foo: 'foo' }` is received by the client.

### Expected Behavior

Not sure, should the property not be returned as would be the case with other invalid fields?

**Comment by climba03003** [comment]
I think the issue should go to https://github.com/fastify/fast-json-stringify. `fastify` use `fast-json-stringify` for response serialization.

**Comment by Eomm** [comment]
The stringify process doesn't **validate** your output
You must use this plugin https://github.com/fastify/fastify-response-validation#fastify-response-validation

**Comment by mattyod** [comment]
Thanks, I guess we'll check the enums ourselves rather than turn on full response validation. It's a bit confusing though because it seems that partial checking and coercion does occur which i guess led me to believe validation was being carried out.

**Given a schema such as:**
```
{
  type: 'object',
  properties: {
    foo: {
      type: 'integer',
      default: 1,
    },
    bar: {
      type: 'string',
    },
    baz: {
      type: 'string',
      enum: ['foo', 'bar'],
    }
  }
```
**and a reply of:**
```
{
  bar: 1,
  baz: 'wrong',
}
```
**The received response is:**
```
{
  "foo": 1,
  "bar": "1",
  "baz": "wrong",
}
```

The properties `foo` and `bar` have been coerced to have valid values but `baz` has been allowed through. 

Posting this for others that may find this thread.

**Comment by Eomm** [comment]
>  It's a bit confusing though

The type coercion is fine, you have set the schema and you are saying that you want a string instead of a number.
But what should we do if the value is not in the set?
If the serializer trigger an error, the user should catch it somehow 
Should we omit the property then? it seems wrong if the user set it with a value

This lead to a lot of configuration and burden to setup up the project if we support both cases.

For this reason, a plugin that adds this feature is more clear: you know what you want to archive and you will not have an unexpected exception in production because one key is missing on the response enum for example.
For sure we could improve the communication of this aspect
