### ISSUE TITLE
`reply.send` is not available from inside of middlewares

### ISSUE THREAD

**Issue by benderTheCrime** [fastify/fastify#319]
Hey All,

I'm having a strange issue with middlewares. AFAIK I'm using the most recent version of fastify.

It says [here](https://github.com/fastify/fastify/blob/master/docs/Middlewares.md):

> Fastify provides out of the box an asynchronous middleware engine compatible with Express and Restify middlewares.

I have put together some sample code:

```javascript
const fastify = require('fastify')();

fastify
    .use('/ping', function(req, res) {
        res.send('foo');
    })
    .get('/ping', function(req, res) {
        res.send('bar');
    }).listen(8080);
```

In the above example, if I hit "http://localhost:8080/ping," I get an error because `res.send` does not exist.

Is this hook not exposed until all of the middlewares are processed?

**Comment by allevo** [comment]
Hi!
 and thank for checking `fastify` out!

Probably the documentation lacks to mention that the `req` and `res` are [`IncomingRequest`](https://nodejs.org/docs/v6.9.4/api/http.html#http_class_http_incomingmessage) and [`ServerResponse`](https://nodejs.org/docs/v6.9.4/api/http.html#http_class_http_serverresponse) instance respectively. So, you should call only methods defined in the nodejs documentation.

Internally `fastify` wraps `req` and `res` nodejs instance using `Request` and `Reply` classes but they are built *after* the middlewares phase.

So, if you need to create a middleware you have to use the nodejs instances. Otherwise you can use the [preHandler  hook](https://github.com/fastify/fastify/blob/master/docs/Hooks.md) that has `Request` and `Reply` fastify instances

**Comment by benderTheCrime** [comment]
Thanks for getting back to me.

I feel like it somewhat violates the spirit of having an Express-compliant middleware engine if I can't take a middleware I was using with Express and plug it into Fastify.

Follow up question: wouldn't wrapping req/res with Request/Reply be _just as fast_ if you wrapped it before as opposed to after the middlewares phase? What would the side effects/implications actually be for Fastify?

I'm ok if all that comes out of this is a clarification that this is the case in the documentation, but the line about being Express-compliant should also be removed if I can't take any middleware from Express and plug it into Fastify!

**Comment by benderTheCrime** [comment]
Also, any recommendations you might have for workarounds to use a middleware with a `res.send` call with fastify would also greatly be appreciated! Would it be possible to perhaps wrap the InternalResponse in a Reply that would then be wrapped in a Reply?

**Comment by allevo** [comment]
Hi, sorry for the delay.
In fastify the middlewares has not the fastify wrappers as argument. So, the `send` method is not defined.

Anyway, you always use the nodejs code methods like [`end`](https://nodejs.org/docs/latest/api/http.html#http_response_end_data_encoding_callback) and [`setHeader`](https://nodejs.org/docs/latest/api/http.html#http_response_setheader_name_value)

Express works different. Your express code can use `json`  because of [this](https://github.com/expressjs/express/blob/master/lib/application.js#L231) but this line drop the performance down.
Fastify mind want to be fast as can as possible. To do that, the framework allows to you to stop the request before the wrapping commonly for small tasks.

If you want to use `send`  method please see how [`hooks`](https://www.fastify.io/docs/latest/Hooks/) work in fastify

**Comment by benderTheCrime** [comment]
Would you mind if I opened a PR to issue an update to the documentation to reflect this?

**Comment by allevo** [comment]
Yes, if you find documentation not so clean, please fire a PR!
We'll discuss the changes in that issue

**Comment by benderTheCrime** [comment]
https://github.com/fastify/fastify/pull/328
