### ISSUE TITLE
New alias: fastify.plugin()

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#3360]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I would expose a new API: `fastify.plugin()` that would be a `register` alias 

```js
app.plugin(require('fastify-mongodb'), config.mongo) // this does not create a new context

app.register(todoPlugin) // as-is: it creates a new context

app.plugin(todoPlugin) // this does not create a new context
```

This feature could be integrated into core to improve documentation readness, but it can be added into the `fastify-plugin` as decorator or in a dedicated plugin.

What do you think?

### Motivation

- let the code be more readable: when you call `register(plugin)` you must be aware that the plugin is using `fastify-plugin` under the hood and you can deduct, but it is not explicitly declared.
- it would be possible to auto-wrap application's plugins reducing the context created during the startup

### Example

See above

**Comment by mcollina** [comment]
Sure thing, PR? Maybe target `next`.

**Comment by MetCoder95** [comment]
The main difference will be `plugin` will do what registering a plugin with the `Symbol['plugin-override']` does? 
If I can add my small two cents here, I've had the confusion already when creating small plugins for an app, when the plugin doesn't decorate the parent instance because either I forgot to use `fastify-plugin` (maybe plugin soo small) or forgot to set `Symbol['plugin-override']`, but also agree can cause some friction.

Just thinking out loud, it can be possible that maybe making the `Symbol['plugin-override']` more visible, maybe changing the shape can be better? I'm also missing the context about why using a Symbol for it, so happy to know more about the reason :)

**Comment by Eomm** [comment]
> I think this will add ambiguity and confusion.

Does `fastify.module()` sound better?
Or do you think an alias is not worth it?

> The main difference will be plugin will do what registering a plugin with the Symbol['plugin-override'] does?

Yes, if it is not already set of course

> maybe changing the shape can be better?

This would be a huge change that impacts a lot to the whole community, I would consider that only if necessary.

>  I'm also missing the context about why using a Symbol for it

Because it does not show by default: https://github.com/Eomm/grokking/blob/master/test/misc/symbol.test.js

**Comment by jsumners** [comment]
> > I think this will add ambiguity and confusion.
> 
> Does `fastify.module()` sound better? Or do you think an alias is not worth it?

As a new user, which do I use and why? How do we effectively explain the seemingly subtle, but really vast, difference between `register` and `plugin`? Don't they both "register" "plugins"?

Right now, encapsulation is the default unless you have thoroughly read the docs and opt out via the symbol/plugin. I firmly believe encapsulation to be the defining feature of Fastify and would not want to make it more confusing for new users.
