### ISSUE TITLE
Make available the data validation method with the specified schema and the data serialization method with the specified schema

### ISSUE THREAD

**Issue by budarin** [fastify/fastify#3897]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I suggest making 2 methods available (it doesn't matter for which object  fastifyInstance or FastifyRequest)

- `vadidate(customSchema, data)`
- `serialize(customSchema, data))`

or simply expose/reexport  `Ajv` and `fast-json-stringify` instances/fabrics to  reuse them

### Motivation

Sometimes it is necessary to make a request to a third-party service and I would like to be able to validate its parameters with the specified schema and then serialize the data into a string with the specified schema

Now in order to do this, I need to configure the project and include packages `ajv` and `fast-json-stringify` as a direct dependency and then make sure that they are the same version as in `fastify` in order not to have duplicates and not to increase the size of the application. 
They need to be configured and created - this is additional code that duplicates the code in `fastify`.

### Example

```js
app.get('/getSomeComplexData', async (req, res) => {
   const validationSchema = validationSchemas['Method1'];
   const stringifySchema = serializationSchemas['Method1'];
   const params = getParamsForMethod1(req); 
   
   if (req.validate(validationSchema, params) === false) {
      throw new Error('Validation of parameters for the Method1 failed');
   }
   
   const method1Data = await fetch('http://some_service/method1').json();
   const calcData = calculateSomedata();

   return { result: {
        calcData,
        method1Result: req.serialize(stringifySchema , method1Data)  // for some reason we need a string instead of json
   }}
});
```

**Comment by climba03003** [comment]
@zekth I think it is what you need in `fastify-websocket`.
I agree to expose the compiler, it is useful for anyone who want to compile there custom validating function.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by zekth** [comment]
> @zekth I think it is what you need in `fastify-websocket`. I agree to expose the compiler, it is useful for anyone who want to compile their custom validating function.
> 
> One concern only, the compiler should be on `FastifyInstance` instead of `FastifyRequest`.

Indeed this is what we need 👍

**Comment by metcoder95** [comment]
I was doing a quick assessment to start working on this and it seems to be doable but will require a few changes here and there, mostly due to the fact that the Serialization and Validator compilers are made with an abstraction on top. This is to bring power to set up granular validators/serializators based on HTTP parts of a request (like `method` and `path`).

And this is even abstracted within the defaults of fastify thanks to [fast-json-stringify-compiler](https://github.com/fastify/fast-json-stringify-compiler) and [ajv-compiler](https://github.com/fastify/ajv-compiler), and they're transparent to which validation compiler are using, making it opaque to fastify being able to return a specific instance of a compiler (either serializer or validator).

One thing that can be done is to make this based on **per-request only**, meaning that we can follow the initial suggestion from @budarin and respect any kind of custom implementation made by the implementation at a route or general level.

**Note**:
- The SchemaController is made based on the same abstraction based on the parts of an HTTP request.

**Comment by mcollina** [comment]
Looks like a good idea

**Comment by climba03003** [comment]
> One thing that can be done is to make this based on per-request only

Not really follow what it means by `pre-request only`. 
I think both the validate and serialize function should be cached once it passed to the function.
If it is `pre-request only` that means the function will be dropped once the request end.

I don't think someone would not share the same schema in this case. But an option to determine if the function is `one-off` seems interesting.

**Comment by metcoder95** [comment]
>Not really follow what it means by pre-request only.

Sure, I mostly referred to attaching the function to the request object instead of the fastify instance, like the first suggestion: `req.serialize` and/or `req.validate`. In that way, we expose whatever serializer/validator is exposed in that context (if none, it is linked to the parent one). Thanks to this, the implementation can take advantage of whatever customization was made to the route (or parent) validator/serializer.

>I think both the validate and serialize function should be cached once it passed to .serialize(<schema>, <json>) or .validate(<schema>, <json>).
If it is pre-request only that means the function will be dropped once the request end.

Here I would rather prefer ergonomics in a two-step manner:
1. Submit the schema, and have a validation function in return
2. Use the returned validation function for subsequent usage

or even be more flexible, so if the input is omitted, we can return the compiled function.

We can even use the schema provided as the key for caching the returned function using a WeakMap for it. But providing two inputs will complicate the things, wdyt?

>It can support dynamic schema from input if someone need.

Exactly this is what I'm aiming for, the schemas provided can be stored within the validator/serializer for subsequent usage, and also the implementation can take advantage of custom settings for a customized validator/serializer per-route (e.g. `coerce-types: false`, or even custom plugins).

More or less what I have in mind:

```js
// we can force to provide an id for the schema
const subSchema = {
  $id: 'my_schema'
  type: 'object',
  properties: {
   hello: 'string'
  }
}

fastify.get('/', { schema }, async (req, reply) => {
  const input = await (await fetch(`https://example.com/${req.body.id}`))).json()

  const result = req.validate(subSchema, input); 

  // or

  const validate = req.validate(subSchema) // This can be cached after first invocation for subsequent usage
  // The id will help to store the schema for future reference if needed
  const result = validate(input)

  // or
  if (input.something) {
	const newSchema = Object.assign({}, subSchema, { properties: { hello: 'string', world: 'string'}})
	// New schema detected thanks to the WeakMap, we compile and cache the new compiled fn
        const input = req.validate(newSchema, input)
  }
})
```

We can advise to not alter the schemas but create new ones.

**Comment by budarin** [comment]
May be it is necessary to provide a compiler so that the schema is not compiled every call over and over again?

```js
const validate = fastify.createValidator(inputSchema);
const stringify = fastify.createStringify(outputSchema);

fastify.get('/', { schema }, async (req, reply) => {
    const params = { ...};
    
    if (validate(params)) {
        const output =await(await fetch('https://example.com/', { ... params ... })).json();
        
        reply.send(stringify(output))
    }
    ...
})
```

**Comment by climba03003** [comment]
> We can even use the schema provided as the key for caching the returned function using a WeakMap for it. But providing two inputs will complicate the things, wdyt?

Good.

**Comment by metcoder95** [comment]
@budarin 
>May be it is necessary to provide a compiler so that the schema is not compiled every call over and over again?

Can also be a way to go, but that will require quite a number of changes to the way the schemas are handled and stored within Fastify because the way this is abstracted creates the dependency of always providing the different parts of an HTTP request (e.g. Headers, Path, Method).
As for the default implementation of fastify, this is not a problem, but for custom implementations that heavily depend on those parameters to decide how to compile the validation/serialization function, it becomes a problem (e.g. [fastify-split-validator](https://github.com/metcoder95/fastify-split-validator)).

Along with that, [Ajv](https://ajv.js.org/guide/getting-started.html#basic-data-validation) already takes care of caching:
>Ajv compiles schemas to functions and caches them in all cases (using the schema itself as a key in a Map) so that the next time the same schema object is used it won't be compiled again.


So, aggregating all of the discussion here, I'll prepare a PR for this week with a PoC 🙂

**Comment by metcoder95** [comment]
> I would add a getter here: [fastify/ajv-compiler@`bbc98b8`/index.js#L36](https://github.com/fastify/ajv-compiler/blob/bbc98b83ecdc98826c2b621cc9aaa4bada21f3ff/index.js#L36)

That will work for the defaults but not when the route has custom `validatorCompiler`/`serializerCompiler`, as `ajv-compiler` is not aware of such customization, isn't it? Unless I'm missing something, an abstraction on fastify still will be needed to handle such cases.

> I think the user must be aware that the instance has all the `add schema()` references, so if the dev thinks to run code like this:
> 
> ```
>   const input = await (await fetch(`https://example.com/[](https://example.com/)${req.body.id}`))).json()
>   const result = req.validate(subSchema, input); 
> ```
> 
> the dev must be aware that:
> 
> * the subSchema is not compiled, so it will be slow (compile + run)
> * the ajv instance may face `$id`s conflicts

That would be super nice to add the docs for awareness. That being said, I also think that adding the schema to the ajv instance for further references and implementing caching as suggested can somehow lower the overhead but not fix it at all, that is still in the dev's hands.

Please correct me if I'm doing a wrong assumption 🙂

**Comment by jsumners** [comment]
Why is it not acceptable to supply your own schema container? The feature was added specifically to make it easy to work with schemas in whatever way the developer wants while utilizing them within Fastify.
