### ISSUE TITLE
Error propagation issue

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#391]
I found a strange behaviour @mcollina @allevo
It's a bug https://github.com/mcollina/avvio/issues/32 or limitation in avvio but I also open an issue here. The reason is that only the next `after` or `ready` callback get the error and [here](https://github.com/fastify/fastify/blob/master/fastify.js#L378) is a `after` callback registered that's why example 3 doesn't work.

We have 3 different states

1. Error is correct propagated
```js
const fastify = require('fastify')()

function fastifyStatic (fastify, opts, next) {
  return next(new Error('test'))
}

fastify.register(fastifyStatic)
// .after((err) => console.error('After:' + err))

// fastify.get('/', (req, reply) => {})

fastify.listen(0, function (err) {
  console.error('Listen:' + err)
})

// Listen:Error: test
```
----
2. The error is only propagated to the next `after` function we can't catch it in the `listen` callback.
```js
const fastify = require('fastify')()

function fastifyStatic (fastify, opts, next) {
  return next(new Error('test'))
}

fastify.register(fastifyStatic)
.after((err) => console.error('After:' + err))

// fastify.get('/', (req, reply) => {})

fastify.listen(0, function (err) {
  console.error('Listen:' + err)
})

// After:Error: test
// Listen:undefined
```
3. No error is propagated this issue is related to https://github.com/fastify/fastify-static/issues/14
```js
const fastify = require('fastify')()

function fastifyStatic (fastify, opts, next) {
  return next(new Error('test'))
}

fastify.register(fastifyStatic)
//.after((err) => console.error('After:' + err))

fastify.get('/', (req, reply) => {})

fastify.listen(0, function (err) {
  console.error('Listen:' + err)
})

// Listen:undefined
```

**Comment by delvedor** [comment]
If you see this from the point of view of `avvio` is not an error, is the correct behaviour. If you want that the error gets propagated you must pass the error to the next callback of `after`.

If you see this from the point of view of Fastify, yes, it's a bug. 
Because we register the routes inside an `after` callback and we do not propagate that error.

I've fixed that 3 hours ago https://github.com/fastify/fastify/pull/390 :P
You will get this fix in the next release of Fastify, very soon ;)

**Comment by StarpTech** [comment]
Nice 👍
