### ISSUE TITLE
onRoute hook executed for endpoint declared before registering it

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#4044]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.3

### Node.js version

18

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

latest

### Description

When the `onRoute` hook is registered after a GET handler, it is executed for the HEAD route only.

### Steps to Reproduce

```
const fastify = require('fastify')
const app = fastify()

app.addHook('onRoute', function inspector(routeOptions) {
  console.log('before ' + routeOptions.method)
})

app.get('/', function (request, reply) { })

app.addHook('onRoute', function inspector(routeOptions) {
  console.log('after ' + routeOptions.method)
})

app.ready()
```

Prints:

```
before GET
before HEAD
after HEAD
```

### Expected Behavior

I think the after hook should not be executed.

It should print:

```
before GET
before HEAD
```

**Comment by mcollina** [comment]
Agreed! Good spot!

**Comment by climba03003** [comment]
The head route added by `fastify` is register in the `next` cycle.

The expected behavior mentioned in here require the `HEAD` route register parallel to `GET`. Which would cause
1. Cold start time increase.
2. Register and de-register route frequently.

I don't know if there are better option to do it.
I would whether not fire the `onRoute` hook if the route is not added by user.
