### ISSUE TITLE
Typescript: Type Provider information gets lost with onRequest

### ISSUE THREAD

**Issue by qqilihq** [fastify/fastify#4120]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### Node.js version

16.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

n/a

### Description

I've added the new type providers from Fastify 4 to my project to avoid the redundant, cluttered generics.

My project makes use of “onRequest” hooks which check a custom authentication in different endpoints.

Example:

```typescript
// simplified for demo purposes -- this is used in various endpoints
const authenticateHook: onRequestAsyncHookHandler<any, any, any, any, any, any, any, any, any> = () => {
  return Promise.resolve();
};

// example copied from https://www.fastify.io/docs/latest/Reference/Type-Providers/#typebox
server.get('/route', {
    schema: {
        querystring: Type.Object({
            foo: Type.Number(),
            bar: Type.String()
        })
    },
    onRequest: authenticateHook
}, (request, reply) => {
    // type Query = { foo: number, bar: string }
    const { foo, bar } = request.query // NOT type safe when adding `onRequest` :-(
})
```

The problem: After adding the `onRequest` hook, the type safety gets totally lost and e.g. request.query is `unknown`.

I've been trying various workarounds (e.g. handling through all these generics), however I didn't really get to a clean, let alone, scalable solution.

### Steps to Reproduce

See snippet.

### Expected Behavior

I'd expect the type information to be preserved.

**Comment by mcollina** [comment]
@fastify/typescript could you take a look?

**Comment by sinclairzx81** [comment]
@qqilihq Hi! Does the following help? [TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAMQIYGcbAGYE8A0cDeiq62ASgKYCOAruWnsmplhWADZZwC+cGUEIOAHIMxZkICwAKFCRYBOABUsYcgCEIAD2WqACvwBuwACbko3Xv0FCAAqKbYA9DBXkAtGEMmzbl6oBGWpIy4NDwhDrkFnwCwjYowAB2AMZsSMBQzq6BmsHSqFgpvNQp6BCJcEjUMAAW5InoyUgw5AASEBAA1gA8inDkmi2JxihEDixUtPRwAKr9g-UjYyQT7FgAfAAUUJN0MABcSng7a4czAJQE0nBwjo5wiRAthyg1SDvGcDUdnaMgSJw3gYogZ3lgkgBzOAQ+pmYDJOBgd5IECjVTmfjVch4FAQOA7Gh7AB0hKgnFeEGobE+-iiJU6jwA7olpFxpNJGCtNuciYzgLVIvoIEZTFBeq4NNpXEKRWYtjyYTBNkJHJiWkI8Phrjc4OUKIS0IdtrtpicOJcALzrSrVOoNeHNNo-Y0GmDHchrc54O4PPH+JLGbU3FDJOr-Q5aqQ66NwUlYNBQSGHSJEgDy-gAVuRkkrIzH87wOsnXESAHLUEC0qDcnBBgs3fzvYuqIkAZRgicSEO5dejXHOdbZUi4eBdUzd+I95rgVquUZ1yXKaAUGA6eEb5h4FsnrpJtDJt3uXVZ5yAA)

```typescript
async function authenticateHook<T extends FastifyRequest, U extends FastifyReply>(request: T, reply: U) {
  // note: shared hooks may have varying generic params per route, so request.query should be unknown
}

Fastify().withTypeProvider<TypeBoxTypeProvider>().get('/route', {
    onRequest: (request, reply) => authenticateHook(request, reply), // no bind
    schema: {
        querystring: Type.Object({
            foo: Type.Number(),
            bar: Type.String()
        })
    }
}, (request, reply) => {
    const { foo, bar } = request.query // ok
})
```

**Comment by qqilihq** [comment]
Hi @sinclairzx81  -- great, that indeed does the trick. Thank you very much!

**Comment by mcollina** [comment]
I think we should document that, would you like to send a PR?

**Comment by RafaelGSS** [comment]
Isn't it a bug? @sinclairzx81 It seems that the type should be inferred even in a `bind`. I'm missing something?

**Comment by sinclairzx81** [comment]
@RafaelGSS Hi! Yeah, it's clearly a bug. Had a quick look into it last night, but did not find the cause (so suggested the workaround in the interim). I may do a bit more investigation into this over the next few days.

**Comment by sinclairzx81** [comment]
@RafaelGSS See PR for potential fix

**Comment by RafaelGSS** [comment]
Thank you! I'm planning to look at it tomorrow

**Comment by qqilihq** [comment]
Thank you all!

**Comment by sinclairzx81** [comment]
@ryanstaniforth Hi. I'm not currently looking into this issue. But see examples below if they are helpful.

## Shared Handlers

The following sets up a shared external handler. Note that because an external handler may be shared across multiple routes, we will want to treat any route parameters as unknown. The following achieves this.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAKFCRYcAGKMKMYHlQAaROMnTZAJQwBHAK4YpCiVJmp1YevLgAJCBADWFxtQAm9DFAAiEahjFa60z3A4+ITEJHjKRoLC0PBIaJgAQnzxGAAKhABuwI6uQQREpGThhrLsnAC0YJnZruUcmDz8AgKsrHDlHZ1d3T29ff0DAy1tBiqocOrauvAAygAWjFAYjsPtg+sbm5vNGLwi8PVYo0aTOlLzi8twALxKJcaaZzAAPAjYCg7mnx-UqAB8zVaay2INBW1WAFFeIxwC5VmCEYi+s08L5aP5qHALktHPYnC4oAAKJZTKQALjuY1O02xywUS1MqApxzUGEZCkcngwFKstjxzlcHi8Pj8wE8AEpEAJAkDaJ4pIpeApxrhbiSngA6HiOcZwIEUBY4inUCDwRj0egQADuywE2GaLNQhPFGqtwBgcxS6QgWRyUGeKSSvC91T9f2dGsgUkJJFYJDk0qlgUCnmp5KxhuW-IJCkTgQotDmGBAjApCDzye1TJQnA1AHkuAArDDownl5MduC8CkpDUAOS0IC4rmdCc7yervYHQ5H4orgWw4rHnaWFEg1Ao3KT47gACYAAz7nu1mYwKA0ADmzvnOAr9oXy+Jmnpukl1z+28Cco3sS7yqCaqaFqEA6s0Harhqm5ODGRYWhAJBzguAjikAA)

```typescript
// -----------------------------------------------------------------
// Fastify Request Shared
// -----------------------------------------------------------------

export type FastifyRequestShared = FastifyRequest<{}, any, any, any>

// -----------------------------------------------------------------
// Example
// -----------------------------------------------------------------

function SharedHandler(request: FastifyRequestShared, reply: FastifyReply, done: HookHandlerDoneFunction) {
  // const { x, y } = request.body  // shared: not allowed
}

Fastify().withTypeProvider<TypeBoxTypeProvider>().post('/',
  {
    onRequest: SharedHandler, 
    schema: {
      body: Type.Object({
        x: Type.Number(),
        y: Type.Number()
      }),
      response: {
        200: Type.String()
      }
    }
  },
  (req, res) => {
    const { x, y } = req.body

    res.send('hello')
  }
)
```

## Inferred Handlers

In instances where you do want to infer the parameters for external handler, you will need to pull the schema of the route so it can be seen by the external handler. The following sets up the `FastifyRequestInferred` type to infer request parameters for the route, allowing the `request.body` to be inferred.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAKFCRYcAGKMKMYHlQAaROMnTZAJQwBHAK4YpCiVJmp1YevLgAJCBADWFxtQAm9DFAAiEahjFa60z-rKRmiYAAqEAG7Ajq6BhrIAyrQAFhggjDj4hMQkeEGygsLQ8EghGABCfGXhEFExUJkERKRkefGo7JwAtGCR0a5dHJg8-AICrKxwXdMzs3PzC4tLy8vjkwYqqHDq2rrwAJLUeK5QGI5rUytX1zc3Yxi8IvBDWBtGOzpSh8dQp44APAI4HAanVXHAHjAME4KEp2tU+vUFEC4ElUukIbwoTC4Zs0WlGAIAHxwAC8uPemk+MH+CGwCgc5kZCnx6QUoP6UCJYwml1u-IFtwuAFEsa5qIx6KiUgS4BAuBRXBFGFwXHAYBA4MkHM5wTq4IQtFCLoLTWbFmNaJ4pNL0RlyQgUTxHKgAFwoTgAOgA8lwAFYYWgwAAUjuBwN47rKnoAcloQFxXMGAJRyFHAt0ezCx+OJqAplHYVMo04USDURXusPhgBMAAY61GvQkYFAaABzAvA7ACHsm80D80i3iMcAufuDyf8sZ4XxB4CeODfE5nexOFz5067KTut5qKl7Ze-M7-MqVXgI2qchQvCB4W0EokKU6mTN74wYV8KRyeDDuqy2GuuruL+Ph+Au1DJogKJWhWJRwLwChbLg5JbtSnrOlscC8pK9AQAA7mcvZjO+KaevhwAwMkl5glAp6cOeNGckSZGQFIwYkKwJBpsC1bAp4Hx7O6R5-EBG48eGFAyuk7qsowEn0iiwZbs+uhQaSJJ8XAsE2kgiFwMhZIGpoGEQC6YzhsZFCeoqTgcak9B4SQyaFgIyZAA)

```typescript

// -----------------------------------------------------------------
// Fastify Request Inferred
// -----------------------------------------------------------------

export type FastifyRequestInferred<
  Provider extends FastifyTypeProvider, 
  Schema extends FastifySchema
> = FastifyRequest<{}, any, any, Schema, Provider>

// -----------------------------------------------------------------
// External Schema observable to handler and route
// -----------------------------------------------------------------

const Schema = {
  body: Type.Object({
    x: Type.Number(),
    y: Type.Number()
  }),
  response: {
    200: Type.String()
  }
}

// -----------------------------------------------------------------
// Example
// -----------------------------------------------------------------

function InferredHandler(request: FastifyRequestInferred<TypeBoxTypeProvider, typeof Schema>, reply: FastifyReply, done: HookHandlerDoneFunction) {
  const { x, y } = request.body  // allowed
}

Fastify().withTypeProvider<TypeBoxTypeProvider>().post('/',
  {
    onRequest: InferredHandler,
    schema: Schema,
  },
  (req, res) => {
    const { x, y } = req.body

    res.send('hello')
  }
)
```
At this stage, there is still a requirement to setup the appropriate types to allow type provider generics to propagate for inference, so setting up custom generics can be necessary when using type providers in this way. I think there may be some upstream considerations going into making it a little bit easier to create types where needed (possibly provided as new utility types, or possibly a refactor for Fastify v5, see issue https://github.com/fastify/fastify/issues/4081).

Hope this helps!
S
