### ISSUE TITLE
Potential issue with validation

### ISSUE THREAD

**Issue by TheSinding** [fastify/fastify#4160]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.3.0

### Node.js version

16.15.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

newest

### Description

This is not a direct bug of fastify, but more a issue with the default configuration of Ajv.
The bug lies in the Ajv library, but because Fastify uses the `removeAdditional: true` it "enables" the bug in the validation.

`removeAdditional` will make the validation/Ajv behave in a potentially undesirable/unexpected way. 

The issue occurs when you use any of the `oneOf`, `anyOf` & `allOf` in combination with `additionalProperties: false` that is in the JSON schema spec.

Take this example schema 
```json
{
  "type": "object",
  "additionalProperties": false,
  "required": [
    "foobar"
  ],
  "properties": {
    "foobar": {
      "anyOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "name"
          ],
          "properties": {
            "name": {
              "const": "foo",
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "name",
            "baz"
          ],
          "properties": {
            "name": {
              "const": "bar",
              "type": "string"
            },
            "baz": {
              "type": "boolean"
            }
          }
        }
      ]
    }
  }
}
```

You would expect that the following two object would pass
```json
{
    "foobar": {
        "name": "foo"
     }
}

{
    "foobar": {
        "name": "bar",
        "baz": false
     }
}
```

But the last object fails because Ajv uses the first "object" of the anyOf in the schema and then removes the additional properties. Resulting in a failed request.

# Conclusion

This makes the validation of Fastify behave in a way which does not conforms to the specifications of JSON schemas and potentially confuses the developer. 

Now I know this is not a bug in the Fastify codebase persay, but I'm raising the question if the `removeAdditional` property should `true` by default, when it makes the validation behave in a non-standard way.

~~I will also report this as a bug in Ajv's repo.~~ I wont see [here](https://ajv.js.org/guide/modifying-data.html#removing-additional-properties)

---

### Steps to Reproduce

```javascript
const fastify = require("fastify");

const instance = fastify({ logger: true });

const body = {
	type: "object",
	additionalProperties: false,
	required: ["foobar"],
	properties: {
		foobar: {
			anyOf: [{
				type: "object",
				additionalProperties: false,
				required: ["name"],
				properties: {
					name: { const: "foo", type: "string" }
				}
			},
			{
				type: "object",
				additionalProperties: false,
				required: ["name", "baz"],
				properties: {
					name: { const: "bar", type: "string" },
					baz: { type: "boolean" }
				}
			}]
		}
	}
}

instance.post("/foo", { schema: { body } }, (_, reply) => reply.send("ok"))
instance.listen({ port: 3030 }, (err) => {
	if (err) console.error(err);
})
```

### Expected Behavior

The anyOf is respected

**Comment by climba03003** [comment]
I think it is why the options `ajv.customOptions` exists.
Default options may not be good enough or satisfy all the people needs.

**Comment by TheSinding** [comment]
Yes, I just found that.

Now I would argue that it should off by default then, due to the fact it creates unexpected behaviors compared to what you would expect out the JSON schema you put in.

**Comment by climba03003** [comment]
>  Now I would argue that it should off by default then, due to the fact it creates unexpected behaviors compared to what you would expect out the JSON schema you put in.

So far, it is the first complain I see on this unexpected behavior.
My application actually heavily rely on the `removeAdditional` options.
From my point of view, I want to accept more request as possible (even through user data may not be correct as first place, e.g. extra properties or wrong types.)

**Comment by TheSinding** [comment]
Then your application is a good example on why the `ajv.customOptions` exists.

I would still argue that the validation should by **default** adhere to what the actual specification of the JSON schemas, and not have unexpected behaviors which deviates from the official specifications

**Comment by climba03003** [comment]
I would just ask for others opinion on this. cc @fastify/core 

I have no personal preference on it. I only think that it is useful by default, but I am also fine to use custom option and enable the behavior.

**Comment by TheSinding** [comment]
Yes, it's not that I don't see it as useful by default - I can understand why it was on in the first place. 
And I'm not trying to say you the in the wrong :) 

I just think that when it essentially makes `anyOf`, `allOf` and `oneOf` unusable in common cases where you would expect it to work, because it's in the documentation of JSON Schemas, then it shouldn't be on by default.

**Comment by climba03003** [comment]
> I just think that when it essentially makes anyOf, allOf and oneOf unusable in common cases where you would expect it to work, because it's in the documentation of JSON Schemas, then it shouldn't be on by default.

It is something that can be documented, if we plan to continue make it by default.
I believe `JSON Schema` is dynamic enough to write workaround schema in this area.

**Comment by mcollina** [comment]
Unfortunately `removeAdditional` is an important safety measure to protect against malicious inserts of data inside databases, as well as unexpected query params and similar problems. We won't change the default.

**Comment by mikicho** [comment]
@mcollina, why is `removeAdditional` preferred over the default behavior of AJV, which fails the request if it contains extra properties? As I understand it, the potential risk comes from not having `additionalProperties: false`, rather than whether or not we remove these extra properties.

One option to address this security concern might be to integrate the behavior of the[ `fastify-no-additional-properties`](https://github.com/greguz/fastify-no-additional-properties) plugin into Fastify. However, I'm not sure I would recommend this, as it could potentially cause some intersection issues, as noted in this issue on the `typebox` repository: https://github.com/sinclairzx81/typebox/issues/114.

**Comment by mcollina** [comment]
I would be happy to ear about an alternative way to achieve the same result.

**Comment by mikicho** [comment]
@mcollina what is the desirable result? not let additional properties slip into the handler? ajv default configuration will do the job and throw an appropriate error.

**Comment by climba03003** [comment]
`remove` is better than `throwing` because it can accept as most of the requests. Some mistake wouldn't be the problem of the user.

For example, people tends to use the result of `GET` and mutate that object than pass it to `PUT`.
But somehow, `PUT` only allow certain properties. In this case, throwing is not a desire behavior.

**Comment by mikicho** [comment]
@climba03003, on the other hand, ignoring extra properties confuses the clients because they may expect the server to do something, and the server ignores part of their request.
IMO this is a good reason to deviate from the default configuration.

**Comment by climba03003** [comment]
> on the other hand, ignoring extra properties confuses the clients because they may expect the server to do something, and the server ignores part of their request.

Expect to do what? I don't think most of the server do anything when there are extra properties. Non of the public API as I can see.

Most of the common behavior would be ignore.

**Comment by mcollina** [comment]
> @mcollina If the desired result is to prevent additional properties from being included in the handler. The default configuration of AJV should be able to handle this and throw an appropriate error if any additional properties are present.

The default configuration of Ajv let those pass.

**Comment by mikicho** [comment]
@mcollina Maybe they changed the default behavior? Because it seems like the default behavior is that additional properties isn't valid:
https://codesandbox.io/s/ajv-playground-forked-518bjl?file=/src/index.js
![image](https://user-images.githubusercontent.com/11459632/209410416-89c5c683-0c27-42d8-9360-572251258bea.png)

**Comment by mcollina** [comment]
The problem is when `additionalProperties` is not specified.

**Comment by mikicho** [comment]
When `additionalProperties` isn't specified, the current configuration (`removeAdditional: true`) won't help either.
Only `removeAddtional: all` removes additional properties even where `addtionalProperties` isn't specified, but as said in this thread, it causes some unexpected behavior ([ajv docs](https://ajv.js.org/guide/modifying-data.html#removing-additional-properties))
![image](https://user-images.githubusercontent.com/11459632/209411097-c55d5bee-320e-4b63-9622-537059b516be.png)
![image](https://user-images.githubusercontent.com/11459632/209411254-0547f215-9239-4098-9664-73600f57db12.png)

**Comment by metcoder95** [comment]
Adding my smaller two cents here... I'm really aligned with @climba03003's standpoint.

>@climba03003, on the other hand, ignoring extra properties confuses the clients because they may expect the server to do something, and the server ignores part of their request.
IMO this is a good reason to deviate from the default configuration.

The argument you're describing here highlights more a misconception of the users of a given API rather than a _tooling_ problem. As if users of the API expect the service to do something with the extra properties that are not defined in a given contract (e.g. documentation), then the API is having a risk of being misused leading to unexpected problems and undesired behaviors.
This is rather a design problem of the API itself, **not the tooling**.

The service should receive and react accordingly to its proposed contract.

Secondly, as from the documentation:
> Fastify's [baseline ajv configuration](https://github.com/fastify/ajv-compiler#ajv-configuration) is:
>
>```js
>{
>  coerceTypes: true, // change data type of data to match type keyword
>  useDefaults: true, // replace missing properties and items with the >values from corresponding default keyword
>  removeAdditional: true, // remove additional properties
>  // Explicitly set allErrors to `false`.
>  // When set to `true`, a DoS attack is possible.
>  allErrors: false
>}

>This baseline configuration can be modified by providing [ajv.customOptions](https://github.com/fastify/fastify/blob/4bde0e0b259b8df6495ae93c91e066>15b61be9c6/docs/Reference/Server.md#factory-ajv) to your Fastify factory.
>

The configuration is aimed to reduce possible security risks and provide a baseline for further extension. That **does not mean you should stick to the default configuration**.

As is highlighted by the suggestions you are providing, we are suggesting a change based on a subsection of the user base, which can have really not-so-good effects and does not cover all the thinking of the community, as the options are almost breaking in all the cases.

IMHO, the documentation is clear enough to state the consequences and intentions of the current choices, and are also clear stating that you have the option of customise it based on your needs. It should be up to each developer/engineer/user to be cautions and responsible to how it defines and manages its schemas based on the validation/serializer utility is using.

**Comment by mikicho** [comment]
> The configuration is aimed to reduce possible security risks and provide a baseline for further extension

But as shown in my previous comment, the current (Fastify) default behavior **doesn't** reduce the security risks, this is actually how I came across this discussion. I saw in my server properties I didn't expect because I forgot to set `additionalProperties: false`.

> we are suggesting a change based on a subsection of the user base,
I argue that current Fastify's default takes into account a subsection of the user base. for what reason we deviate from AJV's default? the current configuration solves nothing, contrary to `remoevAddtional: 'all' which reduces the risk.

**Comment by climba03003** [comment]
>  the current (Fastify) default behavior doesn't reduce the security risks

It is partially correct. Most of the user use a schema builder for constructing `JSON schema` (No survey for the conclusion but from looking at the issue amount and Discord.js channel.). AFAIK, most of them provide `additionalProperties: false` by default.

Not trying to blame user that write schema manually, but human typing always prone to error (e.g. typo).

> removeAddtional: all

Which would be too strict as a `default`.

**Comment by mikicho** [comment]
> AFAIK, most of them provide additionalProperties: false by default.

TypeBox doesn't ([this is why](https://github.com/sinclairzx81/typebox/issues/114)), what builder are you using maybe I'll migrate.

> Which would be too strict as a default.

My point is that `removeAddtional: true` or `removeAddtional: false` isn't matter to our question. both wouldn't protect the user if he/she forgets to add `additionalProperties: false` so why change the default behavior in the first place? 

> Which would be too strict as a default.

I agree, this is why I won't recommend this.

**Comment by climba03003** [comment]
> What builder are you using maybe I'll migrate.

Hmm, I am using TypeBox. Seems like I am wrong with this one.
Just scan through my code. I did indeed provide all `additionalProperties: false` myself.

I just search around a bit. 

Provide by default.
https://github.com/serafin-labs/schema-builder

Something that provide an API to generation. For example, CLI options, `.addtionalProperties` API.
https://www.npmjs.com/package/ts-json-schema-generator
https://github.com/YousefED/typescript-json-schema
https://github.com/fastify/fluent-json-schema

It latter do reduce typo error.

> why change the default behavior in the first place?

Your argument is like "It does not protect all the case, so it is not a good default". 
But in fact, when it cover it's own use-case (with respect to JSON schema), it should be a good default.

I agree it should be a default not only because of `Security` but it reduce works to pick up the appropriate properties and allow most of the incoming request not to be rejected.
As the initial conversation to the author, I am fine to customize the option myself if the default changes. But, I do not see any value to revert back to `false` in current case.

**Comment by gurgunday** [comment]
No opinions, just pointing out that when using serialization, only what's specified is sent back and everything else is discarded. Isn't `removeAddtional: 'all'` the logical equivalent to this behavior?

**Comment by rluvaton** [comment]
> why is `removeAdditional` preferred over the default behavior of AJV, which fails the request if it contains extra properties?

I agree with @mikicho

Another problem that rise when removing additional or even accepting the data is this scenario:

We have some API that execute some action
The user has `force` in the body for example which doesn't exist
If we ever wanna add `force` property it will change what the user wanted as up until that point it did 1 and know it does 2


**Another scenario:**
Client has a typo in the property, if that property is not mandatory the server may do different thing
