### ISSUE TITLE
hasRoute causes infinite loop 

### ISSUE THREAD

**Issue by matthyk** [fastify/fastify#4319]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.7

### Node.js version

16.14.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.13.1

### Description

If you want to add a route in an `onRoute` hook function and before you check if this route already exists with the new `hasRoute`method, then you will be stuck in an infinite loop, calling the `onRoute` hook over and over again.

### Steps to Reproduce

```js
const Fastify = require('fastify')

const app = Fastify({ logger: true })

app.addHook('onRoute', function (routeOptions) {
  const { url, method } = routeOptions

  if (!this.hasRoute({
    url,
    method,
    constraints: {
      host: 'fastify.io'
    }
  })) {
    this.route({
      url,
      method,
      constraints: {
        host: 'fastify.io'
      },
      handler: () => {}
    })
  }
})

app.get('/test', () => {})

```

### Expected Behavior

The `onRoute` hook should be called only one more time for the route added in the hook method.

**Comment by Uzlopak** [comment]
I implemented hasRoute. hasRoute uses find-my-way and does not call any fancy stuff from fastify.

Imho this infinite loop is not because hasRoute but the call to this.route(). route() adds a new route thus invoking the onRoute hook. onRoute-hook is called before adding the route to the router, as the onRoute-Hook can be used to modify the routeOptions before adding the route to the router.

Thus said, it would make sense to add a key to the custom attribute of the routeOptions and check if that was set and if so skip adding the route.

Not tested but you should get the idea:
```js
const Fastify = require('fastify')

const app = Fastify({ logger: true })

const kRouteAlreadyProcessed = Symbol('route-already-processed')

app.addHook('onRoute', function (routeOptions) {
  const { url, method } = routeOptions

  const isAlreadyProcessed = routeOptions?.custom[kRouteAlreadyProcessed] || false

  if (isAlreadyProcessed === false && !this.hasRoute({
    url,
    method,
    constraints: {
      host: 'fastify.io'
    }
  })) {
    this.route({
      url,
      method,
      constraints: {
        host: 'fastify.io'
      },
      custom: {
        [kRouteAlreadyProcessed]: true
      },
      handler: () => {}
    })
  }
})

app.get('/test', () => {})
```

**Comment by mcollina** [comment]
This behavior seems correct. I'm not 100% sure we can prevent this somehow: @Uzlopak could you take a look?

**Comment by Uzlopak** [comment]
@mcollina 

The only idea I have is to add a "shadowRouter" which gets initialized next to the real router and gets the routes added before calling the onRoute-hook. And use the "shadowRouter" instead of the real router to determine if the route has been added or not. Because the routeOptions can be manipulated by the onRoute-hook we need to keep the original routeOptions before the onRoute-hook-call and check if methods, path and constraints are still the same after we called the onRoute-hook, and if not remove the route from the shadowRouter based on the original routeConfig and add it back to the shadowRouter with the modified routeOptions.

Or we use the real router but implement the above mentioned logic of adding and removing the route before calling onRoute.

I have the feeling that both could slow down the startup time. But that is basically the only idea, where I would say, that it would solve that issue 100%.

**Comment by omarish** [comment]
We ended up solving this by adding this immediately before `fastify.ready()`:

```ts
  fastify.register(async function (instance) {
    for (const [route, handlers] of instance.routes) {
      for (const handler of handlers) {
        if (!handler.url.endsWith('.json')) {
          const urlWithJSONExtension = `${handler.url}.json`

          if (
            !instance.hasRoute({ method: handler.method, url: urlWithJSONExtension })
          ) {
            instance.log.info(`Also adding alias route ${urlWithJSONExtension}`)
            instance.route({
              ...handler,
              url: urlWithJSONExtension,
              schema: {
                ...handler.schema,
                hide: true,
              },
            })
          }
        }
      }
    }
  })
```
