### ISSUE TITLE
preParsing is undefined not null

### ISSUE THREAD

**Issue by tuonidaici** [fastify/fastify#4511]
fastify version  v4.11
        "@fastify/cors": "8.2.0",
        "@fastify/csrf-protection": "6.1.0",
        "@fastify/swagger": "8.2.1",
        "@fastify/swagger-ui": "^1.3.0",
        "body-parser": "1.20.1",
        "cos-nodejs-sdk-v5": "2.11.19",
        "cron": "2.2.0",
        "fastify": "4.11.0",
        "fastify-file-upload": "4.0.0",
        "fastify-plugin": "4.4.0",

![1673539895600](https://user-images.githubusercontent.com/37258529/212120665-01b710b1-57e3-4f2b-abdd-7fc1ed78d49d.jpg)
<img width="540" alt="1673539789448" src="https://user-images.githubusercontent.com/37258529/212120671-6d79646d-37ac-4c06-99f6-fabbf8b2a7af.png">
<img width="761" alt="1673539770559" src="https://user-images.githubusercontent.com/37258529/212120680-bf988ec4-551a-4384-a660-87f079e8d3cd.png">

**Comment by jsumners** [comment]
Please provide a minimal reproduction. This collection of screenshot is nonsensical.

**Comment by kosl90** [comment]
This happens to me as well, but it is not fastify's bug as I know. I will show you my case.

1. fastify version v4.13
2. **use fastify-cli to start the server.**
3. use schema in the code.

the server crashes when the schema compiles error:
![image](https://user-images.githubusercontent.com/1311476/222616237-2f82eff8-4b4d-4214-a668-9410727109e3.png)

However, `fastify start` shows nothing:
![image](https://user-images.githubusercontent.com/1311476/222614707-3f4ca213-e0d4-45b8-bc8d-8a8b41da668d.png)

I don't know the reason why fastify-cli does not crash, but it makes `preReady` hook(https://github.com/fastify/fastify/blob/v4.13.0/lib/route.js#L335) to be skipped. It means the lifecycles won't be injected, so that the `preParsing` field in context is undefined instead of null.
![image](https://user-images.githubusercontent.com/1311476/222617446-86dd99cb-fcf7-4256-b444-431f88c52354.png)

I wish this is useful @tuonidaici .

BTW, the `kRequestValidateWeakMap` symbol does not exist in symbols.js. You will see `undefine: null` in a context instance.
![image](https://user-images.githubusercontent.com/1311476/222618575-9aae721d-fd5f-493c-bb50-58501f8aefc5.png)

It runs good so far, but I think it's a bug :P @jsumners

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Eomm** [comment]
> BTW, the kRequestValidateWeakMap symbol does not exist in symbols.js. You will see undefine: null in a context instance.

This is dangerous - why did the linting not warn us?
For sure we must fix it!

**Comment by tuonidaici** [comment]
this question maybe schema cause ,  i delete schema.response and schema.body  this program  is running success

**Comment by kosl90** [comment]
@mcollina here is the example, you can try it. https://github.com/kosl90/fastify-cli-not-crash-example

**Comment by mcollina** [comment]
This is fixed in v4.14.1.

**Comment by mcollina** [comment]
@kosl90 you might want to open a different issue for your case. I think you have found an odd problem of passing a callback to `fastify.ready()` that is letting you start an application with errors.
