### ISSUE TITLE
req.getValidationFunction() not working

### ISSUE THREAD

**Issue by cibilex** [fastify/fastify#4617]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.14.1

### Plugin version

1

### Node.js version

16.14.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

cat /etc/os-release

### Description

req.getValidationFunction() not working as excepted.
```js
    app.route({
        method: 'GET',
        url: '/',
        handler: (req, res) => {
            const validate = req.getValidationFunction({
                    type: 'object',
                    properties: {
                        foo: {
                            type: 'string'
                        }
                    }
                })
            console.log(validate({ foo: 'bar' }))
            res.send('hi')
        },
    })
```
and this is the response:
```js
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "validate is not a function"
}
```

### Steps to Reproduce

here is how looks my request

```
GET   http://localhost:8000/
content-type: application/json

```

### Expected Behavior

It must write to console "false" .

**Comment by metcoder95** [comment]
Hey! This is a wholly expected behavior. The function does not compile any validation function but instead does a lookup and returns the validate function if there's a match or `undefined` otherwise (ref: https://www.fastify.io/docs/latest/Reference/Request/#getvalidationfunctionschema--httppart).

If you want to compile the validation function and validate at the same time you can use `validateInput` instead. See https://www.fastify.io/docs/latest/Reference/Request/#validateinputdata-schema--httpstatus-httpstatus

**Comment by cibilex** [comment]
> Hey! This is a wholly expected behavior. The function does not compile any validation function but instead does a lookup and returns the validate function if there's a match or `undefined` otherwise (ref: https://www.fastify.io/docs/latest/Reference/Request/#getvalidationfunctionschema--httppart).
> 
> If you want to compile the validation function and validate at the same time you can use `validateInput` instead. See https://www.fastify.io/docs/latest/Reference/Request/#validateinputdata-schema--httpstatus-httpstatus

**Thanks** a lot ,It my fault
