### ISSUE TITLE
[Docs] Add network configuration for AWS EC2 to docs and README

### ISSUE THREAD

**Issue by Creative-Difficulty** [fastify/fastify#4621]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Add the network interface configuration required for deployment on AWS EC2 instances to the docs & quickstart section on the README (solution found in #2285).

### Motivation

I have been searching for this solution for a very long time. It would be beneficial to the developer experience to add the config options for AWS and other Cloud providers(e.g. Google Cloud, Microsoft Azure) into the docs and README.

### Example
Taken from the README quickstart section:
### Example

```js
// Require the framework and instantiate it
// ESM
import Fastify from 'fastify'
const fastify = Fastify({
  logger: true
})
// CommonJs
const fastify = require('fastify')({
  logger: true
})
// Declare a route
fastify.get('/', (request, reply) => {
  reply.send({ hello: 'world' })
})
// Run the server!
// Note: for AWS use: fastify.listen({ port: 3000 }, "0.0.0.0", (err, adress) => { if(err) throw err });
fastify.listen({ port: 3000 }, (err, address) => {
  if (err) throw err
  // Server is now listening on ${address}
})
```

with async-await:

```js
// ESM
import Fastify from 'fastify'
const fastify = Fastify({
  logger: true
})
// CommonJs
const fastify = require('fastify')({
  logger: true
})
fastify.get('/', async (request, reply) => {
  reply.type('application/json').code(200)
  return { hello: 'world' }
})
// Note: for AWS use: fastify.listen({ port: 3000 }, "0.0.0.0", (err, adress) => { if(err) throw err });
fastify.listen({ port: 3000 }, (err, address) => {
  if (err) throw err
  // Server is now listening on ${address}
})
```

**Comment by jsumners** [comment]
There's nothing special about the environments mentioned. They are virtual machines / Docker instances just like any other. We very clearly highlight that you should give thought to the interfaces you choose to listen on in all of the documentation:

1. https://www.fastify.io/docs/latest/Reference/Server/#listen
2. And the docs you reference instruct you to read the Getting Started guide for more information. That guide says:
https://github.com/fastify/fastify/blob/eafeed737f5e753b0d2fbf33e68a995d3149b769/docs/Guides/Getting-Started.md?plain=1#L98-L119

Additionally, your suggested fix is incorrect. You should provide the host via:

```js
fastify.listen({ port: 3000, host: '0.0.0.0' })
```

I'm completely onboard with improving the documentation. However, I do not think the suggested improvements are in the appropriate place. We don't need to call out "for AWS" in a random comment in the README. The issue is not specific to some non-specific "AWS" (AWS itself is not a sufficient qualifier for the environment).

**Comment by Creative-Difficulty** [comment]
Ok
