### ISSUE TITLE
Error: Schema for validaton is undefined

### ISSUE THREAD

**Issue by c0sx** [fastify/fastify#4634]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.15.0

### Node.js version

any

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

4.15 release have a backward compatibility issue ([PR](https://github.com/fastify/fastify/pull/4620)): it throws an error if schema for validation is undefined. 

For example, we get a schemas and pass them to fastify.

```ts
const { headers, body } = getSchemas();

fastify.post('/', {
  schema: {
    headers,
    body
  }
}
```

### Steps to Reproduce

```ts
const fastify = require("fastify")({ logger: true });

fastify.get(
  "/",
  {
    schema: {
      headers: undefined,
    },
  },
  () => {
    return "hello";
  }
);

const start = async () => {
  try {
    await fastify.listen({ port: 3000 });
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};

start();
```

Server throws an error `Failed building the validation schema for GET: /, due to error headers schema is undefined"` when started

### Expected Behavior

I think that `undefined` is acceptable value, which means that validation will be skipped.

**Comment by mcollina** [comment]
@Eomm I think we should revert https://github.com/fastify/fastify/pull/4620, and possibly undo that for v5.

**Comment by Eomm** [comment]
I added that fix because I had undefined schemas and all was working fine. 

I tested what I was going adding into the db and I spot additional fields that was unexpected.. Then a debug session pointed me to a typo! 

I'm sure out there there are a lot of typos and developers that think to have set a validation schema.. But they are not!

I think that setting a schema as undefined is a "don't care" action. Do not add the property if you don't want the schema instead.

**Comment by Eomm** [comment]
I like the @climba03003 proposal as mediation 👍

Even though I think an error shows a real security issue tbh

**Comment by Eomm** [comment]
> More specifically, undefined is not returned when rendering JSON, so its presence should be "neutral". I would still throw for null.

The logic is: if de dav has set the property field (`body`, `headers` etc..) the value must not be falsy. I don't think the rendering json is a thing here, a human has written `body: fastify.getSchema('typo')` and the endpoint does not run the validation.

> This change was about type system and contracts, but not about security. You're trying to shift the user's responsibility on library level.

Absolutely yes, it is both. Security because an endpoint must validate its input and because the framework must help the dev and understand clearly unwanted behaviour: why a developer should write `body: undefined`?

I mean, you need to change it to this code to make it optional:

```
{
  schema: {
    ...(bodySchema? { body: bodySchema }: null )
  }
}
```

This will not add the `body` when the `bodySchema` does not exist

**Comment by franher** [comment]
Hello all,

I think https://github.com/fastify/fastify/pull/4620 caused a breaking change for me too.

We have `schema.headers` as undefined in several OpenAPI schemas. Is it an unexpected breaking change that has landed in a minor version, v4.15.0?

**Comment by climba03003** [comment]
> Is it an unexpected breaking change that has landed in a minor version, v4.15.0?

Throughout the conversation, we should change the `Error` to `Warning` first.
Would you like to work on this?

**Comment by franher** [comment]
> > Is it an unexpected breaking change that has landed in a minor version, v4.15.0?
> 
> Throughout the conversation, we should change the `Error` to `Warning` first. Would you like to work on this?

Sure, @climba03003. I think this is an excellent opportunity for me to become a Fastify contributor.

**Comment by Eomm** [comment]
> Should I use this?

Yes, so it can be tested easily as well

**Comment by franher** [comment]
> > Should I use this?
> 
> Yes, so it can be tested easily as well

Thank you for the feedback, @Eomm. I'm working on it today! stay tuned :P
