### ISSUE TITLE
Package Manager CI Failing with PNPM 8

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify#4724]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Bumped pnpm to use v8 in package manager CI workflow, however it is now failing when ran. ☹️

Cant see any breaking changes that would affect this in the v8 release notes: https://github.com/pnpm/pnpm/releases/tag/v8.0.0

**Comment by Fdawgs** [comment]
> Where's a link to one of the failures? Are you sure it's not the big leading headline about Node 14 not being supported?

Whoops, https://github.com/fastify/fastify/actions/runs/4862202962

Node 14 is included separately and still uses PNPM 7 in the workflow.

**Comment by jsumners** [comment]
This reproduces locally:

```sh
$ n lts
$ node --version
v18.16.0
$ pnpm --version
8.4.0
$ npm --version
9.5.1
$ rm -rf node_modules && pnpm i
$ tap -R terse --cov --coverage-report=lcovonly
# failure
$ rm -rf node_modules && npm i
$ tap -R terse --cov --coverage-report=lcovonl
# success
```

Maybe @zkochan has an idea?

**Comment by Fdawgs** [comment]
Seems to be a similar issue with https://github.com/fastify/fastify-diagnostics-channel/actions/runs/4859619462 as well

**Comment by zkochan** [comment]
You need to update the version ranges in your `package.json`. pnpm v8 resolves direct dependencies to the lowest supported versions. This clearly catched an issue in your case because your project doesn't work with the ranges specified in package.json. Run `pnpm update` to update the ranges. Or set `resolution-mode=highest` for the old behavior.

**Comment by jsumners** [comment]
> pnpm v8 resolves direct dependencies to the lowest supported versions.

This is very strange and seems counter to the semver qualifiers specified. `^1.2.0` means "at least 1.2.0 but not 2.0.0". It does not mean "1.2.0 even if 1.15.6 exists".

**Comment by zkochan** [comment]
The question is why do you have versions in your `package.json` that don't work with your tests?

**Comment by jsumners** [comment]
> The question is why do you have versions in your package.json that don't work with your tests?

I disagree. The issue you linked described the reason for the semver qualifiers: packages get updated to fix bugs and security issues that don't change the API but _do_ affect the functionality (i.e. correct the functionality to the intended behavior). We rely on the longstanding behavior of package managers to honor the semver qualifiers in order to 1. fix bugs and 2. not have to churn the core framework's version numbers. 

@fastify/core I'm not sure what we want to do here. The easy answer is to add an env var to our CI (assuming pnpm supports that) to restore the previous behavior. But that won't replicate the most likely usage in the wild.

**Comment by climba03003** [comment]
> I'm not sure what we want to do here. The easy answer is to add an env var to our CI (assuming pnpm supports that) to restore the previous behavior. But that won't replicate the most likely usage in the wild.

I would just drop `pnpm` support since it doesn't meet most people expectation.
It is blaming on the library maintainer on the support range, even if we do anything correct.

`pnpm` is missing one point, when people using a library that stable enough and without update for a long time (let say 1 year). But it's dependency has `bug or vulnerability` update, the user will never been able to install the latest version.
It completely create a more serious supply chain attack.

**Comment by zkochan** [comment]
Why do you ignore the valid issues that I am stating and blaming pnpm in non-standard behaviour?

The ranges in your `package.json` suggest that your library should work with any version matching the range. If your tests fail with a version matching the range it means that some of the dependency specs should be updated. This resolution mode literally found an issue (unless the update needs to be done in a dev dependency).

I repeat, this issue will happen to users that use offline install with old cache. Or when the package manager will deduplicate dependencies and the deduplication will choose an older version. It may happen with any package manager, not just pnpm.

> It is blaming on the library maintainer on the support range.

And you are blaming pnpm for installing dependencies that are supported by your project.

**Comment by mcollina** [comment]
Having the package managers change the way they resolve versions creates more problems for the ecosystem than whatever reason why you are doing this.

> The ranges in your package.json suggest that your library should work with any version matching the range. If your tests fail with a version matching the range it means that some of the dependency specs should be updated. This resolution mode literally found an issue (unless the update needs to be done in a dev dependency).

Unfortunately, this is impossible and unfeasible to guarantee: at a first glance, the number of permutations is factorial (`n! (n−r)!`). In order to guarantee that my module works with that version range, I would need to test all possible permutations of the dependency versions. Given the number of dependencies of any modern library, this is unfeasible, and I don't understand why you recommend this behavior. Note that having a lock file hides the problem, but it does not solve it.

Given the number of security vulnerabilities in the ecosystem, I think pnpm behavior is _unsafe_, as you'd likely install vulnerable software when patches are available. 
I'll open an issue in that regard on the pnpm tracker as I think this is not the current venue to discuss.

**Comment by climba03003** [comment]
> someone removed my message? I thought I already posted a link to it

No one removed your message, you are reference from that issue to here.

> The solution would be to install the highest version and update the specs in package.json

Fresh installation with `highest` would meet most user expectation.
Later on, `lock file` do it's own job to prevent wrong version being installed.
