### ISSUE TITLE
creating multipleBindings function does not catch/handle errors

### ISSUE THREAD

**Issue by ivan-tymoshenko** [fastify/fastify#4730]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

One of the multiple ways to reproduce it:

```js
'use strict'

const http = require('http')
const fastify = require('fastify')

let counter = 0
const serverFactory = (handler, opts) => {
  if (++counter > 1) {
    throw new Error('kaboom')
  }

  const server = http.createServer((req, res) => {
    handler(req, res)
  })

  return server
}

const app = fastify({ serverFactory })

async function main () {
  try {
    await app.listen()
  } catch (err) {
    console.log(err)
  }

  await app.close()
}

process.on('uncaughtException', (err) => {
  console.log('uncaughtException', err)
})

main()

```

The reject is ignored [here](https://github.com/fastify/fastify/blob/dc87e008652f2b2bd1c0e55dab40a29904da2f15/lib/server.js#L90)

**Comment by metcoder95** [comment]
Not same issue, but maybe similar feeling to #4725 🤔

**Comment by ivan-tymoshenko** [comment]
Only because I'm working with a `serverFactory` for the [@fastify/restartable](https://github.com/fastify/restartable), internally, these are two different problems. The error in this issue might be thrown not only from the serverFactory but from any place inside the `multipleBindings` function.

**Comment by metcoder95** [comment]
It is perceptually different that's true, but they share the same essence.

The `multipleBindings` function is designed to swallow the errors as failing to instantiate the secondary server should not block the app from running if the primary server is already listening. It catches and swallows the errors that the DNS lookup, `listen` can return, but is true that it does not consider what happens if the `serverFactory` fails, as shown here: https://github.com/fastify/fastify/blob/dc87e008652f2b2bd1c0e55dab40a29904da2f15/lib/server.js#L141C45-L147

**One option** can be to just be surrounded by a `try/catch` and ignore the error (maybe print a log?).
And the **second one** (at least that I can think of) it is just to ignore the secondary binding when a custom `serverFactory` is provided.

Weighting between the small performance impact at startup that `try/catch` can provide (that it is only done once), with a DX (providing insights that something went wrong), the first option can be a good way to go

**Comment by mcollina** [comment]
I would just ignore the secondary binding if serverFactory is provided.

**Comment by climba03003** [comment]
> I would just ignore the secondary binding if serverFactory is provided.

The problem is more than that.
Even the first server can be passed a `listening` server.

So, I would propose checking `server.listening` property.
1. The first server would throw `error`.
2. The second server would emit `warning`.

In this case, we retain the multiple binding ability for multiple bindings for `serverFactory` **if it generate different server instance**.

**Comment by metcoder95** [comment]
> So, I would propose checking server.listening property.
>
>The first server would throw error.
>The second server would emit warning.
>In this case, we retain the multiple binding ability for multiple bindings for serverFactory if it generate different server instance.

Meanwhile, the proposal fits perfectly for #4725, I think here the range of scenarios is slightly bigger. We need to consider what would happen if e.g. `serverFactory` fails internally due to any reason while instantiating the secondary binding. As not handled, that's what will cause the `uncaughtException`.

We can do a "best effort" and just catch the error to swallow it and continue if the first binding is already done, or just ignore it completely and not create the secondary binding.

We can align it with #4725 in terms of creating a warning that shows the error so users are informed.
