### ISSUE TITLE
`fastify.server.close()` did not behave as expected.

### ISSUE THREAD

**Issue by hienngm** [fastify/fastify#4774]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Node.js version

v16.19.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6

### Description

According to the Node.js documentation:
```typescript
 /**
   * Stops the server from accepting new connections and keeps existing
   * connections. This function is asynchronous, the server is finally closed
   * when all connections are ended and the server emits a `'close'` event.
   * The optional `callback` will be called once the `'close'` event occurs. Unlike
   * that event, it will be called with an `Error` as its only argument if the server
   * was not open when it was closed.
   * @since v0.1.90
   * @param callback Called when the server is closed.
   */
  close(callback?: (err?: Error) => void): this;
```
The callback is supposed to be called when the server is closed. I've already tested it in the NodeJS HTTP server. However, in my case, when I call `fastify.server.close(callback)`, the callback is invoked immediately, and the server is still processing incoming requests instead of being closed. 
> I'm reporting this issue because it breaks some of the shutdown features of `NestJS` (using `Fastify` adapter).

### Steps to Reproduce

```typescript
import Fastify from 'fastify';
const fastify = Fastify();

fastify.get('/', async (request, reply) => {
  await new Promise((resolve) => {
    setTimeout(() => resolve(1), 10000);
  });
  reply.send({ hello: 'world' });
});

setTimeout(() => {
  fastify.server.close((error) => {
    console.log('Server is closed', error);
  });
}, 5000);

// Run the server!
fastify.listen({ port: 3000 }, (err, address) => {
  if (err) throw err;
  // Server is now listening on ${address}
});

```
Start the server and call the API at `localhost:3000`.

### Expected Behavior

The callback is only invoked when the server is actually closed as the original NodeJS HTTP server behaves. 
> I'm reporting this issue because it breaks some of the shutdown features of `NestJS` (using `Fastify` adapter).

**Comment by metcoder95** [comment]
Hey! Thanks for the report 🙂 
The behavior is actually expected, as two things are happening within your example:

1. Once you trigger `fastify.close` it will start rejecting new connections, and wait until the ones that are open get served before closing the server completely.
2. The `close` callback (and its Promise version) are called once all the `onClose` hooks have been successfully called (if any). This is due to `avvio` behavior which is Fastify extends underneath.
>  __From [Avvio's docs](https://github.com/fastify/avvio#close)__: Starts the shutdown procedure, the callback is called once all the registered callbacks with onClose have been executed.

I acknowledge that the current [docs](https://www.fastify.io/docs/latest/Reference/Server/#close) does not explain that small point. Maybe something worth it to mention?

**Comment by hienngm** [comment]
Thank you for your quick response 😄. However, what I meant was `fastify.server.close()` instead of `fastify.close()`. As stated in the Fastify documentation, `fastify.server` returns the underlying Node HTTP server object. Ideally, `fastify.server.close()` should exhibit the same behavior as the raw HTTP server in Node, but it seems to deviate from that behavior which has led to confusion.

**Comment by Eomm** [comment]
In general:

- prefer `fastify.close()` over `fastify.server.close()` as you are skipping some fastify features (such as the `onClose`)
- in an async handler `return reply` instead of `reply.send()`. It is managed, but it may leads to unpredictable bugs

If you run your server with `fastify.listen({ host: '0.0.0.0', port: 3000 }` all will work as expected.

I think this issue is related to the multiple bindings when we listen to both ipv4 and ipv6 ips

```
    // https://github.com/nodejs/node/issues/9390
    // If listening to 'localhost', listen to both 127.0.0.1 or ::1 if they are available.
    // If listening to 127.0.0.1, only listen to 127.0.0.1.
    // If listening to ::1, only listen to ::1.
```
