### ISSUE TITLE
Allow empty responses

### ISSUE THREAD

**Issue by ThatTonybo** [fastify/fastify#4833]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Under the [OpenAPI 3.0 specifications](https://swagger.io/docs/specification/describing-responses/), "Empty Response Body" explains that responses such as 204 No Content can omit the `content` and just have a description. This should be an allowed feature.

### Motivation

This is useful as it covers the full specification.

### Example

I have tried to do this...
```js
{
    schema: {
        ...
        response: {
            204: {
                description: "Session deleted"
            }
        }
    }
}
```
...but it currently errors
```
FastifyError [Error]: Failed building the serialization schema for DELETE: /users/sessions/@me, due to error schema is invalid: data/properties/description must be object,boolean
```
I have to include a `type: "object"` and empty `properties: {}` for it to build. Having only a description should be supported.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by ThatTonybo** [comment]
> Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

I don't have that much experience doing such changes, but I could have a go after I get back from my trip 😅

**Comment by shayff** [comment]
@mcollina May I work on it?

**Comment by Eomm** [comment]
Sure!

**Comment by Eomm** [comment]
Hi @shayff @giuliowaitforitdavide 
I got the time to check deeper this issue and let me write it here instead of on your PRs 🙏🏼 

@SkeLLLa was right. The issue comes from the default `type` assigned to the schema when it is missing:

https://github.com/fastify/fastify/blob/9f005638774b72cce55496c8941e818256e4d3e7/lib/schemas.js#L134-L138

Setting a schema like the one on the first comment, Fastify reads it like this:

```
{ type: 'object', properties: { description: 'Session deleted' } }
```

and it triggers the error.

Now, if we set the route like the following:

```
const fastify = require('./fastify')
const app = fastify()

app
  .register(require('@fastify/swagger'))
  .after(() => {
    app.get('/', {
      schema: {
        response: {
          204: {
            type: 'null',
            description: 'Session deleted'
          }
        }
      }
    }, function (request, reply) {
      console.log(JSON.stringify(app.swagger(), null, 2))
      reply.code(204).send({ hello: 'world' })
    })
  })
  .inject('/', (err, response) => {
    if (err) {
      console.log(err)
    } else {
      console.log(response.payload)
    }
  })
```

all work as expected:

```
{
  "swagger": "2.0",
  "info": {
    "version": "8.8.0",
    "title": "@fastify/swagger"
  },
  "definitions": {},
  "paths": {
    "/": {
      "get": {
        "responses": {
          "204": {
            "description": "Session deleted"
          }
        }
      }
    }
  }
}
null
```

Or with open API 3:

```
.register(require('@fastify/swagger'), {
    openapi: {}
  })

{
  "openapi": "3.0.3",
  "info": {
    "version": "8.8.0",
    "title": "@fastify/swagger"
  },
  "components": {
    "schemas": {}
  },
  "paths": {
    "/": {
      "get": {
        "responses": {
          "204": {
            "description": "Session deleted"
          }
        }
      }
    }
  }
}
null
```

## Now, let's focus on the standard

First issue: Open API is not JSON Schema
Here are some differences: https://swagger.io/docs/specification/data-models/keywords/

They are working together to make them compatible, but we are not at that point, and `@fastify/swagger` does a lot of transformation to make them compatible.

That said, the Fastify route wants a JSON Schema so we must provide it.
If we look at the supported JSON Schema version of `fast-json-stringify` that processes the `response` schemas, we must adhere the DRAFT-7 one:

https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-01#section-6.1.1

> type
> The value of this keyword MUST be either a string or an array.  If it
> is an array, elements of the array MUST be strings and MUST be
> unique.

So, I think a fix is not needed, but a `type: 'null'` must be added to the json schema when a response payload is not expected

**Comment by giuliowaitforitdavide** [comment]
Fair enough. Should we close our PR?

**Comment by Uzlopak** [comment]
But type is not mandatory?!

**Comment by Uzlopak** [comment]
So is it still a good-first-issue or a bug?

Or more like a documentation issue?

**Comment by Eomm** [comment]
I was waiting for a @ThatTonybo feedback tbh

Closing due the analysis I have done
