### ISSUE TITLE
coverage workflows

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify#4887]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I quiete dont understand why we need the coverage workflows. Why do they even run before we run all the tests specific to the node version and os?

Why cant they run parallel to the specific tests?

**Comment by jsumners** [comment]
1. https://github.com/fastify/fastify/pull/3717
2. https://github.com/fastify/fastify/pull/3719
3. https://github.com/fastify/fastify/pull/3722 (https://github.com/fastify/fastify/issues/3720)

But the short answer is: if the coverage isn't 100%, there's not point in running the full matrix of test suites because the PR needs to improve its testing.
