### ISSUE TITLE
Why I won't switch to Fastify from Express

### ISSUE THREAD

**Issue by DreamwareDevelopment** [fastify/fastify#4933]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

tl;dr: Data serialization/deserialization is too coupled with this framework's implementation.

As described [here](https://github.com/fastify/fastify/blob/main/docs/Reference/ContentTypeParser.md) "Natively, Fastify only supports 'application/json' and 'text/plain' content types. If the content type is not one of these, an FST_ERR_CTP_INVALID_MEDIA_TYPE error will be thrown.". First off, that's a huge limitation for other reasons than the following; It offers no support for binary data serialization/deserialization methods such as Protobuf or Avron. If it doesn't then this is no more than a hobbyist's tool. Engineers must have the flexibility to prioritize performance over usability. Especially since this is considered _more performant than Express_. Fastify was [shown](https://dev.to/samchon/i-made-express-faster-than-fastify-4h8g) to be faster due to a faster JSON serialization algorithm, I'd insist that other points must be highlighted to as to why Fastify is faster than Express outside of serialization/deserialization before you can convince engineers to use this in production grade projects.

I find this whole project to be arrogant in nature and a complete waste of 6 hours of my time of looking into it for a future project.

### Motivation

Constructive criticism

### Example

I would like to use Fastify with a binary serialization protocol. But if there are no other reasons that Fastify is faster than Express then I might as well use Express. Serialization/Deserialization is too tightly coupled to the implementation, so using a binary protocol isn't even an option.

**Comment by mcollina** [comment]
Thanks for your feedback @DreamwareDevelopment.

I want to note a few things:

1. `express` cannot parse JSON out of the box. A middleware must be added to parse JSON: [`app.use(express.json())`](https://expressjs.com/en/api.html). 
2. You can add whatever parsing logic for your content types; it's as easy as calling [`server.addContentTypeParser()`](https://fastify.dev/docs/latest/Reference/Server/#addcontenttypeparser). You can even set up your own serializer, globally or for each route. 
3. Fastify is significantly faster than Express, even without custom JSON serialization. There are infinite conference talks on this topic which a very quick search on google would have turned out. I guess we might want to list them on the website.

I would recommend you to check out our documentation, reach out on Discord, or open an issue in the help repository.

**Comment by DreamwareDevelopment** [comment]
Very good, thanks for the quick response. Sorry for being ill-informed. I'll do more research.

**Comment by Fdawgs** [comment]
Ah shit, guess that web API I built that is used at multiple hospitals across the UK for converting clinical files in multiple binary formats isn't "production grade". My bad.
