### ISSUE TITLE
New Community Plugin: fastify-rabbitmq

### ISSUE THREAD

**Issue by Bugs5382** [fastify/fastify#4995]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I wrote a new plugin for Fastify and RabbitMQ. Still in alpha, but published on the NPM registry with > 94 already weekly downloads.

**Comment by Uzlopak** [comment]
To be honest: 
94 downloads doesnt mean much. I have one package, which I did not promote anywhere and got about the same amount of weekly downloads because other package systems are replicating the the packages from npm.

Also it basically yet another ampqlib wrapper. 

Btw. you should not target ES2015 in your tsconfig. better target node 18. With ES2015 you have no async await support, so your transpiled code has some logic to implement something called __awaiter. Or use the callback way for fastifyPlugin instead of async function, then it wont need the __awaiter.

If you want to add it to the ecosystem, open a PR and add it to Ecosystem.md

Closing this issue as you should anyway prepared a PR against Ecosystem.md.
