### ISSUE TITLE
onReady might be executed twice

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#5049]
If we call `ready()` in parallel, the `onReady` hooks are triggered twice

```js
import fastify from './fastify.js'

const app = fastify()

app.addHook('onReady', async function () {
  console.log('onReady')
})


await Promise.race([app.ready(), app.ready()])

await app.ready()
```

Note that this is also a problem when using `inject()`

**Comment by saikiran76** [comment]
You are correct that calling ready() in parallel can cause the onReady hooks to be triggered twice. This is because onReady hooks are triggered once for each call to be ready().

To avoid this issue, you can use a boolean flag to ensure that the onReady hooks are only triggered once. Here's an example:

`import fastify from './fastify.js'

const app = fastify()

let isReady = false

app.addHook('onReady', async function () {
  if (!isReady) {
    console.log('onReady')
    isReady = true
  }
})

await Promise.race([app.ready(), app.ready()])

await app.ready()
`

**Comment by saikiran76** [comment]
If the above seems it can work, may be I will be able to work on this. @mcollina

**Comment by mcollina** [comment]
Yes... but it's likely going to be more tricky than that example.
