### ISSUE TITLE
handler doesn't exist in routerOptions

### ISSUE THREAD

**Issue by its-dibo** [fastify/fastify#5113]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.0

### Node.js version

18

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22

### Description

[Fastify docs](https://fastify.dev/docs/latest/Reference/Routes/#routes-options) mentioned that you can get the registered handler in onRequest hook by `request.routeOptions.hndler`, but there handler doesn't exist in the typeof `routerOptions`

```
 app.addHook('onRequest', (req, res, done) => {
  // Property 'handler' does not exist on type 'Readonly<RequestRouteOptions<unknown, FastifySchema>>'
    console.log( req.routeOptions.handler);
    done();
  });
};
```

### Steps to Reproduce

.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests (we use `tsd` for types).

**Comment by Uzlopak** [comment]
We expose the handler. Maybe you need to upgrade fastify.
https://github.com/fastify/fastify/blob/9b8a7825dc033887d293549e40284284bf27c5a5/lib/request.js#L193

**Comment by saikiran76** [comment]
To resolve this issue, we can try accessing the handler using req.raw.originalHandler instead.
code:
`app.addHook('onRequest', (req, res, done) => {
  console.log(req.raw.originalHandler);
  done();
});
`

**Comment by Sboonny** [comment]
@Uzlopak, I think the title confused you, the handler isn't typed in the [`RequestRouteOptions`](https://github.com/fastify/fastify/blob/9b8a7825dc033887d293549e40284284bf27c5a5/types/request.d.ts#L23-L34), if I am not wrong and `RequestRouteOptions` is its actual type. It exists, but if you use it in typescript, you will get `any`.

I am wondering if the type is similar to [RouteHandler](https://github.com/fastify/fastify/blob/c3a9f49d534026eb0305c2948a0d99fc05692f96/types/route.d.ts#L162-L175), but `this` is typed as `never`, because trying to access it will break the type? 💭

**Comment by its-dibo** [comment]
Good job @MikeJeffers <3
