### ISSUE TITLE
Get original error instance in errorHandler

### ISSUE THREAD

**Issue by BastienAr** [fastify/fastify#512]
When setting a custom error handler through `fastify.setErrorHandler(handler(error, reply))` the error is always an instance of [`Error`](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Error)

Is there a way to get the real instance of the error, especially when this is an `Ajv.ValidationError`, to be able to format the error, without JSON parsing the error message ?

**Comment by BigMurry** [comment]
You can try
```js
fastify.extendServerError((err) => {
  // the `err` should be the original error instance
})
```

**Comment by mcollina** [comment]
> Is there a way to get the real instance of the error, especially when this is an Ajv.ValidationError, to be able to format the error, without JSON parsing the error message ?

What do you mean by "real instance"?

**Comment by nasplachkov** [comment]
I am in exactly the same place as the OP and after looking into the code I saw where you handle it. 

[https://github.com/fastify/fastify/blob/ed65c02c9fa5084603646c99405a65e55763f40a/lib/validation.js#L66](https://github.com/fastify/fastify/blob/ed65c02c9fa5084603646c99405a65e55763f40a/lib/validation.js#L66)

You are using **fastJsonStringify** and later have to parse the data back to an object in order to use it. Since no one wants their regex patterns (for example) to be visible for whoever is using that endpoint, can we modify that part to return that errors array as is from Ajv? 

[https://github.com/fastify/fastify/blob/ed65c02c9fa5084603646c99405a65e55763f40a/lib/handleRequest.js#L141-L145](https://github.com/fastify/fastify/blob/ed65c02c9fa5084603646c99405a65e55763f40a/lib/handleRequest.js#L141-L145)

In order to not mess up the whole logic, I suggest something like adding that array as a property to the Error instance argument in **extendServerError**. Then we can do our own business as we wish.
At the moment we enter the else part. Seems like just stringifying there, but also attach as a property.

What do you think?

**Comment by mcollina** [comment]
Would you mind to send a PR? It’s not clear what you want to achieve, and code is easier to discuss.

**Comment by nasplachkov** [comment]
This is what I am thinking about: [https://github.com/fastify/fastify/pull/544](https://github.com/fastify/fastify/pull/544)
Having an additional property makes it easy to modify the response inside the **extendServerError**

**Comment by delvedor** [comment]
This can be closed, `extendServerError ` is no more a supported API and thank to https://github.com/fastify/fastify/pull/544 you will get the original validation error.
