### ISSUE TITLE
Property 'get' does not exists on type 'FastifyInstance'

### ISSUE THREAD

**Issue by YChebotaev** [fastify/fastify#5181]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Node.js version

21.1.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.1.1

### Description

<img width="538" alt="Screenshot 2023-11-29 at 18 08 24" src="https://github.com/fastify/help/assets/5302856/91dbdaef-0347-4c34-b7bb-c7552b3b05c0">

<img width="790" alt="Screenshot 2023-11-29 at 18 08 40" src="https://github.com/fastify/help/assets/5302856/a03a46e9-443e-46a5-b09e-b563712a0da0">

### Steps to Reproduce

1. Create project
2. Write code as in screenshot

### Expected Behavior

No bug

**Comment by Dar-win** [comment]
Make sure you're on Typescript 5.x.x.
The Fastify type declarations (in .d.ts) use const type parameters which were introduced in TS 5.0 but appear as errors in earlier Typescript versions, breaking the .d.ts and therefore the compiler won't catch it 

`
  listen(port: number | string, address?: string, backlog?: number): Promise<string>;

  ready(): FastifyInstance<RawServer, RawRequest, RawReply, Logger, TypeProvider> & PromiseLike<undefined>;
  ready(readyListener: (err: Error) => void): FastifyInstance<RawServer, RawRequest, RawReply, Logger, TypeProvider>;

  register: FastifyRegister<FastifyInstance<RawServer, RawRequest, RawReply, Logger, TypeProvider> & PromiseLike<undefined>>;

//The line below has const type declaration. Every method declared before this (including listen and register) work pretty well, but all other methods declared after this line will not be caught by the compiler because TS <5.0 assumes const is a syntax error and therefore everything else is a syntax error.
  route<
    RouteGeneric extends RouteGenericInterface = RouteGenericInterface,
    ContextConfig = ContextConfigDefault,
    const SchemaCompiler extends FastifySchema = FastifySchema,
  >(opts: RouteOptions<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider>): FastifyInstance<RawServer, RawRequest, RawReply, Logger, TypeProvider>;

  get: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
  head: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
  post: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
  put: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
  delete: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
  options: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
  patch: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
  all: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;

`

**Comment by Dar-win** [comment]
Make sure you're on Typescript 5.x.x.
The Fastify type declarations (in .d.ts) use const type parameters which were introduced in TS 5.0 but appear as errors in earlier Typescript versions, breaking the .d.ts and therefore the compiler won't catch it 

`
    index.d.ts
    listen(port: number | string, address?: string, backlog?: number): Promise<string>;
  
    ready(): FastifyInstance<RawServer, RawRequest, RawReply, Logger, TypeProvider> & PromiseLike<undefined>;
    ready(readyListener: (err: Error) => void): FastifyInstance<RawServer, RawRequest, RawReply, Logger, TypeProvider>;
  
    register: FastifyRegister<FastifyInstance<RawServer, RawRequest, RawReply, Logger, TypeProvider> & PromiseLike<undefined>>;
  
  //The line below has const type declaration. Every method declared before this (including listen and register) work pretty well, but all other methods declared after this line will not be caught by the compiler because TS <5.0 assumes const is a syntax error and therefore everything else is a syntax error.
    route<
      RouteGeneric extends RouteGenericInterface = RouteGenericInterface,
      ContextConfig = ContextConfigDefault,
      const SchemaCompiler extends FastifySchema = FastifySchema,
    >(opts: RouteOptions<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider>): FastifyInstance<RawServer, RawRequest, RawReply, Logger, TypeProvider>;
  
    get: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
    head: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
    post: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
    put: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
    delete: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
    options: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
    patch: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
    all: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;

`

**Comment by Dar-win** [comment]
Make sure you're on Typescript v5.x.x. The Fastify type declarations use const type parameters introduced in TS 5.0 but they appear as errors in TS <5.0, therefore the compiler won't recognize some methods such as get, post etc.
Here's a snippet of the instance.d.ts.

    instance.d.ts
    ...
    listen(port: number | string, address?: string, backlog?: number): Promise<string>;
    ready(): FastifyInstance<RawServer, RawRequest, RawReply, Logger, TypeProvider> & PromiseLike<undefined>;
    ready(readyListener: (err: Error) => void): FastifyInstance<RawServer, RawRequest, RawReply, Logger, TypeProvider>;
    register: FastifyRegister<FastifyInstance<RawServer, RawRequest, RawReply, Logger, TypeProvider> & PromiseLike<undefined>>;
  
	  //The line below has const type declaration. Every method declared before this (including listen and register) work pretty well, but all other methods declared after this line will not be caught by the compiler because TS <5.0 assumes const is a syntax error and therefore everything else is a syntax error.
	  
    route<
      RouteGeneric extends RouteGenericInterface = RouteGenericInterface,
      ContextConfig = ContextConfigDefault,
      const SchemaCompiler extends FastifySchema = FastifySchema,
    >(opts: RouteOptions<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider>): FastifyInstance<RawServer, RawRequest, RawReply, Logger, TypeProvider>;
  
    get: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
    head: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
    post: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
    put: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
    delete: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
    options: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
    patch: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;
    all: RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>;

**Comment by CanTheAlmighty** [comment]
I should add, if you're suffering from this issue in VSCode, as in, VSCode is not autocompleting this for you, even though it runs, make sure to switch the VSCode's internal version:

<kbd>Ctrl</kbd>/<kbd>CMD</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> > Select Typescript Version
