### ISSUE TITLE
 Enhance Readme with Dynamically Fetched Contributors' Avatars

### ISSUE THREAD

**Issue by aditya-armal** [fastify/fastify#5225]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Proposed Solution
Integrate a dynamic solution that fetches contributors' avatars from their GitHub profiles and displays them in the Readme. This will not only showcase the diverse community contributing to the project but also add a personal touch to the documentation.

### Motivation

Adding dynamically fetched contributors' avatars to the Readme file is not just a cosmetic enhancement; it's a visual celebration of our contributors' invaluable efforts. This addition fosters a stronger sense of community, encouraging both new and existing contributors to feel recognized and connected to the project. Let's make our Readme reflect the vibrant and diverse community that drives the success of our open-source endeavor.

### Example

<h2>🤝 Contributors</h2>

Thanks go to these wonderful people:

<a href="https://github.com/fastify/fastify/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=fastify/fastify" />
</a>

**Comment by aditya-armal** [comment]
I'm eager to contribute to the project by implementing the enhancement to dynamically fetch contributors' avatars in the Readme file—please assign this issue to me. Thanks!

**Comment by jsumners** [comment]
Feel free to jump in and work on this task!

We've decided not to assign the issue to avoid any ["cookie licking"](https://www.redhat.com/en/blog/dont-lick-cookie), so please remember these simple guidelines:

- First, check if there are any existing Pull Requests (PRs) related to this issue. Just check the notification in this page.

- If you create a PR or draft PR, make sure to link it to this issue using the [GitHub keyword method](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). It helps keep things organized, and you'll see a nice message here.

Don't worry about whether this issue is assigned to your GitHub handle or not—just dive right in. We're all about collaboration here!
