### ISSUE TITLE
Dependency AJV is not maintained

### ISSUE THREAD

**Issue by marco-ippolito** [fastify/fastify#5275]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello,
The dependency [AJV](https://github.com/ajv-validator/ajv) that it's in the fastify dependency tree, by [fastify/ajv-compiler](https://github.com/fastify/ajv-compiler/blob/main/package.json), is not currently being maintained.
There are a lot of bug reports that have been ignored https://github.com/ajv-validator/ajv/issues
Pull requests opened that have not been reviewed https://github.com/ajv-validator/ajv/pulls
There are currently only 2 maintainers that are not active https://github.com/orgs/ajv-validator/people
I would consider to reach out to the authors before forking.

**Comment by mcollina** [comment]
As an additional note, there are 30k in its OpenCollective: https://opencollective.com/ajv.

cc @epoberezkin

**Comment by epoberezkin** [comment]
Hey there!

> The dependency [AJV](https://github.com/ajv-validator/ajv) that it's in the fastify dependency tree, by [fastify/ajv-compiler](https://github.com/fastify/ajv-compiler/blob/main/package.json), is not currently being maintained.

I guess definitions of maintenance may wary :)
Ajv is a rather stable library that doesn't require too many changes.

What might be missing is answering with questions - most of the questions happen because people simply don't want to read the docs.

> There are a lot of bug reports that have been ignored https://github.com/ajv-validator/ajv/issues

Historically, most bug reports are not bugs, but rather misunderstandings and, again, the failure to read the docs, sadly. But we will triage.

There might be some build issues though.

Anyway, having said that, I just got some mid-level JS developer to help with that part time, and open to consider some other paid contributors - the project has a small reserve of funds for any important or urgent changes - I am not billing it for anything.

**Comment by epoberezkin** [comment]
Also, to differentiate, what doesn't happen is user support - I don't think it's a pre-requisite for an open source project to provide any level of support via issues, as there is a community support available via Stack Overflow. It's not the same as lack of maintenance though - security reports are reviewed and will be fixed if necessary.

**Comment by marco-ippolito** [comment]
@epoberezkin thanks a lot for your fast reply. Appreciate!

**Comment by epoberezkin** [comment]
Alright, so going through the bugs, only one or two _may be_ a real bug, but more looks like a limitation, and one is the compatibility issue with the most recent node.js - needs to be improved if confirmed.

I think the issue here is that github "issues" create a lot of support work for users that indiscriminately use bug label hoping to get more attention, instead of trying to review the documentation and existing issues.

**Comment by mcollina** [comment]
@epoberezkin I absolutely concur with you!
