### ISSUE TITLE
Logger methods are not bound to this

### ISSUE THREAD

**Issue by Hurtak** [fastify/fastify#5487]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.15.0

### Node.js version

20

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

MacOs 14.4.1

### Description

When using more functional style programming and you pass logger methods into other functions, the log functions crash with following error because they are not bound to correct this

```
TypeError: Cannot read properties of undefined (reading 'Symbol(pino.msgPrefix)')
    at LOG (/Users/hurtak/hello/stockstory/src/node_modules/.pnpm/pino@8.14.2/node_modules/pino/lib/tools.js:68:22)
    at getApp (/Users/hurtak/hello/stockstory/src/apps/api/src/app.ts:244:3)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /Users/hurtak/hello/stockstory/src/apps/api/src/serve.ts:182:15
```

Example code

```js
  const app = fastify({
    logger: true
  });

  app.log.error('This works')
  const logError = app.log.error
  logError('This crashes');
```

JavaScript console.log used to have the same issue.

One quick fix you can do is to manually patch the methods

```js
  const app = fastify({
    logger: true
  });
  app.log.error = app.log.error.bind(app.log)
  // also patch the rest of the log methods like info/warn/trace/...

  app.log.error('This works')
  const logError = app.log.error
  logError('This also works');
```

Can we make the logger methods bound to correct this by default?

**Comment by jsumners** [comment]
This is baseline JavaScript behavior. You must provide the correct context when passing functions by reference.

**Comment by Hurtak** [comment]
@jsumners Do we know why TypeScript is not able to detect this issue? The `@typescript-eslint/unbound-method` usually catches it.

![image](https://github.com/fastify/fastify/assets/6587821/6ca4d6ad-9fa4-46b7-95be-36636e7972a0)

Also, I remember few years back Chrome/Node also changed the JavaScript global `console` object so that its log methods are bound to the instance - so I am thinking if they were able to do it without breaking any code, doing it in Fastify should also probably be fine?

**Comment by mcollina** [comment]
Historically we did not do this because `.bind()` was incredibly expensive.
We can 100% re-evaluate this, but it should really happen in the pino repository.

There are two problems with that:

1. pino has a system that allows creating child loggers with almost no overhead. As you can see in the [`child`](https://github.com/pinojs/pino/blob/8db130eba0439e61c802448d31eb1998cebfbc98/lib/proto.js#L82) implementation, we don't touch the logging functions. Adding the `bind()` for each of the functions would add some overhead. This could be investigated.
2. pino assigns no-op function for disabled levels, it introduces a race condition if the level of the logger is changed.
