### ISSUE TITLE
req.headers or req.query null in a 404 handler

### ISSUE THREAD

**Issue by ritikrao1** [fastify/fastify#5494]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Node.js version

14.18.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

i am using `req.headers` and `req.query `in the `setNotFoundHandler` but it seems one of the values either req.headers or req.query are null, in which scenarios can this happen
one workaround that i can think if is initialising headers and query as empty objects if they are null, is ther any good solution or am i doing something wrong

### Expected Behavior

req.headers and req.query should be empty object by default in any scenario

**Comment by climba03003** [comment]
I doubt that `request.headers` will be `null`. It is just returning `IncomingMessage.headers`.

https://github.com/fastify/fastify/blob/a00f3ca91d4bea348e3dd71dfeb2edf017285aaf/lib/request.js#L294-L304

`request.query` is on-purpose passing null.
https://github.com/fastify/fastify/blob/a00f3ca91d4bea348e3dd71dfeb2edf017285aaf/lib/fourOhFour.js#L178

**Comment by ritikrao1** [comment]
but this isn't happening on all 404 requests, in some of them query is coming null and in other it isn't

**Comment by climba03003** [comment]
I would like to see a reproducible example before judging.

**Comment by shwetd19** [comment]
Hey there 👋,

The core of the issue is that `req.headers` and `req.query` might be null under certain conditions, which shouldn't normally happen. A potential workaround you suggested is initializing them as empty objects if they are null. However, I wonder if there's a more elegant solution or if there's something else going on that we're missing.

A potential fix could involve ensuring that `req.headers` and `req.query` are always initialized as empty objects by default, regardless of the request context. This might involve tweaking the request initialization logic in Fastify to guarantee these properties are never null.

Would it be possible to let me tackle this? 

Cheers,
@shwetd19

**Comment by jsumners** [comment]
Closing due to lack of response. Please re-open with a reproduction.
