### ISSUE TITLE
Plugin: Generate endpoints based on file names on a directory.

### ISSUE THREAD

**Issue by georgeiliadis91** [fastify/fastify#5514]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

A plugin that will allow users to put some files of a given format in a directory and auto generate endpoints based on the file names. 

This will allow users to prototype and host simple configuration files without bothering to write more than a couple of lines of code.

### Motivation

In the past there has been need to create quick apis to share configs amongst different applications.

This would allow users to just add a file on a directory and serve it via calling an endpoint with the file name. 
or even just update a file on a git repo and toggle settings on and off.

In our case we went with the now deprecated netlify-cms. I believe this would be a fairly straight forward thing to add and it could find some use in the fastify plugin ecosystem. 

I am aware that there are ways to do with various cloud providers and their storage solutions. But this allows you do it on your own whilst having additional control on the endpoints via fastify's plugin ecosystem.

### Example

Let's say you have a folder called file, the file naming can be dynamic itself. 

You would have a file structure like this 

```sh
|-- file
|   |-- foo.json
|   |-- bar.json
```

That way executing a request at 
```
myapi.com/files/foo 
```
would return the json content of the foo.json file.

You could register this plugin as below, passing an optional f

```js

fastify.register(require('./file-based-routes-plugin'), {
  fileDirectory: 'files'
});

**Comment by jsumners** [comment]
https://www.npmjs.com/package/@fastify/autoload

**Comment by mcollina** [comment]
This is an easy plugin to do.

**Comment by aliharis99** [comment]
Hi, would it be alright if I pick up this issue, please?

**Comment by gurgunday** [comment]
Go ahead!

**Comment by STAR-173** [comment]
Hey, had some questions regarding this issue
- do you want the files to be automatically converted into the routes ( for example if you paste a file into the `files` folder, should it automatically be converted into a route ?)
- So it should just return the content of the json file, kind of like a test file to try things out on the client side .

**Comment by mcollina** [comment]
Yes exactly!

**Comment by kunal097** [comment]
Is anybody working on this or can I pick this up? 
Do we need to support only JSON or it can other files too (like YAML)

**Comment by jsumners** [comment]
Feel free to jump in and work on this task!

We've decided not to assign the issue to avoid any ["cookie licking"](https://www.redhat.com/en/blog/dont-lick-cookie), so please remember these simple guidelines:

- First, check if there are any existing Pull Requests (PRs) related to this issue. Just check the notification in this page.

- If you create a PR or draft PR, make sure to link it to this issue using the [GitHub keyword method](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). It helps keep things organized, and you'll see a nice message here.

Don't worry about whether this issue is assigned to your GitHub handle or not—just dive right in. We're all about collaboration here!

**Comment by kunal097** [comment]
![image](https://github.com/fastify/fastify/assets/23140769/b2ed5dc6-da53-4164-9e98-9eaac8708ded)
 The attached image shows that we have 2 files available in the data directory which gonna auto-load and will be available on respective paths i.e./data/path1.json and /data/path2.json.
 
![image](https://github.com/fastify/fastify/assets/23140769/184a8fad-803f-4bd1-9cf1-d39f6042a34a)

If this is the desired result then help me with some questions or do let me know what's missing. 

- Do we need to integrate this in Fastify itself or do we need to create a separate plugin for this?

- Does it support YAML or just JSON?

- What needs to be done if the file fails to load due to any reason? Do we need to throw an error or silently skip that file?

**Comment by mcollina** [comment]
> Do we need to integrate this in Fastify itself or do we need to create a separate plugin for this?

Separate plugin

> Does it support YAML or just JSON?

only json for now

> What needs to be done if the file fails to load due to any reason? 

log a warning

> Do we need to throw an error or silently skip that file?

log a warning and skip the file

**Comment by kunal097** [comment]
Ok Roger, will work on these.

**Comment by kunal097** [comment]
https://www.npmjs.com/package/@pybot/fastify-autoload

Look at this, does this fulfill the requirement?

**Comment by mcollina** [comment]
Yes! Can you open a PR to add it to the ecosystem page?

**Comment by kunal097** [comment]
Sure, but can you help me with the steps or any doc which I can refer?

**Comment by mcollina** [comment]
Add it to this list: https://github.com/fastify/fastify/blob/main/docs/Guides/Ecosystem.md#community

in alphabetical order
