### ISSUE TITLE
feat: add custom http methods

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#5553]
We should design a new API to let plugins add new HTTP methods to cover this new trend (that many vendors support).

              My general review is that whatever architecture is needed to be added such that non-standard methods can be added via a plugin should be added, and then all of the webdav methods removed and added via such a plugin.

_Originally posted by @jsumners in https://github.com/fastify/fastify/pull/5549#pullrequestreview-2160471860_

**Comment by gurgunday** [comment]
Since we now use [Sets for HTTP methods](https://github.com/fastify/fastify/blob/de1c064d725eb1ce1ea58f6c139747a8cf287bbe/lib/httpMethods.js) instead of hard-coded if else statements, this should be fairly simple

Just to voice my opinion, I also support the idea of Fastify core staying as lean as (pragmatically) possible by only supporting standards and being extendable for other use cases; otherwise for this specific case for instance, we will get more and more PRs asking for more methods to be added until we reach parity with Node.js itself `http.METHODS`

As per our principles:

> If something could be a plugin, it likely should be
