### ISSUE TITLE
The stream error of Openai

### ISSUE THREAD

**Issue by solid-component** [fastify/fastify#5584]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28.1

### Node.js version

v22.2.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.1

### Description

npm install openai
```ts 
const ai = new OpenAI();

async function chat() {
  const completion = await ai.chat.completions.create({
    messages: [
      {
        role: "system",
        content: "你是豆包，是由字节跳动开发的 AI 人工智能助手",
      },
      { role: "user", content: "常见的十字花科植物有哪些？" },
    ],
    model: "ep-20240722220630-jw4jf",
    stream: true,
  });
}
 
fastify.post("/api/chat", async (request, reply) => {
    try {
      const stream = await chat();
      reply.header("Content-Type", "application/octet-stream");
      return stream.toReadableStream()
    } catch (e) {
      console.log("错误", e);
      reply.send({ code: 400, msg: e });
    }
  });
  done();
```
get a error:
TypeError: The "readableStream" argument must be an instance of ReadableStream. Received an instance of ReadableStream
    at Object.newStreamReadableFromReadableStream (node:internal/webstreams/adapters:511:11)

and   can't get the stream properly on the web

**Comment by mcollina** [comment]
Because for whatever reason, they are not using the global, but a polyfill: https://github.com/openai/openai-node/blob/22896e88e97c0e8621bf74c666a6fc7d9d832267/src/_shims/node-runtime.ts#L18.

Note that there is no reason for them to do this since April 2022 (when Node.js v14 exited LTS).

You might try doing what we are doing in ai-warp: https://github.com/platformatic/ai-warp/blob/main/ai-providers/open-ai.ts.

(Generically, you might want to use ai-warp anyway, as it probably does what you are looking for anyway).

**Comment by climba03003** [comment]
I am closing the issue because it is un-related to `fastify` itself.

**Comment by solid-component** [comment]
Thanks

**Comment by RobertCraigie** [comment]
Hey @solid-component, openai-node maintainer here, we've removed this polyfill in `v4.53.1`, would you be interested / able to try it out again?
