### ISSUE TITLE
Getting 'undefined' for reply.redirect when using middleware (fastify.use()) 

### ISSUE THREAD

**Issue by HappyZombies** [fastify/fastify#598]
I am trying to create a simple middleware that will redirect any url ending in "/" to one without the "/" trailing "/". Here is what I wrote. 

```
fastify.use((request, reply, next) => {
    if (request.url.substr(-1) == '/' && request.url.length > 1) {
        reply.redirect(request.url.slice(0, -1));
        return;
    }
    next();
})
```

Hitting my url "/api/test" works and gets me my data. But when I hit /api/test/ I get that .redirect is not a method. reply.redirect returns undefined.

When I create a route, for example:

```
fastify.get(/'hello', (request, reply)=>{
 console.dir(reply.redirect);
});
```

I get that 'redirect' is indeed a function.

Am I doing something wrong? Or is the redirect simply not available for middlewares (when using .use())? I tried wrapping the middleware in fastify.ready() but still no success, in fact, the middleware doesn't run at all. It could be that maybe I didn't read something right, so any directions or help would be appreciated. Really don't want to add the middleware to every single route. Thanks!

**Comment by StarpTech** [comment]
@HappyZombies on the first view I would say you have to call `next()` you are still in a middleware cycle.

```js
fastify.use((request, reply, next) => {
    if (request.url.substr(-1) == '/' && request.url.length > 1) {
        reply.redirect(request.url.slice(0, -1));
        next();
        return;
    }
    next();
})
```

**Comment by jsumners** [comment]
I recommend writing a [fastify-plugin](https://github.com/fastify/fastify-plugin) that adds an `onRequest` hook. The hook would:

```js
req.setHeader('Location', '/foo')
req.end()
```

**Comment by HappyZombies** [comment]
@StarpTech , @jsumners , I added a hook instead of a middleware. The hook looks like this 

```
app.addHook('preHandler', (request, reply, next) => {
    const url = request.req.url;
    if (url.substr(-1) == '/' && url.length > 1) {
        reply.redirect(url.slice(0, -1));
        next();
        return;
    }
    next();
});
```

However I feel like this is not right. I wonder if this is okay and if it could cause any problems down the line. I still feel as though that this should be a middleware, not a hook.

**Comment by StarpTech** [comment]
@HappyZombies you just using the wrong middleware signature. https://github.com/fastify/fastify/blob/master/docs/Middlewares.md

**Comment by StarpTech** [comment]
But also with this I get `Error: Can't set headers after they are sent.`
```js
fastify.use((req, res, next) => {
  if (req.url.substr(-1) == '/' && req.url.length > 1) {
      res.writeHead(302, {'Location': 'http://127.0.0.1' + fastify.server.address().port + req.url.slice(0, -1)});
  }
  next();
})
```

**Comment by StarpTech** [comment]
That's a bug because `.send()` method internally does not check the raw response state. (finished, headersSent)

**Comment by StarpTech** [comment]
@HappyZombies the use of hook is correct look in the https://github.com/fastify/fastify/blob/master/docs/Lifecycle.md

**Comment by StarpTech** [comment]
@delvedor due to the fact that the 404 is [set](https://github.com/fastify/fastify/blob/master/fastify.js#L589) via the `reply` interface the user can't override it in a middleware. I still get 404. 

```js
fastify.use((req, res, next) => {
  if (req.url.substr(-1) == '/' && req.url.length > 1) {
      res.setHeader('Location', 'http://127.0.0.1' + fastify.server.address().port + req.url.slice(0, -1))
      res.statusCode = 302
  }
  next();
})
```

**Comment by jsumners** [comment]
@HappyZombies my opinion is that the "middleware" support is there merely to support the ones already written for other frameworks. I think Fastify plugin's are the better way of writing modules for Fastify.

Take a look at https://github.com/fastify/fastify/blob/master/docs/Lifecycle.md . Notice that the `onRequest` hook comes _before_ the middleware execution. I suggested `onRequest` specifically because it is the earliest point at which you can take complete control of the request.

**Comment by StarpTech** [comment]
@jsumners `onRequest` has the same interface as a middleware. Unless we fixed the middleware issues it's still not safe to work with raw resp.

**Comment by jsumners** [comment]
No, that's not really the problem. As I suspected, but didn't mention, the real issue is that you can't override the router in this manner. The following doesn't work because a request to `/foo/` will return a 404, while a request to `/foo` works as expected:

```js
'use strict'

const url = require('url')
const fastify = require('fastify')()
const fp = require('fastify-plugin')

const plugin = fp(function (instance, opts, done) {
  instance.addHook('onRequest', function (req, reply, next) {
    const _url = url.parse(req.url)
    if (_url.pathname !== '/' && _url.pathname.substr(-1) === '/') {
      reply.setHeader('Location', _url.pathname.substr(0, _url.pathname.length - 1))
      reply.statusCode = 301
      reply.end()
      return
    }
    next()
  })
  done()
})

fastify.register(plugin)

fastify.get('/foo', function (req, reply) {
  reply.send({foo: 'bar'})
})

fastify.listen(8000)
```

**Comment by HappyZombies** [comment]
@jsumners, what you are saying is exactly why I tried to make the middleware / hook to go around this issue of "/foo" working and "/foo/" returning 404. I kinda figured that it "worked" by design.

**Comment by StarpTech** [comment]
@HappyZombies,  @nwoltman has a good workaround

```js
fastify.setNotFoundHandler(function ({req}, reply) {
  if (req.url.substr(-1) == '/' && req.url.length > 1) {
    reply.redirect(req.url.slice(0, -1))
    return
  }
  reply.code(404).send('Not found')
})
```

**Comment by StarpTech** [comment]
Due to inactivity, I close it. Feel free to reopen.

**Comment by tandrewnichols** [comment]
So . . . the docs for middleware says, "Fastify provides an asynchronous middleware engine out-of-the-box, which is compatible with Express and Restify middleware." I feel fairly strongly, based on this issue, that you should remove that claim  (I mean the compatibility part). Express provides its own version of request and response to each middleware, so things like `req.get()` and `res.redirect()` work. Fastify provides the base HttpRequest and HttpResponse instances. That's a _major_ difference. If you're coming from Express, you would (based on that claim) expect to be able to _reuse_ your existing middleware functions, but unless you're not interacting with the request and response at all, that's likely to not be true. Like, I expected that this would work:

```
fastify.use('/some/path', (req, res, next) => {
  res.redirect('/another/path');
});
```

But it doesn't. You get "res.redirect is not a function."

I don't know if you _care_ about compatibility with those frameworks (the suggestion above to use lifecycle hooks kinda suggests no). If you don't, just removing that claim seems sufficient. If you do, providing the fastify request and response objects to middleware functions seems like a starting point, although I'm still not convinced that provides complete compatibility with Express (can't speak to Restify) because the Express `req` and `res` aren't identical to the Fastify `request` and `reply`.
