### ISSUE TITLE
LTS strategy

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#670]
As mentioned in https://github.com/fastify/fastify/issues/229#issuecomment-358108181, it would be a good idea to have a published LTS strategy. Even if it is as simple as "we only support the active X release of semantic version X.Y.Z releases."

Use this issue to hash it out.

**Comment by mcollina** [comment]
I would like to call 1.0.0 LTS (supported) for a 6 month timeline minimum. And maintenance (security fixes) for another 6 months.

All semver-major work should happen in master but we would issue backport PRs to a 1.x.x branch.

And we need semver-* tags.

I would also note that we should start squashing commits when landing, because that would simplify backporting.

**Comment by jsumners** [comment]
I can get onboard with all of those suggestions.

**Comment by jsumners** [comment]
@fastify/fastify do you agree with the proposal set for by @mcollina?

**Comment by nwoltman** [comment]
Absolutely :)
