### ISSUE TITLE
Fails with supertest

### ISSUE THREAD

**Issue by timwis** [fastify/fastify#704]
#### What are you trying to achieve or the steps to reproduce?

I'd like to use [supertest](https://github.com/visionmedia/supertest) to test my fastify app. This worked fine with version `0.9.0` last year but I upgraded and it started failing.

#### What was the result you received?

```
TypeError: Cannot read property 'logLevel' of undefined
Server.fastify (node_modules/fastify/fastify.js:175:67)
```
Reproduction available at [timwis/fastify-supertest-demo](https://github.com/timwis/fastify-supertest-demo)

#### What did you expect?
Passing tests

#### Context

* *node version*: 9.3.0
* *fastify version*: >=0.39.0
* *os*: Mac
* *any other relevant information*:

**Comment by delvedor** [comment]
Hi! Thank you for checking out Fastify!
From version [`v0.39.0`](https://github.com/fastify/fastify/releases/tag/v0.39.0) the function returned by the factory is no more the "classic" http handler, with request and response objects.
The http handler used by node is now an internal function, `router.lookup`, which calls the function that is returned by the factory.

Why this change?
Our router builds the context for every request, so it must be the very first function called by the http handler.

If you want to use fake http injection testing, I suggest you to use our api [`inject`](https://github.com/fastify/fastify/blob/master/docs/Testing.md#testing-with-http-injection), which solves your issue.

Currently `supertest` does not work because the function that it needs is not exposed.

**Comment by timwis** [comment]
Really helpful response - thanks!

**Comment by nwoltman** [comment]
@delvedor Is there any reason for fastify to not be compatible with `supertest`? It could be done by changing only a few lines of code.

**Comment by delvedor** [comment]
@nwoltman I guess we could expose `router.lookup` in some way.
The question is "do we want to expose an api just to support an external testing library"?
Do not forget that will be another thing to maintain and that we could break in the future.
That's why we dropped the direct support to `Boom` and `Joi`.

**Comment by jsumners** [comment]
I'm 👎 on exposing stuff just to support such a library. At least without significant demand. And the library in question looks to not be maintained (no update in a year and >100 issues).

**Comment by nwoltman** [comment]
It's not really any extra maintenance for us. All we need to do is expose a different function as the "fastify object". Currently I don't see any particular reason for [this function](https://github.com/fastify/fastify/blob/ef2215711ca4e348f91b32c8c413d1779692bebd/fastify.js#L187) to be the "fastify object" returned by `require('fastify')()` anyway.

**Comment by armandopadilla** [comment]
just want to revisit this. Another use case to expose the function. This is also affecting running fastify on AWS lambda using aws-serverless-express.  require('fastify')() ,  returns an object yet the library is looking for a function.

**Comment by mcollina** [comment]
Can you open up a new issue? I’m happy to revist, but we should really track this  as a new bug/feature.

**Comment by mcollina** [comment]
I think we need to add a section to our document on how to run on lambda.
Il giorno mar 31 lug 2018 alle 19:19 Nathan Woltman <
notifications@github.com> ha scritto:
