### ISSUE TITLE
Audit documentation and website

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#801]
Prior to issuing v1.0.0, we need someone who is familiar with the website generation process to audit the documentation and website to determine what fixes need to be implemented. For example, on https://www.fastify.io/docs/latest/Server-Methods/ click the "Fastify factory function" link. Notice that it does not work.

I really have no idea how we are supposed to write the documentation such that the website builds correctly. I'm used to simply writing standard Markdown and generating HTML from it.

**Comment by delvedor** [comment]
cc @lmammino

**Comment by jsumners** [comment]
@lmammino do you have any input here?

**Comment by lmammino** [comment]
Sorry for the very late reply, I have been very busy lately 😞 

The issue with that specific example is that it does not use the markdown markup for the link (see https://raw.githubusercontent.com/fastify/fastify/master/docs/Server-Methods.md)

```
## Server Methods

<a name="server"></a>
#### server
`fastify.server`: The Node core [server](https://nodejs.org/api/http.html#http_class_http_server) object as returned by the <a href="https://github.com/fastify/fastify/blob/master/docs/Factory.md"><code><b>Fastify factory function</b></code></a>.
```

We should change it to proper markdown in order for the current build process to pick it up and be able to update the link so that it works inside the website.

Another approach might be to make the build process smarter and able to catch this kind of links too.

I am not sure if this is enough for this issue or if you are planning to do some sort of bigger review

**Comment by lmammino** [comment]
If it's just a matter of styling here, wouldn't this markdown generate the same result:

```markdown
[**`Fastify factory function`**](https://github.com/fastify/fastify/blob/master/docs/Factory.md).
```


---

**Preview**:

[**`Fastify factory function`**](https://github.com/fastify/fastify/blob/master/docs/Factory.md).

**Comment by jsumners** [comment]
I think what it comes down to is we should have a style guide we can easily reference.

**Comment by mcollina** [comment]
I think we can close this.
