### ISSUE TITLE
about the log

### ISSUE THREAD

**Issue by weivea** [fastify/fastify#863]
i really hope you can remove the logger in fastify? 
it's  Tightly coupled with fastify,  This leads to that we can't do more design on logger , 
and every request print two logs : incoming request   / request completed .
it's not elegant
please，please，please，please，please，please，please，please，please，please，please，please
remove the logger

**Comment by mcollina** [comment]
Logging is the easiest way to slow down your application. It is also a very important non-functional requirement of every application.

Feel free not to use it, and roll out your own using our hooks.

**Comment by delvedor** [comment]
@weivea the logger is integrated inside the framework by design because is really expensive, we worked a lot to optimize it and even more did @mcollina and the pino team in https://github.com/pinojs/pino.
The integrated logger is here to stay, but if you build a logger with a compatible api you can use one of your own as documented [here](https://github.com/fastify/fastify/blob/master/docs/Logging.md).

 I highly recommend you to see https://www.youtube.com/watch?v=Dnx2SPdcDSU and read https://medium.com/@nearform/the-cost-of-logging-9faa11fd053.

Thank you for checking out Fastify.
