### ISSUE TITLE
Allow middleware to be added to routes when defined

### ISSUE THREAD

**Issue by chrismpettyjohn** [fastify/fastify#942]
Example
```
fastify.get('/link', Middleware, Controller) 
```

or

```
fastify.get('/link', Middleware
fastify.get('/link', Controller)
```

**Current Behavior**
First example doesn't work at all and considers it an option.  Second example will return
```{ AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route```

**Comment by chrismpettyjohn** [comment]
Currently handling this issue with a hook (preHandler)
```javascript
                HTTP.server.addHook('preHandler', (async (request, reply, next) => {
                  if (request.raw.url == link && request.raw.method == data.method) {
                    console.log('u called?')
                    request = await HTTP.middleware[data.middleware](request, reply)
                    next()
                  } else {
                    next()
                  }
                }))
```

**Comment by delvedor** [comment]
Hi, thank you for contributing to Fastify!
Personally I would not support this feature, even if we do support Express-style middlewares, Fastify is not a middleware oriented framework, you should use the `use` api.

If you want that a middleware to run just for one route you could encapsulate it inside a plugin:
```js
function endpoints (fastify, opts, next) {
  fastify.get(...)
  fastify.post(...)

  fastify.register((instance, opts, next) => {
    fastify.use(yourMiddleware)
    fastify.get(...)
    next()
  })

  next()
}
```

In this way that specific middleware will run only inside that nested plugin.

A completely different concept are *hooks*. An hook is an "event" that is triggered in a specific moment of the lifecycle (`onRequest`, `preHandler`, `onSend`...) and them are not compatible with Express middlewares.

Finally, [this](https://github.com/fastify/fastify/issues/942#issuecomment-389996714) hook is not correct, because you are using both `next` and *async-await*.
If you are using *async-await* you **should not** use `next`, everything is handled automatically.

I suggest you to read our [hooks](https://github.com/fastify/fastify/blob/master/docs/Hooks.md) and [middlewares](https://github.com/fastify/fastify/blob/master/docs/Middlewares.md) documentation :)

**Comment by chrismpettyjohn** [comment]
Hey,
I looked into the documentation more and realized that Fastify has a beforeHandler() function which works perfectly for my situation!  

Much appreciation for this project

**Comment by Vandell63** [comment]
Maybe late, but helpful for some later ->
> ```js
> function endpoints (fastify, opts, next) {
>   fastify.get(...)
>   fastify.post(...)
> 
>   fastify.register((instance, opts, next) => {
>     instance.use(yourMiddleware) <===== NOT FASTIFY, but the actual instance
>     fastify.get(...)
>     next()
>   })
> 
>   next()
> }
> ```
